name = "client"
version = "0.2.0"
gleam = ">= 1.18.0"

[dependencies]
host = { path = "../host" }
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
core = { path = "../core" }
storage = { path = "../storage" }
session = { path = "../session" }
machine = { path = "../machine" }
prompt = { path = "../prompt" }
events = { path = "../events" }
runtime = { path = "../runtime" }
broker = { path = "../broker" }
provider = { path = "../provider" }
tools = { path = "../tools" }
codemode = { path = "../codemode" }
mcp = { path = "../mcp" }
gleam_mcp = { git = "https://github.com/Roasbeef/gleam-mcp.git", ref = "686955fc0461630bf64a4dc8eb51565dc7ca1ac9" }
lsp = { path = "../lsp" }
telemetry = { path = "../telemetry" }
session_view = { path = "../session_view" }
web_view = { path = "../web_view" }
lustre = "== 5.7.1"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
weft = "== 0.4.5"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
mist = { git = "https://github.com/Roasbeef/mist.git", ref = "28b43178ff57bfb619c64b8c3544831646d5fdb9" }
simplifile = ">= 2.0.0 and < 3.0.0"
argv = ">= 1.1.0 and < 2.0.0"
tom = ">= 2.1.0 and < 3.0.0"
gleam_regexp = ">= 1.1.1 and < 2.0.0"

[dev_dependencies]
gleamy_bench = ">= 0.6.0 and < 1.0.0"
sqlight_loom = "== 1.2.1"
tui = { path = "../tui" }
etui = { git = "https://github.com/Roasbeef/etui.git", ref = "7365d4773a3aeba3f394e3d5fd06a77fa7e26fe2" }
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
