// Code generated by scripts/gen-tags.py from protocol/enforcement-tags.toml; DO NOT EDIT.
// source sha256: 94ee6475acc42ee37e29a0a263fba85fad2101d672d8e3a01ba728e748b19c30

package jail

// The enforcement tag vocabulary: the strings this helper writes into
// hello.features and exec_exit.enforcement, and that the broker's
// exec.gleam reads back through the generated broker/tags module. Edit
// protocol/enforcement-tags.toml and run `make gen-tags`; never this file.

// TagRlimits is the layer tag "rlimits".
// Per-process resource ceilings; needs no kernel opt-in, so always
// advertised. Emitted as: feature; on: linux, darwin, other.
const TagRlimits = "rlimits"

// TagPgroup is the layer tag "pgroup".
// Each execution gets its own session and process group, signalled as a
// unit. Emitted as: feature; on: linux, darwin, other.
const TagPgroup = "pgroup"

// TagDegraded is the layer tag "degraded".
// The strongest platform jail (bwrap or Seatbelt) is unavailable on this
// host. Emitted as: feature; on: linux, darwin, other.
const TagDegraded = "degraded"

// TagPlatformUnsupported is the layer tag "platform-unsupported".
// The build has no jail for its operating system at all; worse than
// degraded. Emitted as: feature; on: other.
const TagPlatformUnsupported = "platform-unsupported"

// TagBwrap is the layer tag "bwrap".
// Bubblewrap namespaces and mount plan; applied only once stage 2 has
// reported from inside. Emitted as: feature, applied, skip; on: linux.
const TagBwrap = "bwrap"

// TagLandlock is the layer tag "landlock".
// Landlock filesystem rules, the second filesystem layer and the first in
// degraded mode. Emitted as: feature, applied, skip; on: linux.
const TagLandlock = "landlock"

// TagSeccomp is the layer tag "seccomp".
// Seccomp-filter support; the applied form is seccomp-net. Emitted as:
// feature, skip; on: linux.
const TagSeccomp = "seccomp"

// TagCgroupV2 is the layer tag "cgroup-v2".
// A per-execution cgroup v2 group holding the memory and process ceilings.
// Emitted as: feature, applied, skip; on: linux.
const TagCgroupV2 = "cgroup-v2"

// TagSeatbelt is the layer tag "seatbelt".
// The macOS Seatbelt profile (sandbox-exec) entered around the execution.
// Emitted as: feature, applied, skip; on: darwin.
const TagSeatbelt = "seatbelt"

// TagMounts is the layer tag "mounts".
// The audited mount plan: applied carries counts and a plan digest,
// skipped names a widened path. Emitted as: applied, skip; on: linux.
const TagMounts = "mounts"

// TagNoNewPrivs is the layer tag "no-new-privs".
// PR_SET_NO_NEW_PRIVS: no privilege gain through setuid binaries or file
// capabilities. Emitted as: applied, skip; on: linux.
const TagNoNewPrivs = "no-new-privs"

// TagSeccompNet is the layer tag "seccomp-net".
// A seccomp filter denying direct sockets under network off and proxy
// policies. Emitted as: applied; on: linux.
const TagSeccompNet = "seccomp-net"

// TagSeatbeltFs is the layer tag "seatbelt-fs".
// The Seatbelt filesystem plan, with root counts and a plan digest.
// Emitted as: applied; on: darwin.
const TagSeatbeltFs = "seatbelt-fs"

// TagSeatbeltNet is the layer tag "seatbelt-net".
// Seatbelt denial of direct network access under network off and proxy
// policies. Emitted as: applied; on: darwin.
const TagSeatbeltNet = "seatbelt-net"

// TagRlimitFsize is the layer tag "rlimit-fsize".
// RLIMIT_FSIZE ceiling on the size of any file the execution writes.
// Emitted as: applied; on: linux, darwin.
const TagRlimitFsize = "rlimit-fsize"

// TagRlimitCpu is the layer tag "rlimit-cpu".
// RLIMIT_CPU ceiling on CPU seconds. Emitted as: applied; on: linux,
// darwin.
const TagRlimitCpu = "rlimit-cpu"

// TagRlimitAddressSpace is the layer tag "rlimit-address-space".
// RLIMIT_AS ceiling standing in for the memory limit, where the kernel
// accepts one. Emitted as: applied, skip; on: darwin.
const TagRlimitAddressSpace = "rlimit-address-space"

// TagRlimitProcesses is the layer tag "rlimit-processes".
// RLIMIT_NPROC ceiling standing in for the process limit; per-user, not
// per-execution. Emitted as: applied, skip; on: darwin.
const TagRlimitProcesses = "rlimit-processes"

// TagDarwinProcessLifecycle is the layer tag "darwin-process-lifecycle".
// The one containment property Seatbelt cannot give: no PID namespace or
// subreaper. Emitted as: skip; on: darwin.
const TagDarwinProcessLifecycle = "darwin-process-lifecycle"

// TagStage2 is the layer tag "stage2".
// Stage 2 sent no enforcement report, so its in-process layers cannot be
// confirmed. Emitted as: skip; on: linux, darwin.
const TagStage2 = "stage2"

// TagNetworkProxy is the layer tag "network-proxy".
// Proxy-mode network policy: direct network was disabled but the allowlist
// was not enforced. Emitted as: skip; on: linux, darwin, other.
const TagNetworkProxy = "network-proxy"

// TagPlatformRestrictions is the layer tag "platform-restrictions".
// Stage 2 has no in-process driver for this operating system. Emitted as:
// skip; on: other.
const TagPlatformRestrictions = "platform-restrictions"

// TagJail is the layer tag "jail".
// Opens the platform-unsupported reason: this build has no sandbox for its
// OS. Emitted as: skip; on: other.
const TagJail = "jail"

// PrefixSkip is the separator "skip:".
// Marks an enforcement entry as a layer that was NOT applied; the rest is
// the layer tag and a reason.
const PrefixSkip = "skip:"

// PrefixLandlockAbi is the separator "landlock:abi=".
// Landlock applied entry; the number that follows is the kernel ABI
// version.
const PrefixLandlockAbi = "landlock:abi="

// PrefixMountsReport is the separator "mounts:".
// Mount-audit applied entry; comma-separated counts and a plan digest
// follow.
const PrefixMountsReport = "mounts:"

// PrefixSeatbeltFsReport is the separator "seatbelt-fs:".
// Seatbelt filesystem applied entry; comma-separated counts and a plan
// digest follow.
const PrefixSeatbeltFsReport = "seatbelt-fs:"
