# Loom — common developer commands.
#
# Every target is a thin wrapper over the scripts and package tooling, so
# what CI runs and what you run locally are the same commands.

PACKAGES := host core storage session machine prompt telemetry runtime provider \
	broker mcp lsp tools cap ext codemode events client conformance tui lint
GO_PKG   := packages/sandbox
HELPER   := $(GO_PKG)/loom-exec
PREFIX   ?= $(HOME)/.local

.DEFAULT_GOAL := help

# ---------------------------------------------------------------- checking

.PHONY: check
check: binaries ## Full gate: current helpers, format, build, tests, and lint
	@scripts/check.sh

.PHONY: check-release-update
check-release-update: ## Verify release archives, native downloads, and installation
	@python3 scripts/with_timeout.py 1200 -- bash scripts/check-release-update.sh

.PHONY: check-gleam
check-gleam: binaries ## Full gate for the Gleam packages only
	@scripts/check.sh $(PACKAGES)

.PHONY: check-%
check-%: binaries ## Full gate for one package, e.g. make check-machine
	@scripts/check.sh $*

.PHONY: test
test: ## Run tests only (skips format check), all Gleam packages
	@set -e; for p in $(PACKAGES); do \
		echo "==> $$p"; bash scripts/test.sh $$p; \
	done

.PHONY: test-%
test-%: ## Run tests for one package, e.g. make test-core
	@bash scripts/test.sh $*

.PHONY: build
build: ## Warning-free build of every Gleam package
	@set -e; for p in $(PACKAGES); do \
		echo "==> $$p"; (cd packages/$$p && gleam build --warnings-as-errors); \
	done

# --------------------------------------------------------------- formatting

# Gleam sources that live outside a package: the code-mode migration
# sample is a documentation artifact and a test fixture at once, so no
# package's `gleam format` reaches it.
LOOSE_GLEAM := $(wildcard docs/examples/*.gleam)

.PHONY: fmt
fmt: ## Format all Gleam and Go sources in place
	@set -e; for p in $(PACKAGES); do \
		(cd packages/$$p && \
			paths="src test"; [ ! -d dev ] || paths="$$paths dev"; \
			gleam format $$paths); \
	done
	@test -z "$(LOOSE_GLEAM)" || gleam format $(LOOSE_GLEAM)
	@cd $(GO_PKG) && gofmt -w .
	@echo "formatted"

.PHONY: fmt-check
fmt-check: ## Verify formatting without writing (what CI enforces)
	@set -e; for p in $(PACKAGES); do \
		(cd packages/$$p && \
			paths="src test"; [ ! -d dev ] || paths="$$paths dev"; \
			gleam format --check $$paths); \
	done
	@test -z "$(LOOSE_GLEAM)" || gleam format --check $(LOOSE_GLEAM)
	@test -z "$$(cd $(GO_PKG) && gofmt -l .)" || { \
		echo "unformatted Go files:"; (cd $(GO_PKG) && gofmt -l .); exit 1; }
	@echo "formatting clean"

# ----------------------------------------------------------------- binaries
# Everything runnable lands in bin/: the Go sandbox helper directly, and the
# Gleam server and terminal client as Erlang shipments behind thin launchers.
# Shipments bundle compiled BEAM files, not the runtime system, so running one
# needs an installed Erlang/OTP. For a server that carries the runtime system
# with it, see `make release`.
#
# Every Go build in the tree goes through scripts/go-build.sh so the flags
# cannot drift between them: the helper `make selftest` probes and the
# helper `make dist` ships are then the same bytes, which is the only way
# the self-test's verdict says anything about the artifact.

.PHONY: binaries
binaries: sandbox tui-shipment ## Build bin/loom-exec and the native bin/loom launcher
	@install -m 0755 $(HELPER) bin/loom-exec
	@echo "built bin/loom-exec and bin/loom"

.PHONY: profile-launcher-test
profile-launcher-test: tui-shipment ## Check --profile argument and credential handling
	@scripts/profile-launcher-test.sh

.PHONY: tui-shipment
tui-shipment: ## Package the native TUI: build/tui-erlang-shipment + bin/loom
	@cd packages/tui && gleam export erlang-shipment
	@mkdir -p bin build
	@rm -f bin/loom-tui
	@rm -rf build/tui-erlang-shipment
	@cp -R packages/tui/build/erlang-shipment build/tui-erlang-shipment
	@mkdir -p build/tui-erlang-shipment/bin build/tui-erlang-shipment/share/diagnostics/ebin
	@cp scripts/profile-launcher.sh build/tui-erlang-shipment/share/diagnostics/profile-launcher.sh
	@cp scripts/platform.sh build/tui-erlang-shipment/share/platform.sh
	@erlc -o build/tui-erlang-shipment/share/diagnostics/ebin scripts/mem_report.erl
	@printf '%s\n' '#!/usr/bin/env bash' \
		'# Generated by `make tui-shipment`. Attach the bundled census to a profile node.' \
		'set -euo pipefail' \
		'here="$$(CDPATH= cd -- "$$(dirname -- "$$0")" && pwd -P)"' \
		'root="$$(dirname "$$here")"' \
		'node="$${1:?usage: loom-profile <node> <cookie-home> [label]}"' \
		'cookie_home="$${2:?usage: loom-profile <node> <cookie-home> [label]}"' \
		'label="$${3:-live}"' \
		'[ -r "$$cookie_home/.erlang.cookie" ] || { echo "loom-profile: cookie file is unreadable" >&2; exit 2; }' \
		'source "$$root/share/diagnostics/profile-launcher.sh"' \
		'operator_home="$${HOME:?loom-profile needs HOME}"' \
		'exec /usr/bin/env "HOME=$$cookie_home" erl -pa "$$root"/*/ebin "$$root/share/diagnostics/ebin" -name "loom_probe_$$$$_$$(loom_profile_random)@127.0.0.1" -env HOME "$$operator_home" -kernel inet_dist_use_interface '\''{127,0,0,1}'\'' -hidden -noshell -run mem_report main "$$node" "$$label" observe' \
		> build/tui-erlang-shipment/bin/loom-profile
	@chmod +x build/tui-erlang-shipment/bin/loom-profile
	@printf '%s\n' '#!/usr/bin/env bash' \
		'set -euo pipefail' \
		'# Generated by `make tui-shipment`. The shipment carries compiled' \
		'# BEAM files but not ERTS, so a compatible Erlang/OTP must be on PATH.' \
		'SCRIPT_DIR="$$(CDPATH= cd -- "$$(dirname -- "$$0")" && pwd -P)"' \
		': "$${LOOM_EXECUTABLE:=$$SCRIPT_DIR/loom}"' \
		'export LOOM_EXECUTABLE' \
		'LOOM_BUILD_VERSION="$(CLIENT_VERSION)"' \
		'LOOM_BUILD_COMMIT="$(BUILD_COMMIT)"' \
		'SHIPMENT="$$(dirname "$$SCRIPT_DIR")"' \
		'LOOM_BUILD_PLATFORM="$$(bash "$$SHIPMENT/share/platform.sh")"' \
		'export LOOM_BUILD_VERSION LOOM_BUILD_COMMIT LOOM_BUILD_PLATFORM' \
		'LOOM_PROFILE_TOOL="$$SHIPMENT/bin/loom-profile"' \
		'source "$$SHIPMENT/share/diagnostics/profile-launcher.sh"' \
		'unset LOOM_DAEMON_PROFILE' \
		'loom_profile_consume client "$$@"' \
		'profile_args=()' \
		'profile_exec=()' \
		'if (( LOOM_PROFILE_ENABLED == 1 )); then profile_args=(-name "$$LOOM_PROFILE_NODE" +Muatags true -env HOME "$$LOOM_PROFILE_ORIGINAL_HOME" -kernel inet_dist_use_interface '\''{127,0,0,1}'\''); profile_exec=(/usr/bin/env "HOME=$$LOOM_PROFILE_COOKIE_HOME" "LOOM_DAEMON_PROFILE=1"); fi' \
		'exec $${profile_exec[@]+"$${profile_exec[@]}"} erl +Bd -pa "$$SHIPMENT"/*/ebin $${profile_args[@]+"$${profile_args[@]}"} -eval '\''tui@@main:run(tui)'\'' -noshell -extra $${LOOM_PROFILE_ARGS[@]+"$${LOOM_PROFILE_ARGS[@]}"}' \
		> build/tui-erlang-shipment/bin/loom
	@chmod +x build/tui-erlang-shipment/bin/loom
	@printf '%s\n' '#!/bin/sh' \
		'LOOM_EXECUTABLE="$$(CDPATH= cd -- "$$(dirname -- "$$0")" && pwd -P)/loom"' \
		'export LOOM_EXECUTABLE' \
		'exec "$$(dirname "$$0")/../build/tui-erlang-shipment/bin/loom" "$$@"' > bin/loom
	@chmod +x bin/loom
	@echo "built build/tui-erlang-shipment and bin/loom"

# The seed is a prerequisite because a server booted without one registers
# no `code_mode` tool and says so only in its log; a drive against such a
# server reads as a model that cannot find code mode, which has misled a
# session more than once. The seed script is the one step allowed the
# network, and it is a no-op once the seed builds offline.
.PHONY: server-shipment
server-shipment: codemode-seed ## Package the server: build/erlang-shipment + bin/loomd (needs erl to run)
	@cd packages/client && gleam export erlang-shipment
	@mkdir -p bin build
	@rm -f bin/loom-server
	@rm -rf build/erlang-shipment
	@cp -R packages/client/build/erlang-shipment build/erlang-shipment
	@printf '%s\n' '#!/bin/sh' \
		'# Generated by `make server-shipment`. Runs the exported erlang' \
		'# shipment; needs an installed Erlang/OTP on PATH (shipments bundle' \
		'# compiled BEAM files, not the runtime system).' \
		'LOOM_BUILD_VERSION="$(SERVER_VERSION)"' \
		'LOOM_BUILD_COMMIT="$(BUILD_COMMIT)"' \
		'LOOM_BUILD_PLATFORM="$(shell scripts/platform.sh)"' \
		'export LOOM_BUILD_VERSION LOOM_BUILD_COMMIT LOOM_BUILD_PLATFORM' \
		'exec "$$(dirname "$$0")/../build/erlang-shipment/entrypoint.sh" run "$$@"' \
		> bin/loomd
	@chmod +x bin/loomd
	@echo "built build/erlang-shipment and bin/loomd"

# ------------------------------------------------------------- distribution
# The downloadable server: an OTP release with `include_erts`, so the
# machine that runs it needs no Erlang. rebar3/relx assembles it over the
# same erlang-shipment `server-shipment` exports, because Gleam has no
# release story of its own and the shipment is the one artifact that
# already has every dependency's ebin and priv in one place.
#
# A release is per-platform and cannot be otherwise: the copied ERTS and
# esqlite's `esqlite3_nif.so` are both native to the build host. `make
# release` refuses a GOOS/GOARCH that is not the host rather than
# producing a tree whose name lies about it. docs/distribution.md is the
# argument in full — mechanism, what it costs, and why the helper ships
# beside the release instead of inside it.
#
# A release also carries code mode: `bin/gleam` and `share/codemode-seed`
# beside the helper, found through `code:root_dir()` rather than PATH.
# That is half the download, so `DIST_CODEMODE=0` builds the lean 29 MB
# artifact for a deploy that will never write a program — and drops the
# seed from the prerequisites with it.
#
# To build: gleam, rebar3, erl, go, strip, and a prepared seed (`make
# codemode-seed`). To run what comes out: nothing.

.PHONY: release
release: ## Build the self-contained server into build/release/loom (needs rebar3 + a seed)
	@scripts/release.sh

.PHONY: release-smoke
release-smoke: ## Boot build/release/loom with no erl on PATH and prove it serves code mode
	@python3 scripts/with_timeout.py 180 -- bash scripts/release.sh --smoke

# The client gets the same treatment as the server: an OTP release with
# the runtime system copied in, so `loom` runs on a machine with no
# Erlang. The shipment (`make tui-shipment`) is not retired by it — a
# package manager that already provides Erlang wants the slim one.
.PHONY: release-client
release-client: ## Build the self-contained client into build/release/loom-client
	@scripts/release-client.sh

.PHONY: update-release-smoke
update-release-smoke: ## Exercise installed update and graceful restart using built bundles
	@python3 scripts/with_timeout.py 300 -- python3 scripts/update_release_smoke.py

.PHONY: release-client-smoke
release-client-smoke: ## Boot build/release/loom-client with no erl on PATH
	@scripts/release-client.sh --smoke

.PHONY: dist
dist: release release-smoke release-client release-client-smoke tui-shipment ## Package the server and both client tarballs
	@scripts/dist.sh

# Everything a person needs to type `loom` in a directory: the seed, the
# self-contained server release, a client, and two launchers under
# $(PREFIX)/bin. PREFIX defaults to $$HOME/.local. INSTALL_CLIENT picks the
# client: `bundled` (default) is the self-contained release, `slim` is the
# shipment that runs on the host's own Erlang, which is what a package
# manager providing Erlang as a dependency wants. scripts/install.sh says
# what lands where and why each launcher is shaped as it is.
INSTALL_CLIENT ?= bundled
CLIENT_ARTIFACT := $(if $(filter slim,$(INSTALL_CLIENT)),tui-shipment,release-client)

# Use the freshly built updater so an older installed client can be upgraded.
# Serialize distribution prerequisites even under `make -j`: smoke tests load
# the release trees that their sibling prerequisites assemble.
UPDATE_ARGS ?=

.PHONY: update
update: ## Build this commit, install it, and gracefully restart the daemon (UPDATE_ARGS=flags)
	@$(MAKE) codemode-seed
	@$(MAKE) -j1 dist
	@build/release/loom-client/bin/loom update --from "$(CURDIR)/dist" --prefix "$(PREFIX)" --client "$(INSTALL_CLIENT)" $(UPDATE_ARGS)

.PHONY: install
install: codemode-seed release $(CLIENT_ARTIFACT) ## Install loom and loomd under PREFIX (INSTALL_CLIENT=bundled|slim)
	@PREFIX="$(PREFIX)" LOOM_CLIENT="$(INSTALL_CLIENT)" scripts/install.sh

# Keep diagnostics opt-in and serialize the seed before release assembly.
.PHONY: install-debug
install-debug: ## Install with BEAM debug info, unstripped ERTS, and OTP profiling tools
	@$(MAKE) codemode-seed
	@$(MAKE) release $(CLIENT_ARTIFACT) DIST_DEBUG=1 DIST_STRIP_ERTS=0
	@PREFIX="$(PREFIX)" LOOM_CLIENT="$(INSTALL_CLIENT)" scripts/install.sh

# ------------------------------------------------------------------- running

WORKSPACE ?= .
STATE_DIR ?= $(CURDIR)/build/dev/state

# Build identity for the two `run-*` targets, exported so a development daemon
# or client reports which build it is the same way an installed one does
# (#392). The version is the package's own, matching what scripts/install.sh
# and scripts/release.sh read; the commit falls back to `unknown` so a tree
# without git metadata, or without git at all, still builds.
SERVER_VERSION := $(shell sed -n 's/^version *= *"\(.*\)"/\1/p' packages/client/gleam.toml | head -1)
CLIENT_VERSION := $(shell sed -n 's/^version *= *"\(.*\)"/\1/p' packages/tui/gleam.toml | head -1)
BUILD_COMMIT := $(shell git rev-parse HEAD 2>/dev/null || echo unknown)

.PHONY: run-server
run-server: binaries ## Run the daemon from source: [STATE_DIR=path] [ARGS=--best-effort]
	@export LOOM_BUILD_VERSION="$(SERVER_VERSION)" LOOM_BUILD_COMMIT="$(BUILD_COMMIT)"; \
		cd packages/client && gleam run -m client -- \
		--state-dir "$(abspath $(STATE_DIR))" \
		--helper "$(abspath bin/loom-exec)" $(ARGS)

.PHONY: run-tui
run-tui: binaries server-shipment ## Open the daemon session picker: [STATE_DIR=path] [WORKSPACE=dir] [SESSION=id]; remote: ADDR=ws://host:port/v2/sessions/id/ws TOKEN_FILE=path
	@export LOOM_BUILD_VERSION="$(CLIENT_VERSION)" LOOM_BUILD_COMMIT="$(BUILD_COMMIT)"; \
	if [ -n "$(ADDR)" ]; then \
		test -n "$(SESSION)" && test -n "$(TOKEN_FILE)" || { \
			echo "remote attachment requires SESSION=id and TOKEN_FILE=path" >&2; exit 1; }; \
		./bin/loom --addr "$(ADDR)" --session "$(SESSION)" --token-file "$(TOKEN_FILE)"; \
	else \
		set -- --state-dir "$(abspath $(STATE_DIR))" --workspace "$(abspath $(WORKSPACE))" \
			--server "$(abspath bin/loomd)"; \
		if [ -n "$(SESSION)" ]; then set -- "$$@" --session "$(SESSION)"; fi; \
		./bin/loom "$$@"; \
	fi

.PHONY: bench-tui
bench-tui: ## Benchmark the TUI frame-rendering hot paths
	@cd packages/tui && gleam dev

# The server's per-step hot paths over a real session store: branch scan
# and decode, projection, the threshold estimate, and the provider request
# encode. Point DB at a copy of a session .db, never at a live daemon's
# file: the session layer takes a writer lease on open.
.PHONY: bench-server
bench-server: ## Benchmark the server's per-step hot paths (DB=<copy of a session .db>)
	@test -n "$(DB)" || { echo "usage: make bench-server DB=<copy of a session .db>"; exit 2; }
	@cd packages/client && gleam dev -- "$(DB)"

.PHONY: dev
dev: ## Build a scratch daemon and open its session picker (interactive)
	@scripts/dev.sh

# -------------------------------------------------------------- the sandbox

.PHONY: sandbox
sandbox: ## Build the loom-exec sandbox helper binary
	@scripts/go-build.sh $(GO_PKG) ./cmd/loom-exec $(HELPER)
	@echo "built $(HELPER)"

.PHONY: sandbox-test
sandbox-test: ## Vet, build, and test the Go sandbox package
	@cd $(GO_PKG) && go vet ./... && go build ./... && \
		python3 ../../scripts/with_timeout.py 1200 -- go test -timeout 10m ./...

.PHONY: selftest
selftest: sandbox ## Probe this kernel's enforcement layers (ENFORCED/SKIPPED per probe)
	@./$(HELPER) --self-test

# ---------------------------------------------------------------- end to end

.PHONY: e2e
e2e: sandbox ## Run the jailed end-to-end acceptance against the real helper
	@bash scripts/test.sh conformance

# These are focused daemon fixtures, not a substitute for shipped-artifact
# acceptance. Each module retains its own watchdog and stops the target on
# failure; LOOM_TEST_TIMEOUT_SECONDS overrides the 180-second per-module budget.
.PHONY: e2e-multiplayer
e2e-multiplayer: sandbox ## Run the multiplayer fixture suite against the real helper
	@set -e; for filter in \
		client@tui_e2e_test: \
		client@tui_multiplayer_test: \
		client@tui_v2_persisted_test: \
		client@tui_approval_effect_test: \
		client@daemon_fault_containment_test:; do \
		LOOM_TEST_TIMEOUT_SECONDS="$${LOOM_TEST_TIMEOUT_SECONDS:-180}" \
			bash scripts/test.sh client --match "$$filter"; \
	done

.PHONY: soak-daemon
soak-daemon: sandbox ## Run the bounded real-daemon lifecycle soak fixture
	@LOOM_TEST_TIMEOUT_SECONDS="$${LOOM_TEST_TIMEOUT_SECONDS:-180}" \
		bash scripts/test.sh client --match client@daemon_soak_test:

.PHONY: e2e-client-bootstrap
e2e-client-bootstrap: binaries server-shipment ## Start, detach, and reuse the real local server through the native TUI bootstrap
	@bash scripts/e2e_client_bootstrap.sh

.PHONY: conformance
conformance: ## Run the shared suites (storage conformance + wiring + e2e)
	@bash scripts/test.sh conformance

.PHONY: codemode-seed
codemode-seed: ## Prepare the offline package cache code-mode builds clone
	@scripts/codemode_seed.sh

.PHONY: e2e-codemode
e2e-codemode: sandbox codemode-seed ## Code-mode end to end: jailed build, real satellite, real cap call
	@bash scripts/test.sh codemode

# ------------------------------------------------------------- the signoff
# The merge gate on a developer's own machines instead of hosted runners:
# every lane is a CI job's exact command, run in parallel on one checkout,
# and the verdict lands as a `signoff/<platform>` commit status that the
# main ruleset requires. scripts/signoff.sh says what runs and why.

.PHONY: signoff
signoff: ## Run this platform's gate in parallel and post signoff/<platform> (SIGNOFF_ARGS=--dry-run)
	@bash scripts/signoff.sh $(SIGNOFF_ARGS)

.PHONY: signoff-remote
signoff-remote: ## Run the gate for HEAD in a fresh container on LOOM_SIGNOFF_HOST and post its signoff (LOOM_SIGNOFF_CONTAINER=0 for the bare checkout)
	@bash scripts/signoff_remote.sh $(SIGNOFF_ARGS)

# ------------------------------------------------------------ the simulator

SOAK_SEEDS ?= 2000
SOAK_FROM  ?= 1
# Seeds per test-runner invocation. The test framework imposes a per-test
# timeout (about a minute), and per-seed cost varies enough that a single
# invocation of more than a few dozen seeds can trip it and report a
# timeout rather than a result. The soak therefore runs in chunks; raise
# this only if you have measured that your seeds are cheap.
SOAK_CHUNK ?= 50

# Replay just one generated case, without running unrelated conformance tests.
SIM_SEED ?= 1
.PHONY: replay-simulation
replay-simulation: ## Replay one session simulation seed (SIM_SEED=n)
	@case '$(SIM_SEED)' in ''|*[!0-9]*) echo 'SIM_SEED must be a non-negative integer' >&2; exit 2;; esac
	@LOOM_SOAK_FROM=$(SIM_SEED) LOOM_SOAK_SEEDS=1 \
		bash scripts/test.sh conformance --match conformance@simulation_test:soak_test

# Every chunk names the soak test, for the same reason `replay-simulation`
# does. `LOOM_SOAK_SEEDS` is read by exactly one test, so an unmatched
# invocation ran the whole conformance package once per chunk — forty times
# a night across the nightly's four shards — and charged whatever any of
# those eighty-odd seed-independent tests did to the seed window the chunk
# was on. A `soak FAILED in seeds 1851..1900` that was really an `e2e_test`
# timeout is the failure mode: the report names a seed range that had
# nothing to do with it, and the same tests already run in `make check`.
.PHONY: soak
soak: ## Long deterministic-simulation run (SOAK_SEEDS=n SOAK_FROM=n SOAK_CHUNK=n)
	@from=$(SOAK_FROM); left=$(SOAK_SEEDS); \
	while [ $$left -gt 0 ]; do \
		n=$$( [ $$left -lt $(SOAK_CHUNK) ] && echo $$left || echo $(SOAK_CHUNK) ); \
		echo "==> seeds $$from..$$(( from + n - 1 ))"; \
		( LOOM_SOAK_SEEDS=$$n LOOM_SOAK_FROM=$$from \
			bash scripts/test.sh conformance \
				--match conformance@simulation_test:soak_test ) || \
			{ echo "soak FAILED in seeds $$from..$$(( from + n - 1 ))"; exit 1; }; \
		from=$$(( from + n )); left=$$(( left - n )); \
	done; \
	echo "soak clean: $(SOAK_SEEDS) seeds from $(SOAK_FROM)"

# The daemon simulation is bounded by wall clock instead of by a seed count.
# A daemon seed opens a real SQLite catalogue on a real directory and starts
# several daemon incarnations, so what it costs depends on the machine's file
# system and on what the schedules drew: a seed count would buy an amount of
# lane time nobody can predict from the number. The budget says how long to
# keep drawing, and the run reports how many seeds fit.
#
# The whole budget is spent in one invocation. The suite is a generator that
# asks eunit for a deadline covering the budget and the corroboration tail,
# so there is no per-test timeout to stay under and no seed range to hand
# from one invocation to the next. The outer watchdog is set above the same
# sum, since a run that has to be killed there reports nothing at all.
SOAK_DAEMON_BUDGET_SECONDS ?= 120
SOAK_DAEMON_FROM           ?= 1

.PHONY: soak-daemon-sim
soak-daemon-sim: ## Wall-clock-budgeted daemon simulation (SOAK_DAEMON_BUDGET_SECONDS=n SOAK_DAEMON_FROM=n)
	@LOOM_DAEMON_SOAK_SECONDS=$(SOAK_DAEMON_BUDGET_SECONDS) \
		LOOM_DAEMON_SOAK_FROM=$(SOAK_DAEMON_FROM) \
		LOOM_TEST_TIMEOUT_SECONDS="$${LOOM_TEST_TIMEOUT_SECONDS:-$$(( $(SOAK_DAEMON_BUDGET_SECONDS) + 600 ))}" \
		bash scripts/test.sh conformance \
		--match conformance@simulation_daemon_soak_test:

# ---------------------------------------------------------------- utilities

.PHONY: deps
deps: ## Download dependencies for every package
	@set -e; for p in $(PACKAGES); do \
		echo "==> $$p"; (cd packages/$$p && gleam deps download); \
	done
	@cd $(GO_PKG) && go mod download

.PHONY: gen-sql
gen-sql: ## Regenerate parrot-generated SQL modules (needs sqlite3; ADR-004)
	@scripts/gen-sql.sh

.PHONY: gen-prelude
gen-prelude: ## Regenerate tools/prelude from packages/cap (needs gleam, python3)
	@scripts/gen-prelude.sh

.PHONY: prelude-check
prelude-check: ## Check tools/prelude against packages/cap (no toolchain needed)
	@scripts/gen-prelude.sh --check
	@scripts/gen-prelude.sh --self-test

.PHONY: docs
docs: ## Build HexDocs-style API documentation for every Gleam package
	@set -e; for p in $(PACKAGES); do \
		echo "==> $$p"; (cd packages/$$p && gleam docs build); \
	done

.PHONY: lint
lint: ## Run Loom's own lint (house rules; R0/R2/R4/R6/R10 gate, see scripts/lint.sh)
	@scripts/lint.sh

.PHONY: lint-%
lint-%: ## Lint one package's src, e.g. make lint-core
	@scripts/lint.sh packages/$*/src

.PHONY: doc-check
doc-check: ## Check the doc graph (coverage, AGENTS.md mirror, staleness, citations)
	@scripts/doc_check.sh

# ---------------------------------------------------------------- the image

DOCKER_IMAGE ?= loom-runtime:dev

.PHONY: docker-image
docker-image: ## Build the runnable loomd image (BuildKit; DOCKER_IMAGE=name:tag)
	@DOCKER_BUILDKIT=1 docker build -t "$(DOCKER_IMAGE)" .

.PHONY: docker-smoke
docker-smoke: ## Build the image, boot it, run a client command and the self-test, then stop it
	@bash scripts/docker_smoke.sh "$(DOCKER_IMAGE)"

.PHONY: clean
clean: ## Remove build artifacts
	@rm -rf packages/*/build $(HELPER) bin build dist
	@echo "cleaned"

.PHONY: loc
loc: ## Report source and test line counts per package
	@for p in $(PACKAGES); do \
		src=$$(find packages/$$p/src -name '*.gleam' 2>/dev/null | xargs cat 2>/dev/null | wc -l); \
		tst=$$(find packages/$$p/test -name '*.gleam' 2>/dev/null | xargs cat 2>/dev/null | wc -l); \
		printf '%-12s src %6s  test %6s\n' "$$p" "$$src" "$$tst"; \
	done
	@go_src=$$(find $(GO_PKG) -name '*.go' | xargs cat | wc -l); \
		printf '%-12s src %6s\n' sandbox "$$go_src"

.PHONY: help
help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_%-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

.PHONY: release-tag
release-tag: ## Preview a release tag; TAG=vX.Y.Z RELEASE_ARGS=--push publishes the tag
	@test -n "$(TAG)" || { echo "usage: make release-tag TAG=vX.Y.Z [RELEASE_ARGS=--push]" >&2; exit 1; }
	python3 scripts/release-tag.py "$(TAG)" $(RELEASE_ARGS)
