# Loom — common developer commands.
#
# Every target is a thin wrapper over the scripts and package tooling, so
# what CI runs and what you run locally are the same commands.

PACKAGES := core storage session machine prompt telemetry runtime provider \
	broker mcp tools cap codemode events client conformance tui lint
GO_PKG   := packages/sandbox
HELPER   := $(GO_PKG)/loom-exec

.DEFAULT_GOAL := help

# ---------------------------------------------------------------- checking

.PHONY: check
check: binaries ## Full gate: current helpers, format, build, tests, and lint
	@scripts/check.sh

.PHONY: check-gleam
check-gleam: binaries ## Full gate for the Gleam packages only
	@scripts/check.sh $(PACKAGES)

.PHONY: check-%
check-%: binaries ## Full gate for one package, e.g. make check-machine
	@scripts/check.sh $*

.PHONY: test
test: ## Run tests only (skips format check), all Gleam packages
	@set -e; for p in $(PACKAGES); do \
		echo "==> $$p"; (cd packages/$$p && gleam test); \
	done

.PHONY: test-%
test-%: ## Run tests for one package, e.g. make test-core
	@cd packages/$* && gleam test

.PHONY: build
build: ## Warning-free build of every Gleam package
	@set -e; for p in $(PACKAGES); do \
		echo "==> $$p"; (cd packages/$$p && gleam build --warnings-as-errors); \
	done

# --------------------------------------------------------------- formatting

# Gleam sources that live outside a package: the code-mode migration
# sample is a documentation artifact and a test fixture at once, so no
# package's `gleam format` reaches it.
LOOSE_GLEAM := $(wildcard docs/examples/*.gleam)

.PHONY: fmt
fmt: ## Format all Gleam and Go sources in place
	@set -e; for p in $(PACKAGES); do \
		(cd packages/$$p && gleam format src test); \
	done
	@test -z "$(LOOSE_GLEAM)" || gleam format $(LOOSE_GLEAM)
	@cd $(GO_PKG) && gofmt -w .
	@echo "formatted"

.PHONY: fmt-check
fmt-check: ## Verify formatting without writing (what CI enforces)
	@set -e; for p in $(PACKAGES); do \
		(cd packages/$$p && gleam format --check src test); \
	done
	@test -z "$(LOOSE_GLEAM)" || gleam format --check $(LOOSE_GLEAM)
	@test -z "$$(cd $(GO_PKG) && gofmt -l .)" || { \
		echo "unformatted Go files:"; (cd $(GO_PKG) && gofmt -l .); exit 1; }
	@echo "formatting clean"

# ----------------------------------------------------------------- binaries
# Everything runnable lands in bin/: the Go sandbox helper directly, and the
# Gleam server and terminal client as Erlang shipments behind thin launchers.
# Shipments bundle compiled BEAM files, not the runtime system, so running one
# needs an installed Erlang/OTP. For a server that carries the runtime system
# with it, see `make release`.
#
# Every Go build in the tree goes through scripts/go-build.sh so the flags
# cannot drift between them: the helper `make selftest` probes and the
# helper `make dist` ships are then the same bytes, which is the only way
# the self-test's verdict says anything about the artifact.

.PHONY: binaries
binaries: sandbox tui-shipment ## Build bin/loom-exec and the native bin/loom launcher
	@install -m 0755 $(HELPER) bin/loom-exec
	@echo "built bin/loom-exec and bin/loom"

.PHONY: tui-shipment
tui-shipment: ## Package the native TUI: build/tui-erlang-shipment + bin/loom
	@cd packages/tui && gleam export erlang-shipment
	@mkdir -p bin build
	@rm -f bin/loom-tui
	@rm -rf build/tui-erlang-shipment
	@cp -R packages/tui/build/erlang-shipment build/tui-erlang-shipment
	@printf '%s\n' '#!/bin/sh' \
		'set -eu' \
		'# Generated by `make tui-shipment`. The shipment carries compiled' \
		'# BEAM files but not ERTS, so a compatible Erlang/OTP must be on PATH.' \
		'SCRIPT_DIR="$$(CDPATH= cd -- "$$(dirname -- "$$0")" && pwd)"' \
		'LOOM_EXECUTABLE="$$SCRIPT_DIR/loom"' \
		'export LOOM_EXECUTABLE' \
		'SHIPMENT="$$(dirname "$$0")/../build/tui-erlang-shipment"' \
		'exec erl +Bd -pa "$$SHIPMENT"/*/ebin -eval '\''tui@@main:run(tui)'\'' -noshell -extra "$$@"' \
		> bin/loom
	@chmod +x bin/loom
	@echo "built build/tui-erlang-shipment and bin/loom"

.PHONY: server-shipment
server-shipment: ## Package the server: build/erlang-shipment + bin/loomd (needs erl to run)
	@cd packages/client && gleam export erlang-shipment
	@mkdir -p bin build
	@rm -f bin/loom-server
	@rm -rf build/erlang-shipment
	@cp -R packages/client/build/erlang-shipment build/erlang-shipment
	@printf '%s\n' '#!/bin/sh' \
		'# Generated by `make server-shipment`. Runs the exported erlang' \
		'# shipment; needs an installed Erlang/OTP on PATH (shipments bundle' \
		'# compiled BEAM files, not the runtime system).' \
		'exec "$$(dirname "$$0")/../build/erlang-shipment/entrypoint.sh" run "$$@"' \
		> bin/loomd
	@chmod +x bin/loomd
	@echo "built build/erlang-shipment and bin/loomd"

# ------------------------------------------------------------- distribution
# The downloadable server: an OTP release with `include_erts`, so the
# machine that runs it needs no Erlang. rebar3/relx assembles it over the
# same erlang-shipment `server-shipment` exports, because Gleam has no
# release story of its own and the shipment is the one artifact that
# already has every dependency's ebin and priv in one place.
#
# A release is per-platform and cannot be otherwise: the copied ERTS and
# esqlite's `esqlite3_nif.so` are both native to the build host. `make
# release` refuses a GOOS/GOARCH that is not the host rather than
# producing a tree whose name lies about it. docs/distribution.md is the
# argument in full — mechanism, what it costs, and why the helper ships
# beside the release instead of inside it.
#
# A release also carries code mode: `bin/gleam` and `share/codemode-seed`
# beside the helper, found through `code:root_dir()` rather than PATH.
# That is half the download, so `DIST_CODEMODE=0` builds the lean 29 MB
# artifact for a deploy that will never write a program — and drops the
# seed from the prerequisites with it.
#
# To build: gleam, rebar3, erl, go, strip, and a prepared seed (`make
# codemode-seed`). To run what comes out: nothing.

.PHONY: release
release: ## Build the self-contained server into build/release/loom (needs rebar3 + a seed)
	@scripts/release.sh

.PHONY: release-smoke
release-smoke: ## Boot build/release/loom with no erl on PATH and prove it serves code mode
	@scripts/release.sh --smoke

.PHONY: dist
dist: release release-smoke tui-shipment ## Package the server and native client tarballs
	@scripts/dist.sh

# ------------------------------------------------------------------- running

WORKSPACE ?= .

.PHONY: run-server
run-server: binaries ## Run the server from source: make run-server SESSION=path [ARGS=--best-effort]
	@test -n "$(SESSION)" || { \
		echo "usage: make run-server SESSION=path/to/session.db [WORKSPACE=dir] [ARGS=...]"; \
		exit 1; }
	@cd packages/client && gleam run -m client/serve -- \
		--session "$(abspath $(SESSION))" \
		--workspace "$(abspath $(WORKSPACE))" \
		--helper "$(abspath bin/loom-exec)" $(ARGS)

.PHONY: run-tui
run-tui: binaries ## Attach the TUI: make run-tui ADDR=ws://host:port/v1/ws SESSION=id [TOKEN_FILE=path]
	@test -n "$(ADDR)" && test -n "$(SESSION)" || { \
		echo "usage: make run-tui ADDR=ws://host:port/v1/ws SESSION=id [TOKEN_FILE=path]"; \
		exit 1; }
	@if [ -n "$(TOKEN_FILE)" ]; then \
		./bin/loom --addr "$(ADDR)" --session "$(SESSION)" \
			--token-file "$(TOKEN_FILE)"; \
	else ./bin/loom --addr "$(ADDR)" --session "$(SESSION)"; fi

.PHONY: dev
dev: ## Build, start a server on a scratch session, attach the TUI (interactive)
	@scripts/dev.sh

# -------------------------------------------------------------- the sandbox

.PHONY: sandbox
sandbox: ## Build the loom-exec sandbox helper binary
	@scripts/go-build.sh $(GO_PKG) ./cmd/loom-exec $(HELPER)
	@echo "built $(HELPER)"

.PHONY: sandbox-test
sandbox-test: ## Vet, build, and test the Go sandbox package
	@cd $(GO_PKG) && go vet ./... && go build ./... && go test ./...

.PHONY: selftest
selftest: sandbox ## Probe this kernel's enforcement layers (ENFORCED/SKIPPED per probe)
	@./$(HELPER) --self-test

# ---------------------------------------------------------------- end to end

.PHONY: e2e
e2e: sandbox ## Run the jailed end-to-end acceptance against the real helper
	@cd packages/conformance && gleam test

.PHONY: e2e-client-bootstrap
e2e-client-bootstrap: binaries server-shipment ## Start, detach, and reuse the real local server through the native TUI bootstrap
	@cd packages/tui && \
		LOOM_BOOTSTRAP_E2E_SERVER="$(abspath bin/loomd)" \
		gleam test -- --match bootstrap_real_server_lifecycle_test

.PHONY: conformance
conformance: ## Run the shared suites (storage conformance + wiring + e2e)
	@cd packages/conformance && gleam test

.PHONY: codemode-seed
codemode-seed: ## Prepare the offline package cache code-mode builds clone
	@scripts/codemode_seed.sh

.PHONY: e2e-codemode
e2e-codemode: sandbox codemode-seed ## Code-mode end to end: jailed build, real satellite, real cap call
	@cd packages/codemode && gleam test

# ------------------------------------------------------------ the simulator

SOAK_SEEDS ?= 2000
SOAK_FROM  ?= 1
# Seeds per test-runner invocation. The test framework imposes a per-test
# timeout (about a minute), and per-seed cost varies enough that a single
# invocation of more than a few dozen seeds can trip it and report a
# timeout rather than a result. The soak therefore runs in chunks; raise
# this only if you have measured that your seeds are cheap.
SOAK_CHUNK ?= 50

.PHONY: soak
soak: ## Long deterministic-simulation run (SOAK_SEEDS=n SOAK_FROM=n SOAK_CHUNK=n)
	@from=$(SOAK_FROM); left=$(SOAK_SEEDS); \
	while [ $$left -gt 0 ]; do \
		n=$$( [ $$left -lt $(SOAK_CHUNK) ] && echo $$left || echo $(SOAK_CHUNK) ); \
		echo "==> seeds $$from..$$(( from + n - 1 ))"; \
		( cd packages/conformance && \
			LOOM_SOAK_SEEDS=$$n LOOM_SOAK_FROM=$$from gleam test ) || \
			{ echo "soak FAILED in seeds $$from..$$(( from + n - 1 ))"; exit 1; }; \
		from=$$(( from + n )); left=$$(( left - n )); \
	done; \
	echo "soak clean: $(SOAK_SEEDS) seeds from $(SOAK_FROM)"

# ---------------------------------------------------------------- utilities

.PHONY: deps
deps: ## Download dependencies for every package
	@set -e; for p in $(PACKAGES); do \
		echo "==> $$p"; (cd packages/$$p && gleam deps download); \
	done
	@cd $(GO_PKG) && go mod download

.PHONY: gen-sql
gen-sql: ## Regenerate parrot-generated SQL modules (needs sqlite3; ADR-004)
	@scripts/gen-sql.sh

.PHONY: gen-prelude
gen-prelude: ## Regenerate tools/prelude from packages/cap (needs gleam, python3)
	@scripts/gen-prelude.sh

.PHONY: prelude-check
prelude-check: ## Check tools/prelude against packages/cap (no toolchain needed)
	@scripts/gen-prelude.sh --check
	@scripts/gen-prelude.sh --self-test

.PHONY: docs
docs: ## Build HexDocs-style API documentation for every Gleam package
	@set -e; for p in $(PACKAGES); do \
		echo "==> $$p"; (cd packages/$$p && gleam docs build); \
	done

.PHONY: lint
lint: ## Run Loom's own lint (house rules; R0/R2/R4/R6/R10 gate, see scripts/lint.sh)
	@scripts/lint.sh

.PHONY: lint-%
lint-%: ## Lint one package's src, e.g. make lint-core
	@scripts/lint.sh packages/$*/src

.PHONY: doc-check
doc-check: ## Check the doc graph (coverage, AGENTS.md mirror, staleness, citations)
	@scripts/doc_check.sh

.PHONY: clean
clean: ## Remove build artifacts
	@rm -rf packages/*/build $(HELPER) bin build dist
	@echo "cleaned"

.PHONY: loc
loc: ## Report source and test line counts per package
	@for p in $(PACKAGES); do \
		src=$$(find packages/$$p/src -name '*.gleam' 2>/dev/null | xargs cat 2>/dev/null | wc -l); \
		tst=$$(find packages/$$p/test -name '*.gleam' 2>/dev/null | xargs cat 2>/dev/null | wc -l); \
		printf '%-12s src %6s  test %6s\n' "$$p" "$$src" "$$tst"; \
	done
	@go_src=$$(find $(GO_PKG) -name '*.go' | xargs cat | wc -l); \
		printf '%-12s src %6s\n' sandbox "$$go_src"

.PHONY: help
help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_%-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'
