//// Code generated by `make gen-prelude`. DO NOT EDIT.
////
//// The capability prelude's public surface, one rendered block per
//// module, as the `code_mode` tool description shows it to a model.
////
//// A model writing a code-mode program authors blind: it submits source
//// and finds out what the prelude looks like from the compiler, as a
//// `CompileFailed` round trip carrying a whole hermetic build. The
//// module namespace was the discovery index and the compiler the schema
//// oracle, and the oracle was reachable only by being wrong first. This
//// is that oracle, moved in front of the writing (issue #36).
////
//// Rendered by `scripts/gen-prelude.py` from `gleam export
//// package-interface` over `packages/cap` — the compiler's own account
//// of what it will accept, so the description cannot describe a prelude
//// the build would reject. `scripts/gen-prelude.sh --check` gates the
//// two ways this file can go stale and `make check` runs it.
////
//// Nothing here is filtered. `tools/codemode` selects from `surfaces`
//// through each seam's own `allowed_imports`, which is why `cap/runtime`
//// — on neither seam — is present in this list and must never reach a
//// description.
////
//// Generated from these inputs; `--check` recomputes each digest and
//// names the file that moved:
////
////   de5a54182163d7e4cae0147ee33d2e656bce67cb88a351bd2569342769b3c644  packages/cap/src/cap/actor.gleam
////   b273673129ed12f3ec7055493b1dddfe9480a842319084725bb3d69c7a8508a7  packages/cap/src/cap/fs.gleam
////   13169b82fc24ff5aa14320f25b35c1ff500faf769fa0283cc78adc78d4b634fd  packages/cap/src/cap/git.gleam
////   37332eb8a0ad5118fdf4391729121e71ea153714d53fed8592813308e240b010  packages/cap/src/cap/kv.gleam
////   967a79fcb93b977deaa5f159f7b2263aa7f1a0b96626ecb0d4bbc74aa66149b5  packages/cap/src/cap/lsp.gleam
////   ad6d88ed6bec1e7bbbef9f96431b1a217db683a7c1564cb3eb6db9648febfa05  packages/cap/src/cap/mcp.gleam
////   5d130bfe00a9ea5275c03dce003e6238d497e389d261fb7d6a0e78f83dbde2b3  packages/cap/src/cap/net.gleam
////   68ea7061715254f5dbbcf0242552d89a788b72d896513223e1055704a99d15ef  packages/cap/src/cap/proc.gleam
////   42cd31d198f57cb9314d5e8cebdc77a2acafc80eb7eb57d7858483894eeee432  packages/cap/src/cap/report.gleam
////   e598c08fecc9068f608dd85f7ed334435fa47a1e68ab6cce1ac98ed92eecab68  packages/cap/src/cap/runtime.gleam
////   97797941122361e8deafe0ed9f59636c83acbe68e747a27425257d8ededffcbc  packages/cap/src/cap/schedule.gleam
////   aa37ad78ac1cf27f2be26a8f29630c5e4f41f37c6c4a568989a523ed304d5679  packages/cap/src/cap/strand.gleam
////   3196badca88c32f90b568ca3e596b048f543ddb82cc31f591563bf4db938eb15  packages/cap/src/cap/task.gleam
////   c18b0e9fa7fe45a958d4281cd5760a38bdf673ea8eaf51b1e203ccb4bc75b3c7  scripts/gen-prelude.py
////
//// Body digest (every line after the marker): dedd03589bf1905ab90fae2913c6c68228cc1aba8a1b65d59640b39c35f4fede

// --- generated body: the digests above cover every line below this one ---
/// Every module of the capability prelude, in the order the
/// compiler reports them, paired with its public surface rendered
/// for a model to read.
///
/// Unfiltered on purpose: `tools/codemode` selects from this list
/// through the seam's own `allowed_imports`, so the one place that
/// decides what a model is shown is the one place that already
/// knows what vetting will accept. `cap/runtime` is in here and is
/// on neither seam's allowlist; it must never reach a description.
pub const surfaces: List(#(String, String)) = [
  #(
    "cap/actor",
    "### cap/actor
`cap/actor` — typed, program-scoped actors: a deliberately constrained
`gen_server` for the cases that earn ongoing state and asynchronous input
(watching a build's output and reacting to the first error, a stepping
coordinator, a work-stealing queue where items generate items).

/// Why an actor operation failed.
pub type ActorError {
  /// The actor failed to start.
  StartFailed(message: String)
  /// The mailbox stayed full past the timeout; the message was not
  /// admitted.
  MailboxTimeout
  /// The actor did not answer a `call`/`get` within the timeout.
  NoReply
}
/// An unforgeable handle to a spawned actor. Both type parameters are
/// load-bearing: `msg` types `send`/`call`, `state` types `get`.
pub type Address(a, b)
/// What a message handler decides after handling a message.
pub type Next(a) {
  /// Keep running with this (possibly updated) state.
  Continue(state: a)
  /// Stop the actor.
  Stop
}
/// An opaque, single-use reply channel handed to a handler during `call`.
/// The handler answers it with `reply`; the program never sees a raw
/// `Subject`.
pub type Reply(a)
/// The default mailbox bound `spawn` uses.
pub const default_mailbox_limit: Int
/// Sends a message that expects a reply and waits for it. The `build`
/// function receives a `Reply` handle to embed in the message; the
/// handler answers it with `reply`.
pub fn call(Address(a, b), fn(Reply(c)) -> b, timeout: Int) -> Result(c, ActorError)
/// Continue with a (possibly updated) state — the usual handler return.
pub fn continue(a) -> Next(a)
/// Reads the actor's current state. Ordered after any messages already
/// admitted from this process.
pub fn get(Address(a, b), timeout: Int) -> Result(a, ActorError)
/// Answers a `call` from inside a handler.
pub fn reply(Reply(a), a) -> Nil
/// Sends a message. Blocks only if the mailbox is full, until a slot
/// frees or the admission timeout lapses (in which case the message is
/// dropped — the actor is stalled or dead).
pub fn send(Address(a, b), b) -> Nil
/// Stops the actor. Fire-and-forget.
pub fn shutdown(Address(a, b)) -> Nil
/// Spawns an actor with a default mailbox bound.
///
/// The handler is `fn(state, message) -> Next(state)`: return
/// `continue(new_state)` to keep running or `stop()` to finish.
pub fn spawn(a, fn(a, b) -> Next(a)) -> Result(Address(a, b), ActorError)
/// Spawns an actor with an explicit mailbox bound (the maximum number of
/// admitted-but-unhandled messages before senders park).
pub fn spawn_bounded(a, Int, fn(a, b) -> Next(a)) -> Result(Address(a, b), ActorError)
/// Stop the actor after this message.
pub fn stop() -> Next(a)
",
  ),
  #(
    "cap/fs",
    "### cap/fs
`cap/fs` — workspace filesystem access, as typed calls over the capability
channel.

/// One directory entry from `list`.
pub type DirEntry {
  DirEntry(name: String, is_directory: Bool)
}
/// Why a filesystem call failed. Descriptive variants for the causes a
/// program branches on; `FsFailed` carries any other broker code
/// verbatim; `FsUnavailable` is a transport failure.
pub type FsError {
  /// No such path.
  NotFound(path: String)
  /// The policy does not grant this path (read or write).
  PermissionDenied(path: String)
  /// A `read` target is a directory, or a `write` target's parent is a
  /// file — an operation/kind mismatch.
  WrongKind(path: String, message: String)
  /// An `edit` referenced content that no longer matches; replan.
  StaleContent(path: String, message: String)
  /// A structurally invalid argument (empty path, bad edit).
  InvalidArgument(message: String)
  /// Any other in-band broker refusal, code preserved.
  FsFailed(code: String, message: String)
  /// The capability channel could not carry the call.
  FsUnavailable(reason: String)
}
/// One find/replace edit for `edit`. `find` is matched as an exact
/// substring and must match **exactly once**: zero matches refuses the
/// whole edit as `StaleContent` — the file no longer contains your text —
/// and more than one refuses it as `InvalidArgument`, because a
/// replacement carries no position to say which occurrence was meant;
/// include enough surrounding text to be unique. There are no anchors and
/// no digest on this wire: staleness here means the find text itself, not
/// a pin.
pub type Replacement {
  Replacement(find: String, replace_with: String)
}
/// Applies find/replace edits to a file, all-or-nothing: replacements
/// apply in order, each against the text the previous one produced, and
/// any refusal — a `find` that misses (`StaleContent`), one that matches
/// more than once, an empty one — leaves the file untouched. The read-
/// apply-write happens inside one harness-side call, a tighter window
/// than composing `read` and `write` across two calls; a concurrent
/// writer of the same file within the same execution can still
/// interleave, so a program racing itself should serialize its own edits.
///
/// Capability: `fs.edit`.
pub fn edit(String, List(Replacement)) -> Result(Nil, FsError)
/// Lists a directory's entries.
///
/// Capability: `fs.list`.
pub fn list(String) -> Result(List(DirEntry), FsError)
/// Reads a file's contents as text.
///
/// Capability: `fs.read`.
pub fn read(String) -> Result(String, FsError)
/// Writes `contents` to `path`, creating or replacing the whole file.
///
/// Capability: `fs.write`.
pub fn write(String, String) -> Result(Nil, FsError)
",
  ),
  #(
    "cap/git",
    "### cap/git
`cap/git` — common git operations as typed calls.

/// One commit from `git log`.
pub type Commit {
  Commit(sha: String, subject: String)
}
/// Why a git operation failed.
pub type GitError {
  /// The git process ran but exited non-zero.
  CommandFailed(exit_code: Int, stderr: String)
  /// The underlying `cap/proc` call failed (denial, spawn, channel).
  ProcessError(error: proc.ProcError)
  /// Git's output could not be parsed into the expected shape.
  ParseError(message: String)
}
/// One line of `git status --porcelain`: the two-character status code
/// and the path it refers to.
pub type StatusEntry {
  StatusEntry(code: String, path: String)
}
/// Stages the given paths (`git add`).
pub fn add(List(String)) -> Result(Nil, GitError)
/// Commits the staged changes with `message` and returns the new commit
/// sha.
pub fn commit(String) -> Result(String, GitError)
/// The current branch name (`git rev-parse --abbrev-ref HEAD`).
pub fn current_branch() -> Result(String, GitError)
/// The unified diff of the working tree (optionally staged).
pub fn diff(staged: Bool) -> Result(String, GitError)
/// The most recent commits, newest first, at most `limit`.
pub fn log(limit: Int) -> Result(List(Commit), GitError)
/// The working-tree status as porcelain entries.
pub fn status() -> Result(List(StatusEntry), GitError)
",
  ),
  #(
    "cap/kv",
    "### cap/kv
`cap/kv` — the ephemeral scratch store: a session-scoped key/value space a
program can stash bytes in and read back, including across the calls of a
kept-alive satellite cell.

/// Why a scratch-store call failed at the infrastructure level. A missing
/// key is *not* an error — it is `Ok(None)` from `get`.
pub type KvError {
  /// The broker refused the call in-band.
  KvDenied(code: String, message: String)
  /// The capability channel could not carry the call.
  KvUnavailable(reason: String)
}
/// Deletes a key. Deleting an absent key succeeds.
///
/// Capability: `kv.delete`.
pub fn delete(String) -> Result(Nil, KvError)
/// Reads a key. `Ok(None)` when the key is absent or was evicted — the
/// case every caller must handle.
///
/// Capability: `kv.get`.
pub fn get(String) -> Result(option.Option(BitArray), KvError)
/// Stores bytes under a key, overwriting any prior value.
///
/// Capability: `kv.set`.
pub fn set(String, BitArray) -> Result(Nil, KvError)
",
  ),
  #(
    "cap/lsp",
    "### cap/lsp
`cap/lsp` — semantic queries through the project's language server:
references, go-to-definition, rename, and diagnostics.

/// One diagnostic reported by the language server.
pub type Diagnostic {
  Diagnostic(location: Location, severity: Severity, message: String)
}
/// A position in a file: zero-based `line` and `character`, matching the
/// LSP convention.
pub type Location {
  Location(path: String, line: Int, character: Int)
}
/// Why an LSP query failed.
pub type LspError {
  /// No language server is available for the file's language.
  NoServer(message: String)
  /// The broker refused the query in-band.
  LspDenied(code: String, message: String)
  /// The capability channel could not carry the call.
  LspUnavailable(reason: String)
}
/// A diagnostic's severity.
pub type Severity {
  SeverityError
  SeverityWarning
  SeverityInformation
  SeverityHint
}
/// A text edit a rename would apply.
pub type TextEdit {
  TextEdit(path: String, line: Int, character: Int, new_text: String)
}
/// The definition site(s) of the symbol at `location`.
///
/// Capability: `lsp.definition`.
pub fn definition(Location) -> Result(List(Location), LspError)
/// Diagnostics for a file.
///
/// Capability: `lsp.diagnostics`.
pub fn diagnostics(String) -> Result(List(Diagnostic), LspError)
/// All references to the symbol at `location`.
///
/// Capability: `lsp.references`.
pub fn references(Location) -> Result(List(Location), LspError)
/// The edits a rename of the symbol at `location` to `new_name` would
/// apply. The caller applies them (e.g. via `cap/fs`) — the query itself
/// changes nothing.
///
/// Capability: `lsp.rename`.
pub fn rename(Location, String) -> Result(List(TextEdit), LspError)
",
  ),
  #(
    "cap/mcp",
    "### cap/mcp
`cap/mcp` — the shared vocabulary for the generated `cap/mcp/<server>`
modules: what an MCP tool call returns, and the ways it can fail.

/// One block of a tool result's content. MCP servers answer with a list
/// of typed blocks; text is the kind a program reads, and every other
/// kind is carried by name only in v1 (`Other`), so a result holding an
/// image or a resource still decodes rather than failing the call.
pub type Content {
  /// A text block: `{type: \"text\", text}` on the wire.
  Text(text: String)
  /// Any other block kind, carried as its `type` string verbatim.
  Other(kind: String)
}
/// Why an MCP call failed. Descriptive variants for the causes a program
/// branches on; `McpDenied` carries any other broker code verbatim;
/// `ServerUnavailable` is a transport or reachability failure.
pub type McpError {
  /// The server ran the tool and the tool reported failure (`is_error:
  /// true`). `message` is the joined text content; the full blocks ride
  /// along for a caller that wants more than prose.
  ToolFailed(message: String, content: List(Content))
  /// The capability channel could not carry the call, or the harness
  /// router refused it as `mcp_unavailable` — the server is not running
  /// or its client has gone. (A server this host never configured is a
  /// different refusal: `unsupported_cap`, under `McpDenied`.)
  ServerUnavailable(reason: String)
  /// Any other in-band broker or router refusal, code preserved verbatim
  /// (`unsupported_cap`, `mcp_timeout`, a ceiling, …).
  McpDenied(code: String, message: String)
  /// The `cap_result` did not match the pinned result shape.
  ResultMalformed(reason: String)
}
/// What a successful MCP tool call returns: the content blocks, plus the
/// tool's optional structured output (`structuredContent` in MCP terms)
/// when the server sent one.
pub type ToolResult {
  ToolResult(content: List(Content), structured: option.Option(report.Value))
}
/// A result's text content: every `Text` block, joined with newlines —
/// the common read for a tool whose answer is prose.
pub fn text(ToolResult) -> String
",
  ),
  #(
    "cap/net",
    "### cap/net
`cap/net` — outbound network access, **deny-by-default**.

/// Why a network call did not return a response. `NetDenied` is the
/// default outcome: no policy grants the host.
pub type NetError {
  /// Network is off, or the host is not in the approved allowlist.
  NetDenied(message: String)
  /// The request was allowed but failed (DNS, connection, timeout).
  NetFailed(code: String, message: String)
  /// The capability channel could not carry the call.
  NetUnavailable(reason: String)
}
/// An HTTP request to make through the egress proxy.
pub type Request {
  Request(method: String, url: String, headers: List(#(String, String)), body: BitArray)
}
/// A response from an approved request.
pub type Response {
  Response(status: Int, headers: List(#(String, String)), body: BitArray)
}
/// Fetches a URL with a GET request.
///
/// Capability: `net.request`. Denied by default; see the module docs.
pub fn fetch(String) -> Result(Response, NetError)
/// Makes an arbitrary HTTP request.
///
/// Capability: `net.request`. Denied by default; see the module docs.
pub fn request(Request) -> Result(Response, NetError)
",
  ),
  #(
    "cap/proc",
    "### cap/proc
`cap/proc` — run a command in a jailed executor.

/// A command to run. Opaque: built through `command` and the setters so
/// its invariants (non-empty argv) hold by construction.
pub type Command
/// The result of a completed run. `exit_code` is the child's status;
/// `truncated` flags mark output cut at the policy's byte cap;
/// `timed_out` is set when the wall deadline killed the child.
pub type Output {
  Output(exit_code: Int, stdout: String, stderr: String, stdout_truncated: Bool, stderr_truncated: Bool, timed_out: Bool)
}
/// Why a run could not produce an `Output`.
pub type ProcError {
  /// The broker refused to run the command in-band (e.g. policy).
  ProcDenied(code: String, message: String)
  /// The executor could not spawn the command at all.
  SpawnFailed(message: String)
  /// The capability channel could not carry the call.
  ProcUnavailable(reason: String)
}
/// Begins a command from its argv. The first element is the executable.
pub fn command(List(String)) -> Command
/// Sets the working directory for the command.
pub fn in_dir(Command, String) -> Command
/// Runs the command and returns its output.
///
/// Capability: `proc.run`.
pub fn run(Command) -> Result(Output, ProcError)
/// Adds one environment variable. The executor still drops anything the
/// policy's `env_allow` does not permit.
pub fn with_env(Command, String, String) -> Command
/// Supplies stdin for the command.
pub fn with_stdin(Command, String) -> Command
/// Sets a per-command timeout in milliseconds. The pooled wall deadline
/// still bounds the whole execution.
pub fn with_timeout(Command, Int) -> Command
",
  ),
  #(
    "cap/report",
    "### cap/report
`cap/report` — the structured result a program's `main` returns, plus
artifact emission.

/// A structured value: what an `Outcome` carries, what a blackboard note
/// holds, and what a child's terminal result comes back as.
///
/// A re-export rather than a type of its own, so a value read off one
/// capability can be handed straight to another without a conversion that
/// could lose a case. The alias is what makes the type *nameable* by a
/// program: `report.Value` resolves without an import the allowlist would
/// refuse (see the module doc).
pub type Value
/// A durable reference to an emitted artifact, returned by `emit`.
pub type ArtifactRef {
  ArtifactRef(id: String)
}
/// The result of a program. `Completed` carries a structured value;
/// `Errored` carries a human-readable message and structured details, so
/// a failed program still returns data the model can act on rather than
/// crashing the satellite.
pub type Outcome {
  /// The program finished with this value.
  Completed(value: Value)
  /// The program failed in a controlled way.
  Errored(message: String, details: Value)
}
/// Why an artifact could not be emitted.
pub type ReportError {
  /// The broker refused the emission in-band.
  EmitDenied(code: String, message: String)
  /// The capability channel could not carry the call.
  EmitUnavailable(reason: String)
}
/// A value's boolean, or `Error(Nil)` when it is not one.
pub fn as_bool(Value) -> Result(Bool, Nil)
/// A value's floating-point number, or `Error(Nil)` when it is not one.
/// An int is *not* accepted, the mirror of `as_int`'s refusal of a float:
/// the two tags are distinct on the wire, and a reader that widened one
/// into the other would leave a program no way to ask which arrived.
pub fn as_float(Value) -> Result(Float, Nil)
/// A value's whole number, or `Error(Nil)` when it is not one. A float is
/// *not* accepted: rounding silently is how a count becomes wrong.
pub fn as_int(Value) -> Result(Int, Nil)
/// A value's items, or `Error(Nil)` when it is not a list.
pub fn as_list(Value) -> Result(List(Value), Nil)
/// A value's text, or `Error(Nil)` when it is not text.
pub fn as_string(Value) -> Result(String, Nil)
/// A boolean value.
pub fn bool(Bool) -> Value
/// Emits an artifact and returns a durable reference to it.
///
/// Capability: `report.emit`. `content_type` is a MIME-ish label the
/// broker stores alongside the bytes.
pub fn emit(name: String, content_type: String, bytes: BitArray) -> Result(ArtifactRef, ReportError)
/// An `Errored` outcome from a message alone, with nil details.
pub fn failure(String) -> Outcome
/// One field of an object value, or `Error(Nil)` when the value is not an
/// object or has no such field.
pub fn field(Value, String) -> Result(Value, Nil)
/// A floating-point value.
pub fn float(Float) -> Value
/// A whole-number value.
pub fn int(Int) -> Value
/// A list value.
pub fn list(List(Value)) -> Value
/// The absent value.
pub fn null() -> Value
/// An object value: named fields, in the order given.
pub fn object(List(#(String, Value))) -> Value
/// A text value.
pub fn string(String) -> Value
/// A `Completed` outcome carrying a plain-text summary.
pub fn text(String) -> Outcome
/// Encodes an outcome for the boot module to marshal back to the broker.
/// `Completed` is `{ok: true, value}`; `Errored` is `{ok: false, message,
/// details}`.
pub fn to_msgpack(Outcome) -> Value
/// A `Completed` outcome carrying a structured value.
pub fn value(Value) -> Outcome
",
  ),
  #(
    "cap/runtime",
    "### cap/runtime
`cap/runtime` — the trusted boot runtime that runs *inside* a jailed
satellite node (design/architecture/code-mode.md, \"Layer two: the
satellite node\").

/// What one invocation produced. Mirrors the `hook_result` body.
pub type Answer {
  /// The invocation produced this value, which becomes `{ok: true,
  /// value}`.
  Answered(value: report.Value)
  /// The invocation produced no value, under this in-band code, which
  /// becomes `{ok: false, error: {code, msg}}`. The codes this module
  /// mints itself are `bad_kind`, `busy` and `crashed`; everything else
  /// is the serving function's own vocabulary.
  Refused(code: String, message: String)
}
/// How long an invocation's deadline is, and what it is for. Handed to
/// the serving function so an extension can decide to refuse rather than
/// run past its own bound.
pub type Asked {
  Asked(invocation: Invocation, args: report.Value, deadline_ms: Int)
}
/// A setup failure the runtime cannot recover from. Program failures are
/// never a `BootError` — they become an `Errored` outcome instead.
pub type BootError {
  /// The capability channel actor failed to start.
  ChannelStartFailed(reason: String)
  /// The socket path is unset, or the socket could not be connected.
  TransportUnavailable(reason: String)
  /// The token-file path is unset, or the file could not be read.
  TokenUnavailable(reason: String)
  /// A prior execution's capability channel still occupies the VM-global
  /// slot. Only reachable in the kept-alive satellite mode, and only when
  /// the executor has not reaped the prior execution first.
  ChannelSlotOccupied(reason: String)
}
/// Which kind of thing the harness is asking for.
///
/// The wire carries `\"tool\"` or `\"event\"` as a string (Part 1.4); this is
/// that string turned into a closed set at the edge, so nothing past this
/// module branches on text. A `kind` that is neither is refused rather
/// than guessed at.
pub type Invocation {
  /// A model-made tool call. `name` is the manifest tool's name.
  Tool(name: String)
  /// A hook event on the harness's timeline. `name` is the event's.
  Event(name: String)
}
/// The satellite's link to the host, injected so the runtime is testable
/// without a socket. `send` writes a framed `cap_call`/`cancel` to the
/// channel; `recv` blocks for the next inbound bytes (`Error(Nil)` at end
/// of stream); `outcome_sink` receives the single framed `outcome`.
pub type Transport {
  Transport(send: fn(BitArray) -> Nil, recv: fn() -> Result(BitArray, Nil), outcome_sink: fn(BitArray) -> Nil)
}
/// The kind stamped on the terminal outcome frame.
pub const outcome_kind: String
/// The environment variable naming the AF_UNIX socket path.
pub const sock_env: String
/// The environment variable naming the private cap-token file.
pub const token_env: String
/// Boots the satellite over an injected transport and runs `program`.
///
/// The sequence is: start the channel holding `token`; claim the one door
/// every `cap/*` call resolves, refusing if a prior execution's channel
/// is still installed; start the inbound reader; run `program` in a
/// monitored child (so a crash becomes an outcome, not a dead satellite);
/// marshal and frame the outcome and write it to the sink; then tear the
/// channel and reader down and release the door. Returns `Ok(Nil)` once
/// the outcome has been written, or a `BootError` if the channel would
/// not start or the door was still held.
pub fn boot(BitArray, Transport, fn() -> report.Outcome) -> Result(Nil, BootError)
/// Builds the production transport over the AF_UNIX socket named by
/// `LOOM_CAP_SOCK`. `outcome_sink` shares the socket, so the terminal
/// `outcome` frame travels on the cap channel.
pub fn production_transport() -> Result(Transport, BootError)
/// Reads the raw cap token from the file named by `LOOM_CAP_TOKEN_FILE`.
pub fn read_token() -> Result(BitArray, BootError)
/// The production convenience the generated entry calls: read the socket
/// path and token from the environment, build the real transport, and
/// boot. On any `BootError` it returns `Nil` — the node exits and the
/// host treats the missing outcome as a failure.
pub fn run(fn() -> report.Outcome) -> Nil
/// The production entry for a persistent satellite: read the environment,
/// connect the socket, boot the channel, and serve invocations until the
/// harness cancels or the channel closes.
///
/// The mirror of `run` for the other shape. On a `BootError` it returns
/// `Nil` without serving anything; the node exits and the host observes
/// the socket closing, exactly as it does for a boot that failed.
pub fn serve(fn(Asked) -> Answer) -> Nil
/// Serves invocations over an injected transport, so the whole loop is
/// exercisable in-process with no socket — the same seam `boot` takes and
/// for the same reason.
///
/// `token` is what the node read from `LOOM_CAP_TOKEN_FILE`. For a
/// serving node it is deliberately *not* a working token: the harness
/// mints one per invocation and hands it over on the `hook_call`, and
/// this one only satisfies the boot sequence. It is installed anyway
/// rather than replaced with empty bytes, because the channel's shape
/// should not differ between the two boot modes.
///
/// Returns once the channel closes or the harness cancels, having stopped
/// the reader, the channel actor and its claim on the VM-global slot.
pub fn serve_over(BitArray, Transport, fn(Asked) -> Answer) -> Result(Nil, BootError)
",
  ),
  #(
    "cap/schedule",
    "### cap/schedule
`cap/schedule` — heartbeats a program can set for the strand it is running
on: text injected back into that strand's own context later, on a timer,
whether or not anyone is watching.

/// Whether a recurring schedule takes the host's default expiry or a
/// narrower one this program states.
///
/// Two variants rather than a pair of `Option`s, because \"say nothing and
/// get the host's ceiling\" and \"state both bounds\" are the only two
/// things a caller can usefully mean, and a record of two `Option`s would
/// offer four. Both bounds are always active whichever variant is used —
/// the host applies its default in place of anything this does not state
/// — and whichever is reached first ends the schedule.
///
/// `Bounds` can only ever *narrow*. The host holds both numbers to the
/// same ceilings it holds its own configuration to, so a value above one
/// is denied with `invalid_schedule` rather than granted.
pub type Bounds {
  /// The host's defaults: its ceiling on both bounds. What `every`,
  /// `cron`, `at` and `after` pass.
  DefaultBounds
  /// The bounds this program wants, each at or under the host's ceiling.
  Bounds(max_fires: Int, expires_after_s: Int)
}
/// What a `create` actually produced.
pub type Created {
  Created(name: String, target: String, when: String, wake: Wake)
}
/// One schedule this strand owns.
pub type Schedule {
  Schedule(name: String, target: String, when: String, wake: Wake, fired: Int, body: String)
}
/// Why a scheduling call failed.
pub type ScheduleError {
  /// The broker refused the call in band. `code` distinguishes the
  /// reasons worth branching on: `invalid_schedule` (a bound was missed),
  /// `schedule_limit_reached`, `schedule_name_taken`,
  /// `schedule_not_found`, `schedules_unavailable`.
  ScheduleDenied(code: String, message: String)
  /// The capability channel could not carry the call.
  ScheduleUnavailable(reason: String)
}
/// What a schedule is allowed to do to this strand when it is idle at the
/// moment the schedule fires.
///
/// A program asks for one of these and reads back what it was actually
/// granted, which is not always the same — see the module doc on who owns
/// that decision. The capability wire carries a boolean either way; this
/// type is what a program writes and reads on this side of it.
pub type Wake {
  /// The schedule may start a fresh run when the strand is idle.
  WakesIdle
  /// The schedule steers a run already open, and holds when the strand is
  /// idle. What a host that forbids waking grants instead.
  SteersOnly
}
/// Schedules `body` to fire on this strand once, `seconds` from now.
///
/// This is the relative one-shot, and it exists because **nothing tells
/// this program the current time**: the strand's prompt carries no clock
/// and no date, so an absolute instant for `at` cannot be computed here
/// and a guessed one is either refused or fired at the wrong moment. The
/// host resolves this against the session's own clock.
///
/// `seconds` is between 1 and 604800 (seven days); outside that it is
/// denied with `invalid_schedule`, and the refusal says why the upper
/// bound is where it is — a schedule only fires while this session's
/// server is running.
///
/// Capability: `schedule.create`.
pub fn after(String, Int, Wake, String) -> Result(Created, ScheduleError)
/// `after`, onto a strand this one spawned rather than onto itself. The
/// target rule and the ownership rule are `every_on`'s exactly.
///
/// Capability: `schedule.create`.
pub fn after_on(String, String, Int, Wake, String) -> Result(Created, ScheduleError)
/// Schedules `body` to fire on this strand once, at `instant` — an
/// RFC3339 UTC timestamp, for example `\"2026-09-01T09:00:00Z\"`.
///
/// An instant already past fires promptly, once, annotated as late. It is
/// never replayed for every occurrence that was missed.
///
/// Capability: `schedule.create`.
pub fn at(String, String, Wake, String) -> Result(Created, ScheduleError)
/// `at`, onto a strand this one spawned rather than onto itself. The
/// target rule and the ownership rule are `every_on`'s exactly.
///
/// Capability: `schedule.create`.
pub fn at_on(String, String, String, Wake, String) -> Result(Created, ScheduleError)
/// Cancels one schedule this strand set on itself, by name. It will not
/// fire again, and its record of past fires goes with it, so the name is
/// free to use again.
///
/// A name this strand does not own is denied with `schedule_not_found`
/// rather than silently succeeding, so a program cannot believe it has
/// tidied up when it has not — and a schedule that fires onto another
/// strand is not found by this call at all: it wants `cancel_on`.
///
/// Capability: `schedule.cancel`.
pub fn cancel(String) -> Result(Nil, ScheduleError)
/// Cancels one schedule this strand set onto another strand — the
/// counterpart to `every_on` and `at_on`, addressed by the same target.
///
/// A schedule is named by the pair `{target, name}`, so this is not a
/// convenience over `cancel`: the same name may be in use on this strand
/// and on a subagent's, and `cancel` means this strand's own. `list`
/// shows which target each schedule fires onto.
///
/// Capability: `schedule.cancel`.
pub fn cancel_on(String, String) -> Result(Nil, ScheduleError)
/// Schedules `body` to fire on this strand on a five-field cron
/// expression — `\"0 9 * * 1-5\"` for 09:00 on weekdays.
///
/// **All times are UTC**, and both day fields are ORed when both are
/// restricted; the module doc has the whole of the grammar and what it
/// deliberately does not accept. An expression the host cannot parse is
/// denied with `invalid_schedule`, and the refusal names the field and
/// the item that caused it.
///
/// Reach for this rather than `every` whenever the *time of day* matters:
/// an interval is a grid aligned to the epoch, so `every(…, 86_400, …)`
/// fires at midnight UTC and there is no argument that moves it.
///
/// A cron schedule's first fire is its first match **after the host
/// loaded it**. A match earlier the same day, before this program ran,
/// was never asked for and does not fire.
///
/// Capability: `schedule.create`.
pub fn cron(String, String, Wake, String) -> Result(Created, ScheduleError)
/// `cron`, with the expression's fields read against a clock a fixed
/// offset from UTC — `\"+02:00\"`, `\"-05:30\"` — rather than against UTC
/// itself.
///
/// Reach for this when somebody named a time in their own clock:
/// `cron_at_offset(\"standup\", \"0 9 * * 1-5\", \"+02:00\", …)` is 09:00 in a
/// UTC+02:00 country, which is 07:00 UTC. Everything else is `cron`'s:
/// the grammar, the ORed day fields, the first fire being the first match
/// after the host loaded the schedule.
///
/// It is a **fixed offset and not a timezone**. Loom carries no timezone
/// database and has ruled that it will not, so nothing here follows a
/// daylight-saving change: an offset written in summer fires an hour out
/// all winter, and one written in winter fires an hour out all summer.
/// Write the offset in force now, and say in the body which clock the
/// schedule was set for, so whoever reads the fire can tell.
///
/// The offset is between `\"-14:00\"` and `\"+14:00\"`; anything outside
/// that, or written any other way, is denied with `invalid_schedule`.
///
/// Capability: `schedule.create`.
pub fn cron_at_offset(String, String, String, Wake, String) -> Result(Created, ScheduleError)
/// `cron`, onto a strand this one spawned rather than onto itself. The
/// target rule and the ownership rule are `every_on`'s exactly.
///
/// Capability: `schedule.create`.
pub fn cron_on(String, String, String, Wake, String) -> Result(Created, ScheduleError)
/// `cron`, with the expiry bounds stated rather than defaulted. The
/// bounds rule is `every_within`'s exactly.
///
/// Capability: `schedule.create`.
pub fn cron_within(String, String, Bounds, Wake, String) -> Result(Created, ScheduleError)
/// Schedules `body` to fire on this strand every `seconds` seconds, until
/// the schedule expires on its own.
///
/// `seconds` has a floor the host enforces; anything tighter is denied
/// with `invalid_schedule` rather than quietly rounded up. `name` must be
/// unique among this strand's schedules and among the host's own — a
/// clash is denied with `schedule_name_taken` rather than replacing
/// anything, so replacing one is always `cancel` then `every` again.
///
/// Capability: `schedule.create`.
pub fn every(String, Int, Wake, String) -> Result(Created, ScheduleError)
/// `every`, onto a strand this one spawned rather than onto itself.
///
/// `target` is that strand's name — the one its handle carries. Anything
/// else is denied with `invalid_schedule`: the host checks the target
/// against its own record of who spawned whom, so a sibling's or a
/// parent's name is refused however it was obtained.
///
/// The schedule is **this** strand's: it appears in `list` with `target`
/// set, and `cancel_on` retires it. It is also always steer-only —
/// `Created.wake` says so — and it ends when the target's work does,
/// which is what a heartbeat watching a subagent wants: it steers the
/// child while there is something to steer and stops when there is not.
///
/// Capability: `schedule.create`.
pub fn every_on(String, String, Int, Wake, String) -> Result(Created, ScheduleError)
/// `every`, with the expiry bounds stated rather than defaulted.
///
/// The only way to ask for a *shorter* life than the host's ceiling —
/// four fires, or an hour — which is what a program wants when the thing
/// it is watching will plainly be over long before a week is. `Bounds`
/// cannot widen anything: a value above the host's ceiling is denied with
/// `invalid_schedule`.
///
/// Capability: `schedule.create`.
pub fn every_within(String, Int, Bounds, Wake, String) -> Result(Created, ScheduleError)
/// Lists the schedules this strand owns, wherever each fires.
///
/// Only ones this strand created — its own heartbeats and any it set onto
/// a strand it spawned, each row naming its `target` — and only ones a
/// program or the model created: a schedule the operator configured is
/// not listed and cannot be cancelled here.
///
/// Capability: `schedule.list`.
pub fn list() -> Result(List(Schedule), ScheduleError)
",
  ),
  #(
    "cap/strand",
    "### cap/strand
`cap/strand` — the orchestration seam: starting, joining, and addressing
other agents from inside a code-mode program.

/// One assignment, built up before it is spawned.
///
/// Opaque, so a non-empty purpose and brief hold by construction and the
/// wire shape stays this module's to change. Build it with `assignment`
/// and narrow it with the pipeable steps below.
pub type Assignment
/// How a `send` payload landed.
pub type Delivery {
  /// The target had an open run: the message is a durable steer on it.
  Steered(entry: String)
  /// The target was idle: the message was accepted as a fresh run.
  Started(operation: String)
}
/// One field of the result shape a spawn demands of its child.
pub type Field {
  Field(name: String, expects: FieldType, required: Bool)
}
/// The closed set of types a declared result field may have — the same
/// vocabulary the harness enforces, and no wider. A schema the harness
/// cannot check is refused rather than accepted and ignored, so there is
/// deliberately no way to spell a pattern, an enum, or a bound.
pub type FieldType {
  /// Text.
  StringField
  /// A whole number.
  IntegerField
  /// Any number, whole or not.
  NumberField
  /// A boolean.
  BooleanField
  /// An object, its own fields undescribed.
  ObjectField
  /// A list of `items`.
  ArrayField(items: FieldType)
  /// Anything at all, `null` included.
  AnyField
}
/// A durable reference to one child operation, as `spawn` minted it. It
/// names nothing process-local, so it survives a restart.
pub type Handle {
  Handle(strand: String, operation: String)
}
/// How a child's operation ended.
pub type Outcome {
  /// The run finished normally.
  Completed
  /// The run failed terminally.
  Failed(reason: String)
  /// The run was aborted — deadline, reap, or operator.
  Aborted
}
/// One entry in the roster: a durable read of the lineage ledger, not of
/// process state, so it is still correct after a restart and after
/// compaction has erased every handle from a model's context.
pub type Peer {
  Peer(strand: String, relation: Relation, handle: option.Option(Handle), outcome: option.Option(Outcome), tools: List(String))
}
/// Where a child's context starts.
pub type Provenance {
  /// At the root: the child reads its brief and nothing else.
  Fresh
  /// At the calling strand's current leaf, copying its whole conversation
  /// into the child's context window.
  MyConversation
}
/// How a peer stands in relation to the calling strand.
pub type Relation {
  /// The strand that spawned the caller.
  ParentOf
  /// A strand the caller spawned.
  ChildOf
}
/// Why a call was refused.
///
/// Every variant but the last two is one of the harness's own refusal
/// names, carrying the harness's own sentence verbatim: the authorization
/// model this seam runs under is `client/agency`'s, reused rather than
/// re-derived, and a refusal renamed on the way out would be a second
/// vocabulary for one decision. `message` is not decoration — it names
/// the strand, the cap, or the field that the name alone does not.
pub type StrandError {
  /// This host wired no messaging plane, or its holder is not up yet.
  StrandsUnavailable(message: String)
  /// A handle did not parse.
  MalformedHandle(message: String)
  /// The named strand is not the caller's parent and not a descendant of
  /// it. Also the answer for a strand with no lineage cell at all: \"no
  /// lineage fact\" means \"not a descendant\", never \"unknown, allow\".
  NotAddressable(message: String)
  /// A join named a strand that is not a descendant of the caller. Joins
  /// are strictly downward — that is what keeps the wait graph acyclic.
  NotADescendant(message: String)
  /// The calling strand is already at the spawning depth cap.
  DepthCapReached(message: String)
  /// The caller, or the session, already has as many live strands as it
  /// may have.
  FanOutCapReached(message: String)
  /// The spawn asked for a tool the calling strand does not itself hold.
  /// A child may narrow its parent's set, never widen it.
  UnknownTool(message: String)
  /// An argument was unusable — an empty purpose, too many handles, a
  /// blackboard key outside the allowed shape, a result shape the harness
  /// cannot enforce.
  InvalidArgument(message: String)
  /// The name this spawn derives is already a child's, minted by a
  /// different call. Reconciliation hands an existing child back on a
  /// name match, but only to the caller that minted it; anything else
  /// would be an ownership transfer. Nothing was started — spawn again
  /// under a different purpose.
  NameAlreadyMinted(message: String)
  /// A send upward would have *started* a run rather than steered one:
  /// the parent has finished and nobody is watching it.
  ParentRunEnded(message: String)
  /// A note did not match the result shape this strand's own spawn
  /// demanded of it.
  ResultSchemaUnmet(message: String)
  /// The durable plane refused or failed underneath the call — a commit,
  /// a read, a decode. Not the program's mistake and not a bound it hit:
  /// the harness could not carry out a call it had no objection to.
  PlaneFailed(message: String)
  /// This execution has admitted as many spawns as it may. The seam's own
  /// ceiling; see the module doc for why a loop needs one where a turn
  /// did not.
  SpawnCeilingReached(message: String)
  /// This execution has admitted as many calls of some *other* capped
  /// capability — `send`, `note` or `notes` — as it may. One variant for
  /// the three because the answer to all three is the same, stop looping,
  /// and the message names which capability, what the number was, and
  /// that the bound is for the execution's whole lifetime. Retrying, or
  /// waiting first, will not free one.
  AdmissionCeilingReached(message: String)
  /// Any other in-band refusal, its code preserved.
  StrandRefused(code: String, message: String)
  /// The capability channel could not carry the call.
  StrandUnavailable(reason: String)
}
/// The verdict on the structured result a spawn asked for.
///
/// Four facts, three of which are not failures, so a program branches on
/// what it actually got rather than on a `Result` that flattens \"nobody
/// asked\" into \"nobody answered\".
pub type TerminalResult {
  /// The spawn declared no result shape.
  NoResultAsked
  /// The child recorded a result and it matched the declared shape.
  ResultGiven(value: report.Value)
  /// A shape was asked for and the child's run ended without recording
  /// one.
  ResultAbsent(schema: String)
  /// A result is there and does not match. `reason` names the field, the
  /// type wanted and the type found.
  ResultUnusable(schema: String, received: report.Value, reason: String)
}
/// One handle's position when a join returned.
pub type Waited {
  /// The operation settled. `report` is the child's final assistant text,
  /// `result` the verdict on the shape the spawn demanded, and `notes`
  /// its blackboard cells.
  Ready(handle: Handle, outcome: Outcome, report: String, result: TerminalResult, notes: List(#(String, report.Value)))
  /// The deadline expired first. An answer, not a failure: join again, or
  /// do other work and come back.
  Pending(handle: Handle, waited_ms: Int)
}
/// How much longer than the requested join window this module will wait
/// on the channel before calling the harness unreachable.
///
/// The harness clamps a join to its own ceiling and answers `Pending`
/// rather than hanging, so this margin covers the round trip and the
/// clamp, never the wait itself.
pub const wait_margin_ms: Int
/// An assignment: what the child is for, and what it is being told.
///
/// `purpose` is what the child's minted name is derived from, so two
/// spawns in one program that share a purpose are two spawns the harness
/// cannot tell apart — give each one its own.
pub fn assignment(purpose: String, brief: String) -> Assignment
/// Detaches the child, so the calling strand's run end does not reap it.
pub fn detached(Assignment) -> Assignment
/// A one-line rendering of a refusal, for a program building a report out
/// of what went wrong rather than branching on it.
pub fn error_text(StrandError) -> String
/// Demands a result shape of the child, which the harness holds it to on
/// its own terminal write — so a program that joins can branch on typed
/// fields instead of parsing prose.
pub fn expecting(Assignment, List(Field)) -> Assignment
/// Starts the child at the calling strand's own leaf, copying its whole
/// conversation, rather than at the root with only its brief.
pub fn from_my_conversation(Assignment) -> Assignment
/// A handle rendered as the text the harness and the model both use,
/// `{strand}#{operation}`.
pub fn handle_text(Handle) -> String
/// Writes one blackboard cell under the calling strand's own namespace.
/// The key is forced under that namespace by the harness, so a program
/// cannot address another strand's notes or a reserved cell.
///
/// Capability: `strand.note`.
pub fn note(key: String, value: report.Value) -> Result(Nil, StrandError)
/// Reads blackboard cells under a key prefix, relative to the shared
/// blackboard namespace. `None` reads the whole blackboard.
///
/// Capability: `strand.notes`.
pub fn notes(option.Option(String)) -> Result(List(#(String, report.Value)), StrandError)
/// A field the child may report.
pub fn optional(String, FieldType) -> Field
/// How long a join actually waited, summed over the handles still pending
/// — a program pacing itself against its own deadline needs the number
/// and would otherwise fold it out of `Waited` by hand.
pub fn pending_count(List(Waited)) -> Int
/// A field the child must report.
pub fn required(String, FieldType) -> Field
/// The calling strand's parent and its live descendants, read from the
/// durable lineage ledger.
///
/// Capability: `strand.roster`.
pub fn roster() -> Result(List(Peer), StrandError)
/// Delivers one attributed message to the calling strand's parent or to
/// one of its descendants.
///
/// The payload travels in a commit and only the wake signal is ephemeral,
/// so a message to a strand that is not running now is drained at its
/// next checkpoint rather than lost.
///
/// Capability: `strand.send`.
pub fn send(to: String, text: String) -> Result(Delivery, StrandError)
/// Starts a child strand and returns a durable handle to its brief run.
///
/// Returns as soon as the harness has admitted the child; the work
/// happens on the child's own strand, and `wait` is how a program learns
/// what it produced.
///
/// Capability: `strand.spawn`.
pub fn spawn(Assignment) -> Result(Handle, StrandError)
/// Waits for every handle against **one** shared deadline and answers one
/// `Waited` per handle, in the order given.
///
/// One deadline rather than one per handle is the whole point: joining
/// eight children costs one window, not eight. A handle whose operation
/// has not settled by then comes back `Pending`, which is an answer — the
/// program may join again, or go on and let the parent strand collect the
/// result on a later turn.
///
/// Capability: `strand.wait`.
pub fn wait(List(Handle), within_ms: Int) -> Result(List(Waited), StrandError)
/// A one-line rendering of one joined handle, for the same reason
/// `error_text` exists: a program that reduces a fan-out to a report
/// should not have to spell the vocabulary out itself.
pub fn waited_text(Waited) -> String
/// Narrows the child's tool set. It may only ever narrow the calling
/// strand's own set; naming a tool the caller does not hold is
/// `UnknownTool`.
pub fn with_tools(Assignment, List(String)) -> Assignment
/// Gives the child a wall budget of its own, in milliseconds.
pub fn within(Assignment, Int) -> Assignment
",
  ),
  #(
    "cap/task",
    "### cap/task
`cap/task` — structured concurrency, and nothing else.

/// How one task ended, from the runner's point of view.
pub type Failure(a) {
  /// The task returned `Error(e)`.
  Returned(index: Int, error: a)
  /// The task's process died before returning (a panic in program code,
  /// or a cancellation). `reason` is a coarse label.
  Crashed(index: Int, reason: String)
}
/// Runs every thunk concurrently (unbounded), aggregating failures.
pub fn all(List(fn() -> Result(a, b))) -> Result(List(a), List(Failure(b)))
/// Runs two tasks concurrently and returns both results, or the first
/// failure (cancelling the other).
pub fn both(fn() -> Result(a, b), fn() -> Result(c, b)) -> Result(#(a, c), Failure(b))
/// Maps `f` over `items` concurrently, at most `max_concurrency` at once,
/// and returns the results in input order. Failures aggregate: if any
/// task fails or crashes, every task still runs to completion and the
/// error is the list of all failures, in index order. For early exit use
/// `parallel_map_fail_fast`.
pub fn parallel_map(List(a), max_concurrency: Int, with: fn(a) -> Result(b, c)) -> Result(List(b), List(Failure(c)))
/// Like `parallel_map`, but the first failure cancels every still-running
/// task (killing them, which cancels their in-flight cap calls) and is
/// returned alone.
pub fn parallel_map_fail_fast(List(a), max_concurrency: Int, with: fn(a) -> Result(b, c)) -> Result(List(b), Failure(c))
/// Runs the tasks concurrently and returns the first to *complete*,
/// killing the rest. A killed loser's in-flight cap call is cancelled at
/// the broker. If the winner returned an error, that error is returned.
pub fn race(List(fn() -> Result(a, b))) -> Result(a, Failure(b))
",
  ),
]
