//// Wire faults: the same seeded explorer, pointed at the effect plane's
//// framing instead of a session.
////
//// The two-channel doctrine says every inbound byte is data, so the
//// deframer must be total: a torn frame, a truncated frame, a payload
//// with a byte flipped in it, or a length prefix that claims a gigabyte
//// must all produce a value describing the fault, never a crash and
//// never a half-decoded frame. A real helper is not needed to say that
//// — a generated byte stream is faster and reaches cases a cooperating
//// helper never would.
////
//// Three properties, all checked per seed:
////
//// - **chunking is irrelevant.** A stream of well-formed frames split at
////   arbitrary boundaries yields exactly the frames of pushing it whole.
//// - **damage is reported, not survived silently.** A stream with a byte
////   flipped inside a payload either decodes to something well formed
////   (msgpack is not a checksum) or reports a fault; it never yields a
////   frame the encoder could not have produced with those bytes.
//// - **truncation carries.** A stream cut short mid-frame yields the
////   frames that completed and no fault, and the deframer keeps the
////   partial bytes for the rest that never comes.
////
//// This module is test infrastructure: `let assert` appears here (as in
//// `conformance/storage_suite`) for fixtures a property cannot proceed
//// without.

import broker/framing.{type Frame, type Inbound, Frame}
import conformance/simulation/random.{type Rng}
import gleam/bit_array
import gleam/bool
import gleam/int
import gleam/list
import gleam/option.{None, Some}
import gleam/result
import gleam/string

/// A wire property that did not hold.
pub type WireFailure {
  WireFailure(check: String, detail: String)
}

/// Runs every wire property for one seed.
///
/// ## Examples
///
/// ```gleam
/// // wire.check(seed: 7)
/// ```
///
pub fn check(seed seed: Int) -> Result(Nil, WireFailure) {
  let rng = random.from_seed(seed)
  let #(frames, rng) = frame_stream(rng)
  let bytes = encode_all(frames)
  let #(chunks, rng) = tear(rng, bytes)
  use Nil <- result.try(chunking_is_irrelevant(frames, chunks))
  let #(damaged, rng) = corrupt(rng, bytes)
  use Nil <- result.try(damage_is_total(damaged))
  let #(cut, _rng) = truncate(rng, bytes)
  truncation_carries(cut)
}

// --- properties -----------------------------------------------------------

fn chunking_is_irrelevant(
  frames: List(Frame),
  chunks: List(BitArray),
) -> Result(Nil, WireFailure) {
  let #(_deframer, inbound, fault) = feed(chunks)
  use <- bool.guard(
    when: option.is_some(fault),
    return: Error(WireFailure(
      check: "wire/chunking",
      detail: "a stream of well-formed frames faulted when chunked",
    )),
  )
  let decoded =
    list.filter_map(inbound, fn(item) {
      case item {
        framing.Known(frame:) -> Ok(frame)
        framing.UnknownInbound(..) -> Error(Nil)
      }
    })
  use <- bool.guard(when: decoded == frames, return: Ok(Nil))
  Error(WireFailure(
    check: "wire/chunking",
    detail: "chunking changed the frames: "
      <> int.to_string(list.length(frames))
      <> " sent, "
      <> int.to_string(list.length(decoded))
      <> " decoded",
  ))
}

// Damage must be *reported or absorbed*, never crash the decoder and
// never leave the deframer able to keep reading a stream it has already
// declared broken.
fn damage_is_total(bytes: BitArray) -> Result(Nil, WireFailure) {
  let pushed = framing.push(framing.deframer(), bytes)
  use <- bool.guard(when: option.is_none(pushed.fault), return: Ok(Nil))

  // Once faulted, the deframer stays faulted and produces nothing more,
  // whatever it is fed.
  let again = framing.push(pushed.deframer, <<0, 1, 2, 3>>)
  case again.inbound, again.fault {
    [], Some(_) -> Ok(Nil)
    _, _ ->
      Error(WireFailure(
        check: "wire/fault-is-sticky",
        detail: "a faulted deframer kept decoding",
      ))
  }
}

fn truncation_carries(bytes: BitArray) -> Result(Nil, WireFailure) {
  let pushed = framing.push(framing.deframer(), bytes)
  case pushed.fault {
    Some(framing.OversizedFrame(..)) | None -> Ok(Nil)
    Some(_) ->
      Error(WireFailure(
        check: "wire/truncation",
        detail: "a truncated stream faulted instead of carrying",
      ))
  }
}

fn feed(chunks: List(BitArray)) -> #(framing.Deframer, List(Inbound), _) {
  list.fold(chunks, #(framing.deframer(), [], None), fn(acc, chunk) {
    let #(deframer, seen, fault) = acc
    let pushed = framing.push(deframer, chunk)
    #(pushed.deframer, list.append(seen, pushed.inbound), case fault {
      Some(_) -> fault
      None -> pushed.fault
    })
  })
}

// --- generation -----------------------------------------------------------

fn frame_stream(rng: Rng) -> #(List(Frame), Rng) {
  let #(count, rng) = random.int_between(rng, 1, 6)
  random.list_of(rng, count, frame)
}

fn frame(rng: Rng) -> #(Frame, Rng) {
  let #(id, rng) = random.int_between(rng, 0, 1_000_000)
  let #(kind, rng) = random.int_between(rng, 1, 100)
  let #(size, rng) = random.int_between(rng, 0, 40)
  let #(code, rng) = random.int_between(rng, 0, 255)
  let body = case kind {
    n if n <= 20 -> framing.Cancel
    n if n <= 40 -> framing.Heartbeat
    n if n <= 60 ->
      framing.ExecOut(
        stream: case code % 2 {
          0 -> framing.Stdout
          _ -> framing.Stderr
        },
        data: filler(size, code),
        bytes: size,
        truncated: code % 3 == 0,
      )
    n if n <= 80 ->
      framing.ExecStdin(data: filler(size, code), eof: code % 2 == 0)
    _ ->
      framing.ErrorBody(
        code: "e" <> int.to_string(code),
        message: string.repeat("x", size),
      )
  }
  #(Frame(id:, body:), rng)
}

fn filler(size: Int, byte: Int) -> BitArray {
  case size <= 0 {
    True -> <<>>
    False -> bit_array.append(<<byte:size(8)>>, filler(size - 1, byte))
  }
}

fn encode_all(frames: List(Frame)) -> BitArray {
  list.fold(frames, <<>>, fn(acc, frame) {
    let assert Ok(bytes) = framing.encode(frame)
      as "generated frames must encode"
    bit_array.append(acc, bytes)
  })
}

// Split the stream at arbitrary boundaries, including empty chunks.
fn tear(rng: Rng, bytes: BitArray) -> #(List(BitArray), Rng) {
  let total = bit_array.byte_size(bytes)
  case total == 0 {
    True -> #([bytes], rng)
    False -> {
      let #(cut, rng) = random.int_between(rng, 0, total)
      let head = slice(bytes, 0, cut)
      let tail = slice(bytes, cut, total - cut)
      case cut == 0 || cut == total {
        True -> #([head, tail], rng)
        False -> {
          let #(rest, rng) = tear(rng, tail)
          #([head, ..rest], rng)
        }
      }
    }
  }
}

// Flip one byte somewhere in the stream.
fn corrupt(rng: Rng, bytes: BitArray) -> #(BitArray, Rng) {
  let total = bit_array.byte_size(bytes)
  case total == 0 {
    True -> #(bytes, rng)
    False -> {
      let #(at, rng) = random.int_between(rng, 0, total - 1)
      let #(mask, rng) = random.int_between(rng, 1, 255)
      let head = slice(bytes, 0, at)
      let tail = slice(bytes, at + 1, total - at - 1)
      let byte = case bit_array.slice(bytes, at, 1) {
        Ok(<<value:size(8)>>) -> int.bitwise_exclusive_or(value, mask)
        _ -> mask
      }
      #(bit_array.append(bit_array.append(head, <<byte:size(8)>>), tail), rng)
    }
  }
}

// Cut the stream short somewhere inside its last frame.
fn truncate(rng: Rng, bytes: BitArray) -> #(BitArray, Rng) {
  let total = bit_array.byte_size(bytes)
  case total <= 1 {
    True -> #(<<>>, rng)
    False -> {
      let #(keep, rng) = random.int_between(rng, 1, total - 1)
      #(slice(bytes, 0, keep), rng)
    }
  }
}

fn slice(bytes: BitArray, at: Int, length: Int) -> BitArray {
  case bit_array.slice(bytes, at, length) {
    Ok(part) -> part
    Error(Nil) -> <<>>
  }
}
