//// Closed Launch data framing preserves original identity without granting custody.
////
//// Whole inputs use service_input's existing length-prefixed canonical ServiceKey
//// and exact body. Metadata uses the native bounded MessagePack profile; source
//// and completion bytes travel through workspace_transfer's existing directions.
//// A received completion is checked history, not a local journal COMMIT handle.
//// The owner must retain its exact bytes before acknowledging them.
////
//// `encode_input` and `decode_input` check canonical input and its actual digest.
//// `encode_reply` projects retained local data into bounded metadata and optional
//// unchanged completion bytes. `decode_reply` checks the full expected key and
//// enrollment before exposing historical locations or the closed result.

import broker/enrollment
import codemode/service_input as input
import codemode/service_resources as resources
import core/bounded_msgpack
import core/command
import core/json
import core/msgpack as mp
import executor/remote/identity
import executor/remote/launch_completion as completion
import executor/remote/launch_service as service
import executor/remote/resource_journal as journal
import gleam/bit_array
import gleam/bool
import gleam/crypto
import gleam/option.{type Option, None, Some}
import gleam/result
import gleam/string

/// The configured Launch endpoint accepts only this closed operation vocabulary.
pub type Command {
  /// Requests one original single-use 1000-millisecond ticket.
  ChallengeRequest

  /// Spends the original ticket and remaining attempt duration.
  PlaceToken(
    /// Exactly 32 bytes issued for the same complete key.
    nonce: BitArray,
    /// Original remaining duration, never a renewed deadline.
    budget_ms: Int,
  )

  /// Reads retained history without permission to prepare or finalize.
  Query

  /// Fences original input before following its native association.
  Cancel

  /// Records only the trusted owner's definite refusal before native dispatch.
  RefuseBeforeNative

  /// Reports the owner's separately committed exact-byte receipt.
  Acknowledge(
    /// SHA-256 of the retained outer completion bytes.
    digest: identity.Digest,
  )
}

/// Network completion data cannot construct a local journal retention handle.
pub type Completion {
  /// No exact outer result was retained in this reply.
  Pending

  /// Checked immutable historical result, without another effect permission.
  Retained(
    /// Decoded exact result, including its original executor artifact or error.
    value: completion.LaunchCompletion,
    /// Unchanged bytes which the owner must durably retain before ACK.
    bytes: BitArray,
    /// Actual SHA-256 of these bytes, separate from the native Prepared digest.
    digest: identity.Digest,
    /// Independent retained outer receipt state.
    receipt: journal.OuterReceipt,
  )
}

/// Checked replies preserve preparation, completion and cancellation separately.
pub type Reply {
  /// A short ticket authenticates only its exact complete original key.
  Challenge(
    /// Original complete Launch identity.
    key: command.ServiceKey,
    /// Exactly 32 bytes, never regenerated by a retry.
    nonce: BitArray,
    /// Exactly 1000 milliseconds on the executor's independent clock.
    window_ms: Int,
  )

  /// Historical Ready is neither a successful Launch nor a live allocation.
  Observed(
    /// Preparation history, preserving optional original Ready evidence.
    preparation: journal.Status,
    /// Independent committed outer outcome and receipt.
    completion: Completion,
  )

  /// Committed input/scope fence does not establish native cleanup.
  Cancelled(
    /// Exact retained fence disposition.
    fence: journal.PreparationFence,
  )
}

/// No invalid framing is converted into successful unknown evidence.
pub type Error {
  /// Unsupported, oversized, noncanonical or mismatched data.
  Invalid

  /// The service refused this operation without returning durable evidence.
  Refused
}

/// Encodes exact original input under its existing whole-envelope bound.
///
/// ## Examples
///
/// ```gleam
/// launch_wire.encode_input(enrolled, original) // -> Ok(canonical_bytes).
/// ```
pub fn encode_input(
  enrolled: enrollment.SessionEnrollment,
  original: journal.Input,
) -> Result(BitArray, Error) {
  use decoded <- result.try(input.decode_launch(original.body) |> invalid)
  let facts = input.launch_facts(decoded)
  use Nil <- result.try(enrollment.matches(enrolled, facts.enrolled) |> invalid)
  let digest =
    crypto.hash(crypto.Sha256, original.body)
    |> bit_array.base16_encode
    |> string.lowercase
  use Nil <- result.try(
    bool.guard(
      !{ digest == command.digests(original.key).0 },
      Error(Invalid),
      fn() { Ok(Nil) },
    ),
  )
  input.launch_envelope(original.key, decoded) |> invalid
}

/// Checks declared header size before decoding canonical complete-key JSON.
///
/// ## Examples
///
/// ```gleam
/// assert launch_wire.decode_input(enrolled, <<0xffffffff:32>>) == Error(launch_wire.Invalid)
/// ```
pub fn decode_input(
  enrolled: enrollment.SessionEnrollment,
  bytes: BitArray,
) -> Result(journal.Input, Error) {
  use Nil <- result.try(
    bool.guard(
      !{ bit_array.byte_size(bytes) <= input.max_envelope_bytes },
      Error(Invalid),
      fn() { Ok(Nil) },
    ),
  )
  use #(header, body) <- result.try(case bytes {
    <<size:32, text:bytes-size(size), body:bytes>> if size > 0 && size <= 8192 ->
      Ok(#(text, body))
    _ -> Error(Invalid)
  })
  use key <- result.try(read_key(header))
  let original = journal.Input(key, body)
  use canonical <- result.try(encode_input(enrolled, original))
  use Nil <- result.try(
    bool.guard(!{ canonical == bytes }, Error(Invalid), fn() { Ok(Nil) }),
  )
  Ok(original)
}

/// Encodes only the fixed Launch operation header used by the BEAM endpoint.
/// The largest header is 41 bytes. Encoding grants no input admission or retry.
///
/// ## Examples
///
/// ```gleam
/// assert launch_wire.encode_command(launch_wire.Query) == Ok(<<"LLQ", 1, 2>>)
/// ```
@internal
pub fn encode_command(operation: Command) -> Result(BitArray, Error) {
  case operation {
    ChallengeRequest -> Ok(<<"LLQ", 1, 0>>)
    PlaceToken(nonce, budget) if budget > 0 && budget <= 86_400_000 -> {
      case nonce {
        <<nonce:bytes-size(32)>> -> Ok(<<"LLQ", 1, 1, nonce:bits, budget:32>>)
        _ -> Error(Invalid)
      }
    }
    PlaceToken(_, _) -> Error(Invalid)
    Query -> Ok(<<"LLQ", 1, 2>>)
    Cancel -> Ok(<<"LLQ", 1, 3>>)
    RefuseBeforeNative -> Ok(<<"LLQ", 1, 5>>)
    Acknowledge(digest) ->
      Ok(<<"LLQ", 1, 4, identity.digest_bytes(digest):bits>>)
  }
}

/// Checks the entire fixed header before exposing its closed operation.
/// No trailing bytes, unknown variant or renewed nonpositive budget is accepted.
///
/// ## Examples
///
/// ```gleam
/// assert launch_wire.decode_command(<<"LLQ", 1, 2, 0>>) == Error(launch_wire.Invalid)
/// ```
@internal
pub fn decode_command(bytes: BitArray) -> Result(Command, Error) {
  case bytes {
    <<"LLQ", 1, 0>> -> Ok(ChallengeRequest)
    <<"LLQ", 1, 1, nonce:bytes-size(32), budget:32>>
      if budget > 0 && budget <= 86_400_000
    -> Ok(PlaceToken(nonce, budget))
    <<"LLQ", 1, 2>> -> Ok(Query)
    <<"LLQ", 1, 3>> -> Ok(Cancel)
    <<"LLQ", 1, 5>> -> Ok(RefuseBeforeNative)
    <<"LLQ", 1, 4, bytes:bytes-size(32)>> ->
      identity.digest(bytes)
      |> invalid
      |> result.map(Acknowledge)
    _ -> Error(Invalid)
  }
}

/// Projects an actual service answer; completion bytes remain outside metadata.
///
/// ## Examples
///
/// ```gleam
/// launch_wire.encode_reply(key, answer) // -> Ok(#(metadata, optional_bytes)).
/// ```
@internal
pub fn encode_reply(
  key: command.ServiceKey,
  answer: Result(service.Reply, service.Error),
) -> Result(#(BitArray, Option(BitArray)), Error) {
  use <- bool.guard(
    command.service_role(key) != command.LaunchService,
    Error(Invalid),
  )
  use #(body, content) <- result.try(reply_value(key, answer))
  use bytes <- result.try(encode(frame(key, body)))
  Ok(#(bytes, content))
}

/// Checks metadata before the caller receives a completion transfer.
///
/// ## Examples
///
/// ```gleam
/// assert launch_wire.has_completion(<<>>) == Error(launch_wire.Invalid)
/// ```
@internal
pub fn has_completion(bytes: BitArray) -> Result(Bool, Error) {
  use value <- result.try(bounded_msgpack.decode(bytes) |> invalid)
  use canonical <- result.try(encode(value))
  use Nil <- result.try(
    bool.guard(!{ canonical == bytes }, Error(Invalid), fn() { Ok(Nil) }),
  )
  case value {
    mp.ArrayValue([
      mp.IntValue(1),
      mp.StringValue("loom.remote.launch/1"),
      mp.StringValue(_),
      mp.ArrayValue([mp.IntValue(1), _, mp.ArrayValue([mp.IntValue(1), _, _])]),
    ]) -> Ok(True)
    mp.ArrayValue([
      mp.IntValue(1),
      mp.StringValue("loom.remote.launch/1"),
      mp.StringValue(_),
      _,
    ]) -> Ok(False)
    _ -> Error(Invalid)
  }
}

/// Decodes history against canonical original input, producer and pinned enrollment.
///
/// ## Examples
///
/// ```gleam
/// assert launch_wire.decode_reply(enrolled, original, <<>>, None) == Error(launch_wire.Invalid)
/// ```
pub fn decode_reply(
  enrolled: enrollment.SessionEnrollment,
  original: journal.Input,
  bytes: BitArray,
  content: Option(BitArray),
) -> Result(Reply, Error) {
  use _ <- result.try(encode_input(enrolled, original))
  use launch_input <- result.try(input.decode_launch(original.body) |> invalid)
  let producer = input.launch_facts(launch_input).compiled_by
  let key = original.key
  let #(scope, _, _) = command.coordinates(key)
  let #(_, registration, contract) = command.digests(key)
  use <- bool.guard(
    command.service_role(key) != command.LaunchService
      || scope != enrollment.native_facts(enrolled).scope
      || #(registration, contract) != enrollment.digests(enrolled),
    Error(Invalid),
  )
  use value <- result.try(bounded_msgpack.decode(bytes) |> invalid)
  use canonical <- result.try(encode(value))
  use Nil <- result.try(
    bool.guard(!{ canonical == bytes }, Error(Invalid), fn() { Ok(Nil) }),
  )
  let expected = key_text(key)
  use body <- result.try(case value {
    mp.ArrayValue([
      mp.IntValue(1),
      mp.StringValue("loom.remote.launch/1"),
      mp.StringValue(text),
      body,
    ])
      if text == expected
    -> Ok(body)
    _ -> Error(Invalid)
  })
  case body, content {
    mp.ArrayValue([mp.IntValue(0), mp.BinaryValue(nonce), mp.IntValue(1000)]),
      None
    -> {
      use Nil <- result.try(
        bool.guard(!{ bit_array.byte_size(nonce) == 32 }, Error(Invalid), fn() {
          Ok(Nil)
        }),
      )
      Ok(Challenge(key, nonce, 1000))
    }
    mp.ArrayValue([mp.IntValue(1), prepared, completed]), content -> {
      use prepared <- result.try(read_status(enrolled, key, producer, prepared))
      use completed <- result.try(read_completion(
        enrolled,
        key,
        completed,
        content,
      ))
      Ok(Observed(prepared, completed))
    }
    mp.ArrayValue([mp.IntValue(2), mp.IntValue(0), prepared]), None ->
      read_status(enrolled, key, producer, prepared)
      |> result.map(fn(status) { Cancelled(journal.InputFenced(status)) })
    mp.ArrayValue([mp.IntValue(2), mp.IntValue(1)]), None ->
      Ok(Cancelled(journal.ScopeFenced))
    mp.ArrayValue([mp.IntValue(3)]), None -> Error(Refused)
    _, _ -> Error(Invalid)
  }
}

fn frame(key: command.ServiceKey, body: mp.MsgPackValue) -> mp.MsgPackValue {
  mp.ArrayValue([
    mp.IntValue(1),
    mp.StringValue("loom.remote.launch/1"),
    mp.StringValue(key_text(key)),
    body,
  ])
}

fn reply_value(
  key: command.ServiceKey,
  answer: Result(service.Reply, service.Error),
) -> Result(#(mp.MsgPackValue, Option(BitArray)), Error) {
  case answer {
    Error(_) -> Ok(#(mp.ArrayValue([mp.IntValue(3)]), None))
    Ok(service.Challenge(returned, nonce, window)) -> {
      use Nil <- result.try(
        bool.guard(
          !{
            returned == key
            && bit_array.byte_size(nonce) == 32
            && window == 1000
          },
          Error(Invalid),
          fn() { Ok(Nil) },
        ),
      )
      Ok(#(
        mp.ArrayValue([
          mp.IntValue(0),
          mp.BinaryValue(nonce),
          mp.IntValue(window),
        ]),
        None,
      ))
    }
    Ok(service.Observed(prepared, completed)) -> {
      use prepared <- result.try(status_value(prepared))
      let #(completed, content) = completion_value(completed)
      Ok(#(mp.ArrayValue([mp.IntValue(1), prepared, completed]), content))
    }
    Ok(service.Cancelled(journal.InputFenced(status))) -> {
      use status <- result.try(status_value(status))
      Ok(#(mp.ArrayValue([mp.IntValue(2), mp.IntValue(0), status]), None))
    }
    Ok(service.Cancelled(journal.ScopeFenced)) ->
      Ok(#(mp.ArrayValue([mp.IntValue(2), mp.IntValue(1)]), None))
  }
}

fn status_value(status: journal.Status) -> Result(mp.MsgPackValue, Error) {
  case status {
    journal.Reserved -> Ok(mp.ArrayValue([mp.IntValue(0)]))
    journal.Unknown(ready) -> optional_ready(1, ready)
    journal.Prepared(ready) -> optional_ready(2, Some(ready))
    journal.Released(ready) -> optional_ready(3, ready)
  }
}

fn optional_ready(
  tag: Int,
  ready: Option(resources.Ready),
) -> Result(mp.MsgPackValue, Error) {
  use held <- result.try(case ready {
    None -> Ok(mp.NilValue)
    Some(ready) ->
      resources.encode(ready) |> invalid |> result.map(mp.BinaryValue)
  })
  Ok(mp.ArrayValue([mp.IntValue(tag), held]))
}

fn read_status(
  enrolled: enrollment.SessionEnrollment,
  key: command.ServiceKey,
  producer: command.ServiceKey,
  value: mp.MsgPackValue,
) -> Result(journal.Status, Error) {
  case value {
    mp.ArrayValue([mp.IntValue(0)]) -> Ok(journal.Reserved)
    mp.ArrayValue([mp.IntValue(tag), held]) if tag >= 1 && tag <= 3 -> {
      use ready <- result.try(read_ready(enrolled, key, producer, held))
      case tag, ready {
        1, ready -> Ok(journal.Unknown(ready))
        2, Some(ready) -> Ok(journal.Prepared(ready))
        3, ready -> Ok(journal.Released(ready))
        _, _ -> Error(Invalid)
      }
    }
    _ -> Error(Invalid)
  }
}

fn read_ready(
  enrolled: enrollment.SessionEnrollment,
  key: command.ServiceKey,
  producer: command.ServiceKey,
  value: mp.MsgPackValue,
) -> Result(Option(resources.Ready), Error) {
  case value {
    mp.NilValue -> Ok(None)
    mp.BinaryValue(bytes) -> {
      use ready <- result.try(resources.decode(enrolled, bytes) |> invalid)
      case ready {
        resources.LaunchReady(locations) -> {
          use Nil <- result.try(
            bool.guard(
              !{ resources.launch_keys(locations) == #(key, producer) },
              Error(Invalid),
              fn() { Ok(Nil) },
            ),
          )
          Ok(Some(ready))
        }
        resources.CompileReady(_) -> Error(Invalid)
      }
    }
    mp.IntValue(_)
    | mp.FloatValue(_)
    | mp.StringValue(_)
    | mp.BoolValue(_)
    | mp.ArrayValue(_)
    | mp.MapValue(_) -> Error(Invalid)
  }
}

fn completion_value(
  status: journal.LaunchStatus,
) -> #(mp.MsgPackValue, Option(BitArray)) {
  case status {
    journal.LaunchPending -> #(mp.ArrayValue([mp.IntValue(0)]), None)
    journal.LaunchRetained(retained, receipt) -> {
      let tag = case receipt {
        journal.ReceiptPending -> 0
        journal.ReceiptAcknowledged -> 1
      }
      #(
        mp.ArrayValue([
          mp.IntValue(1),
          mp.IntValue(tag),
          mp.BinaryValue(
            identity.digest_bytes(journal.retained_launch_digest(retained)),
          ),
        ]),
        Some(journal.retained_launch_bytes(retained)),
      )
    }
  }
}

fn read_completion(
  enrolled: enrollment.SessionEnrollment,
  key: command.ServiceKey,
  value: mp.MsgPackValue,
  content: Option(BitArray),
) -> Result(Completion, Error) {
  case value, content {
    mp.ArrayValue([mp.IntValue(0)]), None -> Ok(Pending)
    mp.ArrayValue([mp.IntValue(1), mp.IntValue(tag), mp.BinaryValue(digest)]),
      Some(bytes)
      if tag == 0 || tag == 1
    -> {
      use digest <- result.try(identity.digest(digest) |> invalid)
      use Nil <- result.try(
        bool.guard(
          !{
            crypto.hash(crypto.Sha256, bytes) == identity.digest_bytes(digest)
          },
          Error(Invalid),
          fn() { Ok(Nil) },
        ),
      )
      use value <- result.try(
        completion.decode(enrolled, key, bytes) |> invalid,
      )
      let receipt = case tag {
        0 -> journal.ReceiptPending
        _ -> journal.ReceiptAcknowledged
      }
      Ok(Retained(value, bytes, digest, receipt))
    }
    _, _ -> Error(Invalid)
  }
}

fn read_key(bytes: BitArray) -> Result(command.ServiceKey, Error) {
  use text <- result.try(bit_array.to_string(bytes) |> invalid)
  use value <- result.try(json.parse(text) |> invalid)
  use key <- result.try(command.decode_service(value) |> invalid)
  use Nil <- result.try(
    bool.guard(!{ key_text(key) == text }, Error(Invalid), fn() { Ok(Nil) }),
  )
  Ok(key)
}

fn key_text(key: command.ServiceKey) -> String {
  command.encode_service(key) |> json.to_string
}

fn encode(value: mp.MsgPackValue) -> Result(BitArray, Error) {
  use bytes <- result.try(mp.encode(value) |> invalid)
  use _ <- result.try(bounded_msgpack.decode(bytes) |> invalid)
  Ok(bytes)
}

fn invalid(value: Result(a, b)) -> Result(a, Error) {
  result.replace_error(value, Invalid)
}

/// Encodes placement transport separately from immutable canonical Launch input.
///
/// ## Examples
///
/// ```gleam
/// launch_wire.encode_placement(enrolled, original, token) // -> Ok(closed_body).
/// ```
pub fn encode_placement(
  enrolled: enrollment.SessionEnrollment,
  original: journal.Input,
  token: BitArray,
) -> Result(BitArray, Error) {
  use bytes <- result.try(encode_input(enrolled, original))
  case token {
    <<token:bytes-size(32)>> -> Ok(<<token:bits, bytes:bits>>)
    _ -> Error(Invalid)
  }
}

/// Opens the fixed placement wrapper without putting its token in history.
///
/// ## Examples
///
/// ```gleam
/// assert launch_wire.decode_placement(enrolled, <<>>) == Error(launch_wire.Invalid)
/// ```
pub fn decode_placement(
  enrolled: enrollment.SessionEnrollment,
  bytes: BitArray,
) -> Result(#(journal.Input, BitArray), Error) {
  case bytes {
    <<token:bytes-size(32), envelope:bytes>> ->
      decode_input(enrolled, envelope)
      |> result.map(fn(original) { #(original, token) })
    _ -> Error(Invalid)
  }
}
