name = "tui"
version = "0.2.0"
target = "erlang"
gleam = ">= 1.16.0"

[dependencies]
host = { path = "../host" }
argv = ">= 1.1.0 and < 2.0.0"
core = { path = "../core" }
machine = { path = "../machine" }
session_view = { path = "../session_view" }
etui = { git = "https://github.com/Roasbeef/etui.git", ref = "81fda7d9b96ca467c2e88c9d2d1788799bf77b4a" }
filepath = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
tom = ">= 2.1.0 and < 3.0.0"
weft = "== 0.4.6"
gun = ">= 2.6.0 and < 3.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleamy_bench = ">= 0.6.0 and < 1.0.0"
