name = "tui"
version = "0.1.0"
target = "erlang"
gleam = ">= 1.16.0"

[dependencies]
host = { path = "../host" }
argv = ">= 1.1.0 and < 2.0.0"
core = { path = "../core" }
machine = { path = "../machine" }
etui = { git = "https://github.com/Roasbeef/etui.git", ref = "ff80e0e21580a4b0077cc6989b6dc551af320505" }
filepath = ">= 1.0.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
mork = ">= 1.12.1 and < 1.13.0"
simplifile = ">= 2.0.0 and < 3.0.0"
weft = "== 0.4.4"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleamy_bench = ">= 0.6.0 and < 1.0.0"
