//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.
//// The checked-in SQL file is the schema source of truth.

/// The schema used both at runtime and by sqlc during generation.
pub const schema =
  "-- Executor custody history. This is the runtime and sqlc schema source.\nCREATE TABLE custody_meta (\n  id INTEGER PRIMARY KEY CHECK(id = 1),\n  binding BLOB NOT NULL,\n  capacity INTEGER NOT NULL,\n  version INTEGER NOT NULL CHECK(version >= 0 AND version <= capacity * 6 + 1),\n  bytes INTEGER NOT NULL CHECK(bytes >= 0 AND bytes <= version * 138)\n);\n\nCREATE TABLE custody_event (\n  seq INTEGER PRIMARY KEY,\n  payload BLOB NOT NULL\n);\n\n\n-- Immutable native request/output/terminal custody. Slots never evict keys.\nCREATE TABLE custody_payload (\n  request BLOB NOT NULL CHECK(length(request) <= 138),\n  digest BLOB NOT NULL CHECK(length(digest) = 32),\n  kind INTEGER NOT NULL CHECK(kind BETWEEN 0 AND 4),\n  ordinal INTEGER NOT NULL CHECK(ordinal BETWEEN 0 AND 63),\n  body BLOB NOT NULL CHECK(length(body) <= 131072),\n  PRIMARY KEY (request, kind, ordinal)\n);\n"
