//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.
//// The checked-in SQL file is the schema source of truth.

/// The schema used both at runtime and by sqlc during generation.
pub const schema =
  "-- Upgrade only checked version-1 custody; original rows are never backfilled.\nCREATE TABLE generation_meta_v2 (\n id INTEGER PRIMARY KEY CHECK(id=1),\n format INTEGER NOT NULL CHECK(format=2),\n live_limit INTEGER NOT NULL CHECK(live_limit BETWEEN 1 AND 16),\n row_limit INTEGER NOT NULL CHECK(row_limit BETWEEN 1 AND 4096),\n byte_limit INTEGER NOT NULL CHECK(byte_limit BETWEEN 1 AND 268435456)\n);\nINSERT INTO generation_meta_v2(id,format,live_limit,row_limit,byte_limit)\n SELECT id,2,live_limit,row_limit,byte_limit FROM generation_meta;\nDROP TABLE generation_meta;\nALTER TABLE generation_meta_v2 RENAME TO generation_meta;\nCREATE TABLE generation_scope_plan (\n key BLOB PRIMARY KEY NOT NULL REFERENCES generation_record(key),\n header BLOB NOT NULL CHECK(length(header) BETWEEN 1 AND 262144),\n enrollment BLOB NOT NULL CHECK(length(enrollment) BETWEEN 1 AND 262144),\n digest BLOB NOT NULL CHECK(length(digest)=32)\n);\n"
