//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import parrot/dev

pub fn initialize_custody(binding binding: BitArray, capacity capacity: Int) {
  let sql =
    "
INSERT INTO custody_meta (id, binding, capacity, version, bytes)
VALUES (1, ?, ?, 0, 0)"
  #(sql, [dev.ParamBitArray(binding), dev.ParamInt(capacity)])
}

pub type CustodyMetadata {
  CustodyMetadata(binding: BitArray, capacity: Int, version: Int, bytes: Int)
}

pub fn custody_metadata() {
  let sql =
    "SELECT CAST(CASE WHEN typeof(binding) = 'blob' AND length(binding) <= 303
                 THEN binding ELSE NULL END AS BLOB) AS binding,
       CAST(CASE WHEN typeof(capacity) = 'integer'
                 THEN capacity ELSE NULL END AS INTEGER) AS capacity,
       CAST(CASE WHEN typeof(version) = 'integer'
                 THEN version ELSE NULL END AS INTEGER) AS version,
       CAST(CASE WHEN typeof(bytes) = 'integer'
                 THEN bytes ELSE NULL END AS INTEGER) AS bytes
FROM custody_meta LIMIT 2"
  #(sql, [], custody_metadata_decoder())
}

pub fn custody_metadata_decoder() -> decode.Decoder(CustodyMetadata) {
  use binding <- decode.field(0, decode.bit_array)
  use capacity <- decode.field(1, decode.int)
  use version <- decode.field(2, decode.int)
  use bytes <- decode.field(3, decode.int)
  decode.success(CustodyMetadata(binding:, capacity:, version:, bytes:))
}

pub type CustodyEvents {
  CustodyEvents(seq: Int, payload: BitArray)
}

pub fn custody_events(limit limit: Int) {
  let sql =
    "SELECT seq,
       CAST(CASE WHEN typeof(payload) = 'blob' AND length(payload) <= 138
                 THEN payload ELSE NULL END AS BLOB) AS payload
FROM custody_event ORDER BY seq LIMIT ?"
  #(sql, [dev.ParamInt(limit)], custody_events_decoder())
}

pub fn custody_events_decoder() -> decode.Decoder(CustodyEvents) {
  use seq <- decode.field(0, decode.int)
  use payload <- decode.field(1, decode.bit_array)
  decode.success(CustodyEvents(seq:, payload:))
}

pub fn append_custody_event(seq seq: Int, payload payload: BitArray) {
  let sql = "INSERT INTO custody_event (seq, payload) VALUES (?, ?)"
  #(sql, [dev.ParamInt(seq), dev.ParamBitArray(payload)])
}

pub type AdvanceCustodyHead {
  AdvanceCustodyHead(version: Int)
}

pub fn advance_custody_head(
  next_version next_version: Int,
  next_bytes next_bytes: Int,
  previous_version previous_version: Int,
  previous_bytes previous_bytes: Int,
) {
  let sql =
    "UPDATE custody_meta SET version = ?1, bytes = ?2
WHERE id = 1 AND version = ?3 AND bytes = ?4
RETURNING version"
  #(
    sql,
    [
      dev.ParamInt(next_version),
      dev.ParamInt(next_bytes),
      dev.ParamInt(previous_version),
      dev.ParamInt(previous_bytes),
    ],
    advance_custody_head_decoder(),
  )
}

pub fn advance_custody_head_decoder() -> decode.Decoder(AdvanceCustodyHead) {
  use version <- decode.field(0, decode.int)
  decode.success(AdvanceCustodyHead(version:))
}

pub type PayloadInventory {
  PayloadInventory(items: Int, bytes: Int)
}

pub fn payload_inventory(request request: BitArray, kind kind: Int) {
  let sql =
    "SELECT COUNT(*) AS items,
       CAST(COALESCE(SUM(length(body)), 0) AS INTEGER) AS bytes
FROM custody_payload WHERE request = ? AND kind = ?"
  #(
    sql,
    [dev.ParamBitArray(request), dev.ParamInt(kind)],
    payload_inventory_decoder(),
  )
}

pub fn payload_inventory_decoder() -> decode.Decoder(PayloadInventory) {
  use items <- decode.field(0, decode.int)
  use bytes <- decode.field(1, decode.int)
  decode.success(PayloadInventory(items:, bytes:))
}

pub type PayloadReservations {
  PayloadReservations(items: Int)
}

pub fn payload_reservations() {
  let sql =
    "SELECT COUNT(DISTINCT request) AS items FROM custody_payload WHERE kind IN (0, 4)"
  #(sql, [], payload_reservations_decoder())
}

pub fn payload_reservations_decoder() -> decode.Decoder(PayloadReservations) {
  use items <- decode.field(0, decode.int)
  decode.success(PayloadReservations(items:))
}

pub type ReadCustodyPayload {
  ReadCustodyPayload(digest: BitArray, kind: Int, ordinal: Int, body: BitArray)
}

pub fn read_custody_payload(request request: BitArray) {
  let sql =
    "SELECT CAST(CASE WHEN typeof(digest) = 'blob' AND length(digest) = 32
                 THEN digest ELSE NULL END AS BLOB) AS digest,
       CAST(CASE WHEN typeof(kind) = 'integer' AND kind BETWEEN 0 AND 4
                 THEN kind ELSE NULL END AS INTEGER) AS kind,
       CAST(CASE WHEN typeof(ordinal) = 'integer' AND ordinal BETWEEN 0 AND 63
                 THEN ordinal ELSE NULL END AS INTEGER) AS ordinal,
       CAST(CASE WHEN typeof(body) = 'blob'
                 AND length(body) <= CASE kind WHEN 0 THEN 131072 WHEN 1 THEN 1024
                   WHEN 2 THEN 16384 WHEN 3 THEN 32768 WHEN 4 THEN 32768 ELSE 0 END
                 THEN body ELSE NULL END AS BLOB) AS body
FROM custody_payload WHERE request = ? ORDER BY kind, ordinal LIMIT 69"
  #(sql, [dev.ParamBitArray(request)], read_custody_payload_decoder())
}

pub fn read_custody_payload_decoder() -> decode.Decoder(ReadCustodyPayload) {
  use digest <- decode.field(0, decode.bit_array)
  use kind <- decode.field(1, decode.int)
  use ordinal <- decode.field(2, decode.int)
  use body <- decode.field(3, decode.bit_array)
  decode.success(ReadCustodyPayload(digest:, kind:, ordinal:, body:))
}

pub fn insert_custody_payload(
  request request: BitArray,
  digest digest: BitArray,
  kind kind: Int,
  ordinal ordinal: Int,
  body body: BitArray,
) {
  let sql =
    "INSERT INTO custody_payload (request, digest, kind, ordinal, body) VALUES (?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamBitArray(request),
    dev.ParamBitArray(digest),
    dev.ParamInt(kind),
    dev.ParamInt(ordinal),
    dev.ParamBitArray(body),
  ])
}
