//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import gleam/option.{type Option}
import parrot/dev

pub fn initialize_custody(binding binding: BitArray, capacity capacity: Int) {
  let sql =
    "
INSERT INTO custody_meta (id, binding, capacity, version, bytes)
VALUES (1, ?, ?, 0, 0)"
  #(sql, [dev.ParamBitArray(binding), dev.ParamInt(capacity)])
}

pub type CustodyMetadata {
  CustodyMetadata(binding: BitArray, capacity: Int, version: Int, bytes: Int)
}

pub fn custody_metadata() {
  let sql =
    "SELECT CAST(CASE WHEN typeof(binding) = 'blob' AND length(binding) <= 303
                 THEN binding ELSE NULL END AS BLOB) AS binding,
       CAST(CASE WHEN typeof(capacity) = 'integer'
                 THEN capacity ELSE NULL END AS INTEGER) AS capacity,
       CAST(CASE WHEN typeof(version) = 'integer'
                 THEN version ELSE NULL END AS INTEGER) AS version,
       CAST(CASE WHEN typeof(bytes) = 'integer'
                 THEN bytes ELSE NULL END AS INTEGER) AS bytes
FROM custody_meta LIMIT 2"
  #(sql, [], custody_metadata_decoder())
}

pub fn custody_metadata_decoder() -> decode.Decoder(CustodyMetadata) {
  use binding <- decode.field(0, decode.bit_array)
  use capacity <- decode.field(1, decode.int)
  use version <- decode.field(2, decode.int)
  use bytes <- decode.field(3, decode.int)
  decode.success(CustodyMetadata(binding:, capacity:, version:, bytes:))
}

pub type CustodyEvents {
  CustodyEvents(seq: Int, payload: BitArray)
}

pub fn custody_events(limit limit: Int) {
  let sql =
    "SELECT seq,
       CAST(CASE WHEN typeof(payload) = 'blob' AND length(payload) <= 138
                 THEN payload ELSE NULL END AS BLOB) AS payload
FROM custody_event ORDER BY seq LIMIT ?"
  #(sql, [dev.ParamInt(limit)], custody_events_decoder())
}

pub fn custody_events_decoder() -> decode.Decoder(CustodyEvents) {
  use seq <- decode.field(0, decode.int)
  use payload <- decode.field(1, decode.bit_array)
  decode.success(CustodyEvents(seq:, payload:))
}

pub fn append_custody_event(seq seq: Int, payload payload: BitArray) {
  let sql = "INSERT INTO custody_event (seq, payload) VALUES (?, ?)"
  #(sql, [dev.ParamInt(seq), dev.ParamBitArray(payload)])
}

pub type AdvanceCustodyHead {
  AdvanceCustodyHead(version: Int)
}

pub fn advance_custody_head(
  next_version next_version: Int,
  next_bytes next_bytes: Int,
  previous_version previous_version: Int,
  previous_bytes previous_bytes: Int,
) {
  let sql =
    "UPDATE custody_meta SET version = ?1, bytes = ?2
WHERE id = 1 AND version = ?3 AND bytes = ?4
RETURNING version"
  #(
    sql,
    [
      dev.ParamInt(next_version),
      dev.ParamInt(next_bytes),
      dev.ParamInt(previous_version),
      dev.ParamInt(previous_bytes),
    ],
    advance_custody_head_decoder(),
  )
}

pub fn advance_custody_head_decoder() -> decode.Decoder(AdvanceCustodyHead) {
  use version <- decode.field(0, decode.int)
  decode.success(AdvanceCustodyHead(version:))
}

pub type PayloadInventory {
  PayloadInventory(items: Int, bytes: Int)
}

pub fn payload_inventory(request request: BitArray, kind kind: Int) {
  let sql =
    "SELECT COUNT(*) AS items,
       CAST(COALESCE(SUM(length(body)), 0) AS INTEGER) AS bytes
FROM custody_payload WHERE request = ? AND kind = ?"
  #(
    sql,
    [dev.ParamBitArray(request), dev.ParamInt(kind)],
    payload_inventory_decoder(),
  )
}

pub fn payload_inventory_decoder() -> decode.Decoder(PayloadInventory) {
  use items <- decode.field(0, decode.int)
  use bytes <- decode.field(1, decode.int)
  decode.success(PayloadInventory(items:, bytes:))
}

pub type PayloadReservations {
  PayloadReservations(items: Int)
}

pub fn payload_reservations() {
  let sql =
    "SELECT COUNT(DISTINCT request) AS items FROM custody_payload WHERE kind IN (0, 4)"
  #(sql, [], payload_reservations_decoder())
}

pub fn payload_reservations_decoder() -> decode.Decoder(PayloadReservations) {
  use items <- decode.field(0, decode.int)
  decode.success(PayloadReservations(items:))
}

pub type ReadCustodyPayload {
  ReadCustodyPayload(digest: BitArray, kind: Int, ordinal: Int, body: BitArray)
}

pub fn read_custody_payload(request request: BitArray) {
  let sql =
    "SELECT CAST(CASE WHEN typeof(digest) = 'blob' AND length(digest) = 32
                 THEN digest ELSE NULL END AS BLOB) AS digest,
       CAST(CASE WHEN typeof(kind) = 'integer' AND kind BETWEEN 0 AND 4
                 THEN kind ELSE NULL END AS INTEGER) AS kind,
       CAST(CASE WHEN typeof(ordinal) = 'integer' AND ordinal BETWEEN 0 AND 63
                 THEN ordinal ELSE NULL END AS INTEGER) AS ordinal,
       CAST(CASE WHEN typeof(body) = 'blob'
                 AND length(body) <= CASE kind WHEN 0 THEN 131072 WHEN 1 THEN 1024
                   WHEN 2 THEN 16384 WHEN 3 THEN 32768 WHEN 4 THEN 32768 ELSE 0 END
                 THEN body ELSE NULL END AS BLOB) AS body
FROM custody_payload WHERE request = ? ORDER BY kind, ordinal LIMIT 69"
  #(sql, [dev.ParamBitArray(request)], read_custody_payload_decoder())
}

pub fn read_custody_payload_decoder() -> decode.Decoder(ReadCustodyPayload) {
  use digest <- decode.field(0, decode.bit_array)
  use kind <- decode.field(1, decode.int)
  use ordinal <- decode.field(2, decode.int)
  use body <- decode.field(3, decode.bit_array)
  decode.success(ReadCustodyPayload(digest:, kind:, ordinal:, body:))
}

pub fn insert_custody_payload(
  request request: BitArray,
  digest digest: BitArray,
  kind kind: Int,
  ordinal ordinal: Int,
  body body: BitArray,
) {
  let sql =
    "INSERT INTO custody_payload (request, digest, kind, ordinal, body) VALUES (?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamBitArray(request),
    dev.ParamBitArray(digest),
    dev.ParamInt(kind),
    dev.ParamInt(ordinal),
    dev.ParamBitArray(body),
  ])
}

pub fn initialize_resources(
  enrollment enrollment: BitArray,
  row_limit row_limit: Int,
  byte_limit byte_limit: Int,
) {
  let sql =
    "INSERT INTO resource_meta(id,format,mode,enrollment,row_limit,byte_limit)
VALUES(1,3,0,?,?,?)"
  #(sql, [
    dev.ParamBitArray(enrollment),
    dev.ParamInt(row_limit),
    dev.ParamInt(byte_limit),
  ])
}

pub type ResourceFormat {
  ResourceFormat(format: Int)
}

pub fn resource_format() {
  let sql =
    "SELECT CAST(CASE WHEN typeof(format)='integer' AND format BETWEEN 1 AND 3
                 THEN format ELSE NULL END AS INTEGER) AS format
FROM resource_meta WHERE id=1 LIMIT 2"
  #(sql, [], resource_format_decoder())
}

pub fn resource_format_decoder() -> decode.Decoder(ResourceFormat) {
  use format <- decode.field(0, decode.int)
  decode.success(ResourceFormat(format:))
}

pub type ResourceMetadata {
  ResourceMetadata(
    enrollment: BitArray,
    mode: Int,
    row_limit: Int,
    byte_limit: Int,
  )
}

pub fn resource_metadata() {
  let sql =
    "SELECT CAST(CASE WHEN typeof(id)='integer' AND id=1 AND typeof(format)='integer' AND format=3
                 AND typeof(enrollment)='blob' AND length(enrollment) BETWEEN 1 AND 262144
                 THEN enrollment ELSE NULL END AS BLOB) AS enrollment,
       CAST(CASE WHEN typeof(mode)='integer' AND mode IN (0,1) THEN mode ELSE NULL END AS INTEGER) AS mode,
       CAST(CASE WHEN typeof(row_limit)='integer' AND row_limit BETWEEN 1 AND 65536 THEN row_limit ELSE NULL END AS INTEGER) AS row_limit,
       CAST(CASE WHEN typeof(byte_limit)='integer' AND byte_limit>0 THEN byte_limit ELSE NULL END AS INTEGER) AS byte_limit
FROM resource_meta LIMIT 2"
  #(sql, [], resource_metadata_decoder())
}

pub fn resource_metadata_decoder() -> decode.Decoder(ResourceMetadata) {
  use enrollment <- decode.field(0, decode.bit_array)
  use mode <- decode.field(1, decode.int)
  use row_limit <- decode.field(2, decode.int)
  use byte_limit <- decode.field(3, decode.int)
  decode.success(ResourceMetadata(enrollment:, mode:, row_limit:, byte_limit:))
}

pub type ResourceHeaders {
  ResourceHeaders(
    id: BitArray,
    address_size: Int,
    header_size: Int,
    role: Int,
    input_digest: BitArray,
    input_size: Int,
    phase: Int,
    ready_digest: BitArray,
    ready_size: Int,
    native_id: BitArray,
    ref_size: Int,
    identity_size: Int,
    prepared_size: Int,
    completion_size: Int,
    completion_digest: BitArray,
    outer_receipt: Int,
    valid: Int,
  )
}

pub fn resource_headers(limit limit: Int) {
  let sql =
    "SELECT CAST(CASE WHEN typeof(id)='blob' AND length(id)=36 THEN id ELSE NULL END AS BLOB) AS id,
       CAST(CASE WHEN typeof(address)='blob' AND length(address) BETWEEN 1 AND 8192 THEN length(address) ELSE NULL END AS INTEGER) AS address_size,
       CAST(CASE WHEN typeof(service_header)='blob' AND length(service_header) BETWEEN 1 AND 8192 THEN length(service_header) ELSE NULL END AS INTEGER) AS header_size,
       CAST(CASE WHEN typeof(role)='integer' AND role IN (0,1) THEN role ELSE NULL END AS INTEGER) AS role,
       CAST(CASE WHEN typeof(input_digest)='blob' AND length(input_digest)=32 THEN input_digest ELSE NULL END AS BLOB) AS input_digest,
       CAST(CASE WHEN typeof(input_size)='integer' AND input_size BETWEEN 1 AND 9437184 THEN input_size ELSE NULL END AS INTEGER) AS input_size,
       CAST(CASE WHEN typeof(phase)='integer' AND phase BETWEEN 0 AND 4 THEN phase ELSE NULL END AS INTEGER) AS phase,
       CAST(CASE WHEN typeof(ready_digest)='blob' AND length(ready_digest) IN (0,32) THEN ready_digest ELSE NULL END AS BLOB) AS ready_digest,
       CAST(CASE WHEN typeof(ready_size)='integer' AND ready_size BETWEEN 0 AND 262144 THEN ready_size ELSE NULL END AS INTEGER) AS ready_size,
       CAST(CASE WHEN native_id IS NULL THEN X'' WHEN typeof(native_id)='blob' AND length(native_id)=36 THEN native_id ELSE NULL END AS BLOB) AS native_id,
       CAST(CASE WHEN typeof(command_ref)='blob' AND length(command_ref)<=8192 THEN length(command_ref) ELSE NULL END AS INTEGER) AS ref_size,
       CAST(CASE WHEN typeof(native_identity)='blob' AND length(native_identity) IN (0,106) THEN length(native_identity) ELSE NULL END AS INTEGER) AS identity_size,
       CAST(CASE WHEN typeof(native_prepared)='blob' AND length(native_prepared)<=131072 THEN length(native_prepared) ELSE NULL END AS INTEGER) AS prepared_size,
       CAST(CASE WHEN typeof(completion)='blob' AND length(completion)<=262144 THEN length(completion) ELSE NULL END AS INTEGER) AS completion_size,
       CAST(CASE WHEN typeof(completion_digest)='blob' AND length(completion_digest) IN (0,32) THEN completion_digest ELSE NULL END AS BLOB) AS completion_digest,
       CAST(CASE WHEN typeof(outer_receipt)='integer' AND outer_receipt IN (0,1) THEN outer_receipt ELSE NULL END AS INTEGER) AS outer_receipt,
       CAST(CASE WHEN typeof(input)='blob' AND length(input)=input_size
                 AND typeof(ready)='blob' AND length(ready)=ready_size
                 AND ((ready_size=0 AND length(ready_digest)=0 AND phase IN (0,1,3,4))
                   OR (ready_size>0 AND length(ready_digest)=32 AND phase IN (2,3,4)))
                 AND ((native_id IS NULL AND length(command_ref)=0 AND length(native_identity)=0 AND length(native_prepared)=0)
                   OR (native_id IS NOT NULL AND length(command_ref)>0 AND length(native_identity)=106 AND length(native_prepared)>0 AND ready_size>0))
                 AND ((length(completion)=0 AND length(completion_digest)=0 AND outer_receipt=0)
                   OR (length(completion)>0 AND length(completion_digest)=32 AND (native_id IS NOT NULL OR (phase IN (3,4) AND (ready_size=0 OR role=1)))))
                 THEN 1 ELSE 0 END AS INTEGER) AS valid
FROM resource_call ORDER BY id LIMIT ?"
  #(sql, [dev.ParamInt(limit)], resource_headers_decoder())
}

pub fn resource_headers_decoder() -> decode.Decoder(ResourceHeaders) {
  use id <- decode.field(0, decode.bit_array)
  use address_size <- decode.field(1, decode.int)
  use header_size <- decode.field(2, decode.int)
  use role <- decode.field(3, decode.int)
  use input_digest <- decode.field(4, decode.bit_array)
  use input_size <- decode.field(5, decode.int)
  use phase <- decode.field(6, decode.int)
  use ready_digest <- decode.field(7, decode.bit_array)
  use ready_size <- decode.field(8, decode.int)
  use native_id <- decode.field(9, decode.bit_array)
  use ref_size <- decode.field(10, decode.int)
  use identity_size <- decode.field(11, decode.int)
  use prepared_size <- decode.field(12, decode.int)
  use completion_size <- decode.field(13, decode.int)
  use completion_digest <- decode.field(14, decode.bit_array)
  use outer_receipt <- decode.field(15, decode.int)
  use valid <- decode.field(16, decode.int)
  decode.success(ResourceHeaders(
    id:,
    address_size:,
    header_size:,
    role:,
    input_digest:,
    input_size:,
    phase:,
    ready_digest:,
    ready_size:,
    native_id:,
    ref_size:,
    identity_size:,
    prepared_size:,
    completion_size:,
    completion_digest:,
    outer_receipt:,
    valid:,
  ))
}

pub type ResourceBodies {
  ResourceBodies(
    address: BitArray,
    service_header: BitArray,
    input: BitArray,
    ready: BitArray,
    command_ref: BitArray,
    native_identity: BitArray,
    native_prepared: BitArray,
    completion: BitArray,
  )
}

pub fn resource_bodies(id id: BitArray) {
  let sql =
    "SELECT CAST(CASE WHEN typeof(address)='blob' AND length(address) BETWEEN 1 AND 8192 THEN address ELSE NULL END AS BLOB) AS address,
       CAST(CASE WHEN typeof(service_header)='blob' AND length(service_header) BETWEEN 1 AND 8192 THEN service_header ELSE NULL END AS BLOB) AS service_header,
       CAST(CASE WHEN typeof(input)='blob' AND length(input) BETWEEN 1 AND 9437184 THEN input ELSE NULL END AS BLOB) AS input,
       CAST(CASE WHEN typeof(ready)='blob' AND length(ready)<=262144 THEN ready ELSE NULL END AS BLOB) AS ready,
       CAST(CASE WHEN typeof(command_ref)='blob' AND length(command_ref)<=8192 THEN command_ref ELSE NULL END AS BLOB) AS command_ref,
       CAST(CASE WHEN typeof(native_identity)='blob' AND length(native_identity) IN (0,106) THEN native_identity ELSE NULL END AS BLOB) AS native_identity,
       CAST(CASE WHEN typeof(native_prepared)='blob' AND length(native_prepared)<=131072 THEN native_prepared ELSE NULL END AS BLOB) AS native_prepared,
       CAST(CASE WHEN typeof(completion)='blob' AND length(completion)<=262144 THEN completion ELSE NULL END AS BLOB) AS completion
FROM resource_call WHERE id=? LIMIT 2"
  #(sql, [dev.ParamBitArray(id)], resource_bodies_decoder())
}

pub fn resource_bodies_decoder() -> decode.Decoder(ResourceBodies) {
  use address <- decode.field(0, decode.bit_array)
  use service_header <- decode.field(1, decode.bit_array)
  use input <- decode.field(2, decode.bit_array)
  use ready <- decode.field(3, decode.bit_array)
  use command_ref <- decode.field(4, decode.bit_array)
  use native_identity <- decode.field(5, decode.bit_array)
  use native_prepared <- decode.field(6, decode.bit_array)
  use completion <- decode.field(7, decode.bit_array)
  decode.success(ResourceBodies(
    address:,
    service_header:,
    input:,
    ready:,
    command_ref:,
    native_identity:,
    native_prepared:,
    completion:,
  ))
}

pub type InsertResource {
  InsertResource(id: BitArray)
}

pub fn insert_resource(
  id id: BitArray,
  address address: BitArray,
  service_header service_header: BitArray,
  role role: Int,
  input_digest input_digest: BitArray,
  input_size input_size: Int,
  input input: BitArray,
) {
  let sql =
    "INSERT INTO resource_call(id,address,service_header,role,input_digest,input_size,input,phase,ready_digest,ready_size,ready)
VALUES(?,?,?,?,?,?,?,0,X'',0,X'') RETURNING id"
  #(
    sql,
    [
      dev.ParamBitArray(id),
      dev.ParamBitArray(address),
      dev.ParamBitArray(service_header),
      dev.ParamInt(role),
      dev.ParamBitArray(input_digest),
      dev.ParamInt(input_size),
      dev.ParamBitArray(input),
    ],
    insert_resource_decoder(),
  )
}

pub fn insert_resource_decoder() -> decode.Decoder(InsertResource) {
  use id <- decode.field(0, decode.bit_array)
  decode.success(InsertResource(id:))
}

pub type ClaimResource {
  ClaimResource(phase: Int)
}

pub fn claim_resource(id id: BitArray) {
  let sql =
    "UPDATE resource_call SET phase=1 WHERE resource_call.id=? AND resource_call.phase=0
AND EXISTS(SELECT 1 FROM resource_meta WHERE resource_meta.id=1 AND resource_meta.mode=0) RETURNING phase"
  #(sql, [dev.ParamBitArray(id)], claim_resource_decoder())
}

pub fn claim_resource_decoder() -> decode.Decoder(ClaimResource) {
  use phase <- decode.field(0, decode.int)
  decode.success(ClaimResource(phase:))
}

pub type CommitResourceReady {
  CommitResourceReady(phase: Int)
}

pub fn commit_resource_ready(
  ready_digest ready_digest: BitArray,
  ready_size ready_size: Int,
  ready ready: BitArray,
  id id: BitArray,
) {
  let sql =
    "UPDATE resource_call SET phase=2,ready_digest=?,ready_size=?,ready=?
WHERE id=? AND phase=1 RETURNING phase"
  #(
    sql,
    [
      dev.ParamBitArray(ready_digest),
      dev.ParamInt(ready_size),
      dev.ParamBitArray(ready),
      dev.ParamBitArray(id),
    ],
    commit_resource_ready_decoder(),
  )
}

pub fn commit_resource_ready_decoder() -> decode.Decoder(CommitResourceReady) {
  use phase <- decode.field(0, decode.int)
  decode.success(CommitResourceReady(phase:))
}

pub type MarkResourceUnknown {
  MarkResourceUnknown(phase: Int)
}

pub fn mark_resource_unknown(id id: BitArray) {
  let sql =
    "UPDATE resource_call SET phase=3 WHERE id=? AND phase IN (1,2) RETURNING phase"
  #(sql, [dev.ParamBitArray(id)], mark_resource_unknown_decoder())
}

pub fn mark_resource_unknown_decoder() -> decode.Decoder(MarkResourceUnknown) {
  use phase <- decode.field(0, decode.int)
  decode.success(MarkResourceUnknown(phase:))
}

pub type FenceResourcePreparation {
  FenceResourcePreparation(phase: Int)
}

pub fn fence_resource_preparation(id id: BitArray) {
  let sql =
    "UPDATE resource_call SET phase=3 WHERE id=? AND phase IN (0,1,2) RETURNING phase"
  #(sql, [dev.ParamBitArray(id)], fence_resource_preparation_decoder())
}

pub fn fence_resource_preparation_decoder() -> decode.Decoder(
  FenceResourcePreparation,
) {
  use phase <- decode.field(0, decode.int)
  decode.success(FenceResourcePreparation(phase:))
}

pub type ReleaseResource {
  ReleaseResource(phase: Int)
}

pub fn release_resource(id id: BitArray) {
  let sql =
    "UPDATE resource_call SET phase=4 WHERE id=? AND phase IN (1,2,3) RETURNING phase"
  #(sql, [dev.ParamBitArray(id)], release_resource_decoder())
}

pub fn release_resource_decoder() -> decode.Decoder(ReleaseResource) {
  use phase <- decode.field(0, decode.int)
  decode.success(ReleaseResource(phase:))
}

pub type SealResources {
  SealResources(mode: Int)
}

pub fn seal_resources() {
  let sql = "UPDATE resource_meta SET mode=1 WHERE id=1 RETURNING mode"
  #(sql, [], seal_resources_decoder())
}

pub fn seal_resources_decoder() -> decode.Decoder(SealResources) {
  use mode <- decode.field(0, decode.int)
  decode.success(SealResources(mode:))
}

pub type ResourceAddress {
  ResourceAddress(id: BitArray)
}

pub fn resource_address(address address: BitArray) {
  let sql =
    "SELECT CAST(CASE WHEN typeof(id)='blob' AND length(id)=36 THEN id ELSE NULL END AS BLOB) AS id
FROM resource_call WHERE address=? LIMIT 2"
  #(sql, [dev.ParamBitArray(address)], resource_address_decoder())
}

pub fn resource_address_decoder() -> decode.Decoder(ResourceAddress) {
  use id <- decode.field(0, decode.bit_array)
  decode.success(ResourceAddress(id:))
}

pub type AssociateResourceNative {
  AssociateResourceNative(native_id: Option(BitArray))
}

pub fn associate_resource_native(
  command_ref command_ref: BitArray,
  native_id native_id: Option(BitArray),
  native_identity native_identity: BitArray,
  native_prepared native_prepared: BitArray,
  id id: BitArray,
) {
  let sql =
    "UPDATE resource_call SET command_ref=?,native_id=?,native_identity=?,native_prepared=?
WHERE id=? AND native_id IS NULL AND ready_size>0 AND length(completion)=0 RETURNING native_id"
  #(
    sql,
    [
      dev.ParamBitArray(command_ref),
      dev.ParamNullable(option.map(native_id, fn(v) { dev.ParamBitArray(v) })),
      dev.ParamBitArray(native_identity),
      dev.ParamBitArray(native_prepared),
      dev.ParamBitArray(id),
    ],
    associate_resource_native_decoder(),
  )
}

pub fn associate_resource_native_decoder() -> decode.Decoder(
  AssociateResourceNative,
) {
  use native_id <- decode.field(0, decode.optional(decode.bit_array))
  decode.success(AssociateResourceNative(native_id:))
}

pub type ResourceNativeOwner {
  ResourceNativeOwner(id: BitArray)
}

pub fn resource_native_owner(native_id native_id: Option(BitArray)) {
  let sql =
    "SELECT CAST(CASE WHEN typeof(id)='blob' AND length(id)=36 THEN id ELSE NULL END AS BLOB) AS id
FROM resource_call WHERE native_id=? LIMIT 2"
  #(
    sql,
    [dev.ParamNullable(option.map(native_id, fn(v) { dev.ParamBitArray(v) }))],
    resource_native_owner_decoder(),
  )
}

pub fn resource_native_owner_decoder() -> decode.Decoder(ResourceNativeOwner) {
  use id <- decode.field(0, decode.bit_array)
  decode.success(ResourceNativeOwner(id:))
}

pub type CommitResourceCompile {
  CommitResourceCompile(completion_digest: BitArray)
}

pub fn commit_resource_compile(
  completion_digest completion_digest: BitArray,
  completion completion: BitArray,
  id id: BitArray,
) {
  let sql =
    "UPDATE resource_call SET completion_digest=?,completion=?
WHERE id=? AND native_id IS NOT NULL AND length(completion)=0 RETURNING completion_digest"
  #(
    sql,
    [
      dev.ParamBitArray(completion_digest),
      dev.ParamBitArray(completion),
      dev.ParamBitArray(id),
    ],
    commit_resource_compile_decoder(),
  )
}

pub fn commit_resource_compile_decoder() -> decode.Decoder(
  CommitResourceCompile,
) {
  use completion_digest <- decode.field(0, decode.bit_array)
  decode.success(CommitResourceCompile(completion_digest:))
}

pub type FailResourcePreparation {
  FailResourcePreparation(completion_digest: BitArray)
}

pub fn fail_resource_preparation(
  completion_digest completion_digest: BitArray,
  completion completion: BitArray,
  id id: BitArray,
) {
  let sql =
    "UPDATE resource_call SET phase=3,completion_digest=?,completion=?
WHERE id=? AND native_id IS NULL AND length(completion)=0
AND ((role=0 AND phase=1 AND ready_size=0) OR (role=1 AND phase IN (1,2))) RETURNING completion_digest"
  #(
    sql,
    [
      dev.ParamBitArray(completion_digest),
      dev.ParamBitArray(completion),
      dev.ParamBitArray(id),
    ],
    fail_resource_preparation_decoder(),
  )
}

pub fn fail_resource_preparation_decoder() -> decode.Decoder(
  FailResourcePreparation,
) {
  use completion_digest <- decode.field(0, decode.bit_array)
  decode.success(FailResourcePreparation(completion_digest:))
}

pub type AcknowledgeResourceCompile {
  AcknowledgeResourceCompile(outer_receipt: Int)
}

pub fn acknowledge_resource_compile(
  id id: BitArray,
  completion_digest completion_digest: BitArray,
) {
  let sql =
    "UPDATE resource_call SET outer_receipt=1
WHERE id=? AND completion_digest=? AND length(completion)>0 AND outer_receipt=0 RETURNING outer_receipt"
  #(
    sql,
    [dev.ParamBitArray(id), dev.ParamBitArray(completion_digest)],
    acknowledge_resource_compile_decoder(),
  )
}

pub fn acknowledge_resource_compile_decoder() -> decode.Decoder(
  AcknowledgeResourceCompile,
) {
  use outer_receipt <- decode.field(0, decode.int)
  decode.success(AcknowledgeResourceCompile(outer_receipt:))
}

pub fn initialize_workspace(
  binding binding: BitArray,
  row_limit row_limit: Int,
  byte_limit byte_limit: Int,
) {
  let sql =
    "INSERT INTO workspace_meta(id, format, mode, binding, row_limit, byte_limit) VALUES(1, 2, 0, ?, ?, ?)"
  #(sql, [
    dev.ParamBitArray(binding),
    dev.ParamInt(row_limit),
    dev.ParamInt(byte_limit),
  ])
}

pub type WorkspaceMetadata {
  WorkspaceMetadata(
    binding: BitArray,
    mode: Int,
    row_limit: Int,
    byte_limit: Int,
  )
}

pub fn workspace_metadata() {
  let sql =
    "SELECT CAST(CASE WHEN typeof(id)='integer' AND id=1 AND typeof(format)='integer' AND format=2 AND typeof(binding)='blob' AND length(binding)<=303 THEN binding ELSE NULL END AS BLOB) AS binding,
       CAST(CASE WHEN typeof(mode)='integer' AND mode IN (0,1) THEN mode ELSE NULL END AS INTEGER) AS mode,
       CAST(CASE WHEN typeof(row_limit)='integer' THEN row_limit ELSE NULL END AS INTEGER) AS row_limit,
       CAST(CASE WHEN typeof(byte_limit)='integer' THEN byte_limit ELSE NULL END AS INTEGER) AS byte_limit
FROM workspace_meta LIMIT 2"
  #(sql, [], workspace_metadata_decoder())
}

pub fn workspace_metadata_decoder() -> decode.Decoder(WorkspaceMetadata) {
  use binding <- decode.field(0, decode.bit_array)
  use mode <- decode.field(1, decode.int)
  use row_limit <- decode.field(2, decode.int)
  use byte_limit <- decode.field(3, decode.int)
  decode.success(WorkspaceMetadata(binding:, mode:, row_limit:, byte_limit:))
}

pub type WorkspaceHeaders {
  WorkspaceHeaders(
    id: BitArray,
    request_digest: BitArray,
    request_size: Int,
    phase: Int,
    result_digest: BitArray,
    result_size: Int,
    valid: Int,
  )
}

pub fn workspace_headers(limit limit: Int) {
  let sql =
    "SELECT CAST(CASE WHEN typeof(id)='blob' AND length(id)=36 THEN id ELSE NULL END AS BLOB) AS id,
       CAST(CASE WHEN typeof(request_digest)='blob' AND length(request_digest)=32 THEN request_digest ELSE NULL END AS BLOB) AS request_digest,
       CAST(CASE WHEN typeof(request_size)='integer' AND request_size BETWEEN 1 AND 9437184 THEN request_size ELSE NULL END AS INTEGER) AS request_size,
       CAST(CASE WHEN typeof(phase)='integer' AND phase BETWEEN 0 AND 4 THEN phase ELSE NULL END AS INTEGER) AS phase,
       CAST(CASE WHEN typeof(result_digest)='blob' AND length(result_digest) IN (0,32) THEN result_digest ELSE NULL END AS BLOB) AS result_digest,
       CAST(CASE WHEN typeof(result_size)='integer' AND result_size BETWEEN 0 AND 33554432 THEN result_size ELSE NULL END AS INTEGER) AS result_size,
       CAST(CASE WHEN typeof(request)='blob' AND typeof(result)='blob'
         AND ((phase IN (0,1,4) AND length(request)=request_size AND length(result)=0 AND result_size=0 AND length(result_digest)=0)
           OR (phase=2 AND length(request)=request_size AND length(result)=result_size AND result_size>0 AND length(result_digest)=32)
           OR (phase=3 AND length(request)=0 AND length(result)=0 AND result_size>0 AND length(result_digest)=32))
         THEN 1 ELSE 0 END AS INTEGER) AS valid
FROM workspace_call ORDER BY id LIMIT ?"
  #(sql, [dev.ParamInt(limit)], workspace_headers_decoder())
}

pub fn workspace_headers_decoder() -> decode.Decoder(WorkspaceHeaders) {
  use id <- decode.field(0, decode.bit_array)
  use request_digest <- decode.field(1, decode.bit_array)
  use request_size <- decode.field(2, decode.int)
  use phase <- decode.field(3, decode.int)
  use result_digest <- decode.field(4, decode.bit_array)
  use result_size <- decode.field(5, decode.int)
  use valid <- decode.field(6, decode.int)
  decode.success(WorkspaceHeaders(
    id:,
    request_digest:,
    request_size:,
    phase:,
    result_digest:,
    result_size:,
    valid:,
  ))
}

pub type WorkspaceBodies {
  WorkspaceBodies(request: BitArray, result: BitArray)
}

pub fn workspace_bodies(id id: BitArray) {
  let sql =
    "SELECT CAST(CASE WHEN typeof(request)='blob' AND length(request)<=9437184 THEN request ELSE NULL END AS BLOB) AS request,
       CAST(CASE WHEN typeof(result)='blob' AND length(result)<=33554432 THEN result ELSE NULL END AS BLOB) AS result
FROM workspace_call WHERE id=? LIMIT 2"
  #(sql, [dev.ParamBitArray(id)], workspace_bodies_decoder())
}

pub fn workspace_bodies_decoder() -> decode.Decoder(WorkspaceBodies) {
  use request <- decode.field(0, decode.bit_array)
  use result <- decode.field(1, decode.bit_array)
  decode.success(WorkspaceBodies(request:, result:))
}

pub fn insert_workspace(
  id id: BitArray,
  request_digest request_digest: BitArray,
  request_size request_size: Int,
  request request: BitArray,
) {
  let sql =
    "INSERT INTO workspace_call(id,request_digest,request_size,phase,request,result_digest,result_size,result)
VALUES(?,?,?,0,?,X'',0,X'')"
  #(sql, [
    dev.ParamBitArray(id),
    dev.ParamBitArray(request_digest),
    dev.ParamInt(request_size),
    dev.ParamBitArray(request),
  ])
}

pub type ClaimWorkspace {
  ClaimWorkspace(phase: Int)
}

pub fn claim_workspace(id id: BitArray) {
  let sql =
    "UPDATE workspace_call SET phase=1 WHERE id=? AND phase=0 RETURNING phase"
  #(sql, [dev.ParamBitArray(id)], claim_workspace_decoder())
}

pub fn claim_workspace_decoder() -> decode.Decoder(ClaimWorkspace) {
  use phase <- decode.field(0, decode.int)
  decode.success(ClaimWorkspace(phase:))
}

pub type FinishWorkspace {
  FinishWorkspace(phase: Int)
}

pub fn finish_workspace(
  result_digest result_digest: BitArray,
  result_size result_size: Int,
  result result: BitArray,
  id id: BitArray,
) {
  let sql =
    "UPDATE workspace_call SET phase=2,result_digest=?,result_size=?,result=? WHERE id=? AND phase=1 RETURNING phase"
  #(
    sql,
    [
      dev.ParamBitArray(result_digest),
      dev.ParamInt(result_size),
      dev.ParamBitArray(result),
      dev.ParamBitArray(id),
    ],
    finish_workspace_decoder(),
  )
}

pub fn finish_workspace_decoder() -> decode.Decoder(FinishWorkspace) {
  use phase <- decode.field(0, decode.int)
  decode.success(FinishWorkspace(phase:))
}

pub type AcknowledgeWorkspace {
  AcknowledgeWorkspace(phase: Int)
}

pub fn acknowledge_workspace(id id: BitArray) {
  let sql =
    "UPDATE workspace_call SET phase=3,request=X'',result=X'' WHERE id=? AND phase=2 RETURNING phase"
  #(sql, [dev.ParamBitArray(id)], acknowledge_workspace_decoder())
}

pub fn acknowledge_workspace_decoder() -> decode.Decoder(AcknowledgeWorkspace) {
  use phase <- decode.field(0, decode.int)
  decode.success(AcknowledgeWorkspace(phase:))
}

pub type CancelWorkspace {
  CancelWorkspace(phase: Int)
}

pub fn cancel_workspace(id id: BitArray) {
  let sql =
    "UPDATE workspace_call SET phase=4 WHERE id=? AND phase=0 RETURNING phase"
  #(sql, [dev.ParamBitArray(id)], cancel_workspace_decoder())
}

pub fn cancel_workspace_decoder() -> decode.Decoder(CancelWorkspace) {
  use phase <- decode.field(0, decode.int)
  decode.success(CancelWorkspace(phase:))
}

pub type SealWorkspace {
  SealWorkspace(mode: Int)
}

pub fn seal_workspace() {
  let sql = "UPDATE workspace_meta SET mode=1 WHERE id=1 RETURNING mode"
  #(sql, [], seal_workspace_decoder())
}

pub fn seal_workspace_decoder() -> decode.Decoder(SealWorkspace) {
  use mode <- decode.field(0, decode.int)
  decode.success(SealWorkspace(mode:))
}
