//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import parrot/dev

pub fn initialize_custody(binding binding: BitArray, capacity capacity: Int) {
  let sql =
    "
INSERT INTO custody_meta (id, binding, capacity, version, bytes)
VALUES (1, ?, ?, 0, 0)"
  #(sql, [dev.ParamBitArray(binding), dev.ParamInt(capacity)])
}

pub type CustodyMetadata {
  CustodyMetadata(binding: BitArray, capacity: Int, version: Int, bytes: Int)
}

pub fn custody_metadata() {
  let sql =
    "SELECT CAST(CASE WHEN typeof(binding) = 'blob' AND length(binding) <= 303
                 THEN binding ELSE NULL END AS BLOB) AS binding,
       CAST(CASE WHEN typeof(capacity) = 'integer'
                 THEN capacity ELSE NULL END AS INTEGER) AS capacity,
       CAST(CASE WHEN typeof(version) = 'integer'
                 THEN version ELSE NULL END AS INTEGER) AS version,
       CAST(CASE WHEN typeof(bytes) = 'integer'
                 THEN bytes ELSE NULL END AS INTEGER) AS bytes
FROM custody_meta LIMIT 2"
  #(sql, [], custody_metadata_decoder())
}

pub fn custody_metadata_decoder() -> decode.Decoder(CustodyMetadata) {
  use binding <- decode.field(0, decode.bit_array)
  use capacity <- decode.field(1, decode.int)
  use version <- decode.field(2, decode.int)
  use bytes <- decode.field(3, decode.int)
  decode.success(CustodyMetadata(binding:, capacity:, version:, bytes:))
}

pub type CustodyEvents {
  CustodyEvents(seq: Int, payload: BitArray)
}

pub fn custody_events(limit limit: Int) {
  let sql =
    "SELECT seq,
       CAST(CASE WHEN typeof(payload) = 'blob' AND length(payload) <= 138
                 THEN payload ELSE NULL END AS BLOB) AS payload
FROM custody_event ORDER BY seq LIMIT ?"
  #(sql, [dev.ParamInt(limit)], custody_events_decoder())
}

pub fn custody_events_decoder() -> decode.Decoder(CustodyEvents) {
  use seq <- decode.field(0, decode.int)
  use payload <- decode.field(1, decode.bit_array)
  decode.success(CustodyEvents(seq:, payload:))
}

pub fn append_custody_event(seq seq: Int, payload payload: BitArray) {
  let sql = "INSERT INTO custody_event (seq, payload) VALUES (?, ?)"
  #(sql, [dev.ParamInt(seq), dev.ParamBitArray(payload)])
}

pub type AdvanceCustodyHead {
  AdvanceCustodyHead(version: Int)
}

pub fn advance_custody_head(
  next_version next_version: Int,
  next_bytes next_bytes: Int,
  previous_version previous_version: Int,
  previous_bytes previous_bytes: Int,
) {
  let sql =
    "UPDATE custody_meta SET version = ?1, bytes = ?2
WHERE id = 1 AND version = ?3 AND bytes = ?4
RETURNING version"
  #(
    sql,
    [
      dev.ParamInt(next_version),
      dev.ParamInt(next_bytes),
      dev.ParamInt(previous_version),
      dev.ParamInt(previous_bytes),
    ],
    advance_custody_head_decoder(),
  )
}

pub fn advance_custody_head_decoder() -> decode.Decoder(AdvanceCustodyHead) {
  use version <- decode.field(0, decode.int)
  decode.success(AdvanceCustodyHead(version:))
}

pub type PayloadInventory {
  PayloadInventory(items: Int, bytes: Int)
}

pub fn payload_inventory(request request: BitArray, kind kind: Int) {
  let sql =
    "SELECT COUNT(*) AS items,
       CAST(COALESCE(SUM(length(body)), 0) AS INTEGER) AS bytes
FROM custody_payload WHERE request = ? AND kind = ?"
  #(
    sql,
    [dev.ParamBitArray(request), dev.ParamInt(kind)],
    payload_inventory_decoder(),
  )
}

pub fn payload_inventory_decoder() -> decode.Decoder(PayloadInventory) {
  use items <- decode.field(0, decode.int)
  use bytes <- decode.field(1, decode.int)
  decode.success(PayloadInventory(items:, bytes:))
}

pub type PayloadReservations {
  PayloadReservations(items: Int)
}

pub fn payload_reservations() {
  let sql =
    "SELECT COUNT(DISTINCT request) AS items FROM custody_payload WHERE kind IN (0, 4)"
  #(sql, [], payload_reservations_decoder())
}

pub fn payload_reservations_decoder() -> decode.Decoder(PayloadReservations) {
  use items <- decode.field(0, decode.int)
  decode.success(PayloadReservations(items:))
}

pub type ReadCustodyPayload {
  ReadCustodyPayload(digest: BitArray, kind: Int, ordinal: Int, body: BitArray)
}

pub fn read_custody_payload(request request: BitArray) {
  let sql =
    "SELECT CAST(CASE WHEN typeof(digest) = 'blob' AND length(digest) = 32
                 THEN digest ELSE NULL END AS BLOB) AS digest,
       CAST(CASE WHEN typeof(kind) = 'integer' AND kind BETWEEN 0 AND 4
                 THEN kind ELSE NULL END AS INTEGER) AS kind,
       CAST(CASE WHEN typeof(ordinal) = 'integer' AND ordinal BETWEEN 0 AND 63
                 THEN ordinal ELSE NULL END AS INTEGER) AS ordinal,
       CAST(CASE WHEN typeof(body) = 'blob'
                 AND length(body) <= CASE kind WHEN 0 THEN 131072 WHEN 1 THEN 1024
                   WHEN 2 THEN 16384 WHEN 3 THEN 32768 WHEN 4 THEN 32768 ELSE 0 END
                 THEN body ELSE NULL END AS BLOB) AS body
FROM custody_payload WHERE request = ? ORDER BY kind, ordinal LIMIT 69"
  #(sql, [dev.ParamBitArray(request)], read_custody_payload_decoder())
}

pub fn read_custody_payload_decoder() -> decode.Decoder(ReadCustodyPayload) {
  use digest <- decode.field(0, decode.bit_array)
  use kind <- decode.field(1, decode.int)
  use ordinal <- decode.field(2, decode.int)
  use body <- decode.field(3, decode.bit_array)
  decode.success(ReadCustodyPayload(digest:, kind:, ordinal:, body:))
}

pub fn insert_custody_payload(
  request request: BitArray,
  digest digest: BitArray,
  kind kind: Int,
  ordinal ordinal: Int,
  body body: BitArray,
) {
  let sql =
    "INSERT INTO custody_payload (request, digest, kind, ordinal, body) VALUES (?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamBitArray(request),
    dev.ParamBitArray(digest),
    dev.ParamInt(kind),
    dev.ParamInt(ordinal),
    dev.ParamBitArray(body),
  ])
}

pub fn initialize_workspace(
  binding binding: BitArray,
  row_limit row_limit: Int,
  byte_limit byte_limit: Int,
) {
  let sql =
    "INSERT INTO workspace_meta(id, format, mode, binding, row_limit, byte_limit) VALUES(1, 2, 0, ?, ?, ?)"
  #(sql, [
    dev.ParamBitArray(binding),
    dev.ParamInt(row_limit),
    dev.ParamInt(byte_limit),
  ])
}

pub type WorkspaceMetadata {
  WorkspaceMetadata(
    binding: BitArray,
    mode: Int,
    row_limit: Int,
    byte_limit: Int,
  )
}

pub fn workspace_metadata() {
  let sql =
    "SELECT CAST(CASE WHEN typeof(id)='integer' AND id=1 AND typeof(format)='integer' AND format=2 AND typeof(binding)='blob' AND length(binding)<=303 THEN binding ELSE NULL END AS BLOB) AS binding,
       CAST(CASE WHEN typeof(mode)='integer' AND mode IN (0,1) THEN mode ELSE NULL END AS INTEGER) AS mode,
       CAST(CASE WHEN typeof(row_limit)='integer' THEN row_limit ELSE NULL END AS INTEGER) AS row_limit,
       CAST(CASE WHEN typeof(byte_limit)='integer' THEN byte_limit ELSE NULL END AS INTEGER) AS byte_limit
FROM workspace_meta LIMIT 2"
  #(sql, [], workspace_metadata_decoder())
}

pub fn workspace_metadata_decoder() -> decode.Decoder(WorkspaceMetadata) {
  use binding <- decode.field(0, decode.bit_array)
  use mode <- decode.field(1, decode.int)
  use row_limit <- decode.field(2, decode.int)
  use byte_limit <- decode.field(3, decode.int)
  decode.success(WorkspaceMetadata(binding:, mode:, row_limit:, byte_limit:))
}

pub type WorkspaceHeaders {
  WorkspaceHeaders(
    id: BitArray,
    request_digest: BitArray,
    request_size: Int,
    phase: Int,
    result_digest: BitArray,
    result_size: Int,
    valid: Int,
  )
}

pub fn workspace_headers(limit limit: Int) {
  let sql =
    "SELECT CAST(CASE WHEN typeof(id)='blob' AND length(id)=36 THEN id ELSE NULL END AS BLOB) AS id,
       CAST(CASE WHEN typeof(request_digest)='blob' AND length(request_digest)=32 THEN request_digest ELSE NULL END AS BLOB) AS request_digest,
       CAST(CASE WHEN typeof(request_size)='integer' AND request_size BETWEEN 1 AND 9437184 THEN request_size ELSE NULL END AS INTEGER) AS request_size,
       CAST(CASE WHEN typeof(phase)='integer' AND phase BETWEEN 0 AND 4 THEN phase ELSE NULL END AS INTEGER) AS phase,
       CAST(CASE WHEN typeof(result_digest)='blob' AND length(result_digest) IN (0,32) THEN result_digest ELSE NULL END AS BLOB) AS result_digest,
       CAST(CASE WHEN typeof(result_size)='integer' AND result_size BETWEEN 0 AND 33554432 THEN result_size ELSE NULL END AS INTEGER) AS result_size,
       CAST(CASE WHEN typeof(request)='blob' AND typeof(result)='blob'
         AND ((phase IN (0,1,4) AND length(request)=request_size AND length(result)=0 AND result_size=0 AND length(result_digest)=0)
           OR (phase=2 AND length(request)=request_size AND length(result)=result_size AND result_size>0 AND length(result_digest)=32)
           OR (phase=3 AND length(request)=0 AND length(result)=0 AND result_size>0 AND length(result_digest)=32))
         THEN 1 ELSE 0 END AS INTEGER) AS valid
FROM workspace_call ORDER BY id LIMIT ?"
  #(sql, [dev.ParamInt(limit)], workspace_headers_decoder())
}

pub fn workspace_headers_decoder() -> decode.Decoder(WorkspaceHeaders) {
  use id <- decode.field(0, decode.bit_array)
  use request_digest <- decode.field(1, decode.bit_array)
  use request_size <- decode.field(2, decode.int)
  use phase <- decode.field(3, decode.int)
  use result_digest <- decode.field(4, decode.bit_array)
  use result_size <- decode.field(5, decode.int)
  use valid <- decode.field(6, decode.int)
  decode.success(WorkspaceHeaders(
    id:,
    request_digest:,
    request_size:,
    phase:,
    result_digest:,
    result_size:,
    valid:,
  ))
}

pub type WorkspaceBodies {
  WorkspaceBodies(request: BitArray, result: BitArray)
}

pub fn workspace_bodies(id id: BitArray) {
  let sql =
    "SELECT CAST(CASE WHEN typeof(request)='blob' AND length(request)<=9437184 THEN request ELSE NULL END AS BLOB) AS request,
       CAST(CASE WHEN typeof(result)='blob' AND length(result)<=33554432 THEN result ELSE NULL END AS BLOB) AS result
FROM workspace_call WHERE id=? LIMIT 2"
  #(sql, [dev.ParamBitArray(id)], workspace_bodies_decoder())
}

pub fn workspace_bodies_decoder() -> decode.Decoder(WorkspaceBodies) {
  use request <- decode.field(0, decode.bit_array)
  use result <- decode.field(1, decode.bit_array)
  decode.success(WorkspaceBodies(request:, result:))
}

pub fn insert_workspace(
  id id: BitArray,
  request_digest request_digest: BitArray,
  request_size request_size: Int,
  request request: BitArray,
) {
  let sql =
    "INSERT INTO workspace_call(id,request_digest,request_size,phase,request,result_digest,result_size,result)
VALUES(?,?,?,0,?,X'',0,X'')"
  #(sql, [
    dev.ParamBitArray(id),
    dev.ParamBitArray(request_digest),
    dev.ParamInt(request_size),
    dev.ParamBitArray(request),
  ])
}

pub type ClaimWorkspace {
  ClaimWorkspace(phase: Int)
}

pub fn claim_workspace(id id: BitArray) {
  let sql =
    "UPDATE workspace_call SET phase=1 WHERE id=? AND phase=0 RETURNING phase"
  #(sql, [dev.ParamBitArray(id)], claim_workspace_decoder())
}

pub fn claim_workspace_decoder() -> decode.Decoder(ClaimWorkspace) {
  use phase <- decode.field(0, decode.int)
  decode.success(ClaimWorkspace(phase:))
}

pub type FinishWorkspace {
  FinishWorkspace(phase: Int)
}

pub fn finish_workspace(
  result_digest result_digest: BitArray,
  result_size result_size: Int,
  result result: BitArray,
  id id: BitArray,
) {
  let sql =
    "UPDATE workspace_call SET phase=2,result_digest=?,result_size=?,result=? WHERE id=? AND phase=1 RETURNING phase"
  #(
    sql,
    [
      dev.ParamBitArray(result_digest),
      dev.ParamInt(result_size),
      dev.ParamBitArray(result),
      dev.ParamBitArray(id),
    ],
    finish_workspace_decoder(),
  )
}

pub fn finish_workspace_decoder() -> decode.Decoder(FinishWorkspace) {
  use phase <- decode.field(0, decode.int)
  decode.success(FinishWorkspace(phase:))
}

pub type AcknowledgeWorkspace {
  AcknowledgeWorkspace(phase: Int)
}

pub fn acknowledge_workspace(id id: BitArray) {
  let sql =
    "UPDATE workspace_call SET phase=3,request=X'',result=X'' WHERE id=? AND phase=2 RETURNING phase"
  #(sql, [dev.ParamBitArray(id)], acknowledge_workspace_decoder())
}

pub fn acknowledge_workspace_decoder() -> decode.Decoder(AcknowledgeWorkspace) {
  use phase <- decode.field(0, decode.int)
  decode.success(AcknowledgeWorkspace(phase:))
}

pub type CancelWorkspace {
  CancelWorkspace(phase: Int)
}

pub fn cancel_workspace(id id: BitArray) {
  let sql =
    "UPDATE workspace_call SET phase=4 WHERE id=? AND phase=0 RETURNING phase"
  #(sql, [dev.ParamBitArray(id)], cancel_workspace_decoder())
}

pub fn cancel_workspace_decoder() -> decode.Decoder(CancelWorkspace) {
  use phase <- decode.field(0, decode.int)
  decode.success(CancelWorkspace(phase:))
}

pub type SealWorkspace {
  SealWorkspace(mode: Int)
}

pub fn seal_workspace() {
  let sql = "UPDATE workspace_meta SET mode=1 WHERE id=1 RETURNING mode"
  #(sql, [], seal_workspace_decoder())
}

pub fn seal_workspace_decoder() -> decode.Decoder(SealWorkspace) {
  use mode <- decode.field(0, decode.int)
  decode.success(SealWorkspace(mode:))
}
