//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.
//// The checked-in SQL file is the schema source of truth.

/// The schema used both at runtime and by sqlc during generation.
pub const schema =
  "-- Resolved workspace authority is retained before any session startup.\nALTER TABLE catalogue_sessions ADD COLUMN workspace_binding TEXT NULL;\n"
