//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.
//// The checked-in SQL file is the schema source of truth.

/// The schema used both at runtime and by sqlc during generation.
pub const schema =
  "-- Catalogue v7: a login's own expiry, and the fingerprint of the login whose device link made it.\nALTER TABLE access_credentials ADD COLUMN expires_at_ms INTEGER;\nALTER TABLE access_credentials ADD COLUMN issued_by TEXT\n  CHECK(issued_by IS NULL OR (length(issued_by) = 16 AND issued_by NOT GLOB '*[^0-9a-f]*'));\n"
