//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.
//// The checked-in SQL file is the schema source of truth.

/// The schema used both at runtime and by sqlc during generation.
pub const schema =
  "-- Catalogue v13: where a session is going to or came from. A session with no\n-- row is served by this catalogue and has never moved. A row is 'moving' while\n-- this side hands the session to the peer, 'moved' once it has (a tombstone with\n-- no way out), or 'imported' on the side that received it. The op identifies one\n-- move end to end, so a repeated step of the same op is recognized.\nCREATE TABLE catalogue_session_moves(\n  session_id TEXT NOT NULL PRIMARY KEY REFERENCES catalogue_sessions(session_id),\n  op TEXT NOT NULL CHECK(length(CAST(op AS BLOB)) BETWEEN 1 AND 64),\n  peer TEXT NOT NULL CHECK(length(CAST(peer AS BLOB)) BETWEEN 1 AND 64),\n  state TEXT NOT NULL CHECK(state IN ('moving', 'moved', 'imported'))\n);\n"
