//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.
//// The checked-in SQL file is the schema source of truth.

/// The schema used both at runtime and by sqlc during generation.
pub const schema =
  "-- Catalogue v4: single-use claim tokens, stored only as digests, that bind one credential.\nCREATE TABLE access_claims(\n  digest TEXT NOT NULL PRIMARY KEY\n    CHECK(length(digest) = 64 AND digest NOT GLOB '*[^0-9a-f]*'),\n  principal_id TEXT NOT NULL REFERENCES access_principals(principal_id),\n  expires_at_ms INTEGER NOT NULL,\n  state TEXT NOT NULL CHECK(state IN ('open', 'claimed', 'void')),\n  credential_digest TEXT REFERENCES access_credentials(digest),\n  claimed_at_ms INTEGER,\n  CHECK((state = 'claimed') = (credential_digest IS NOT NULL)),\n  CHECK((state = 'claimed') = (claimed_at_ms IS NOT NULL)),\n  CHECK(credential_digest IS NULL OR credential_digest != digest)\n);\nCREATE UNIQUE INDEX access_one_open_claim\n  ON access_claims(principal_id) WHERE state = 'open';\n"
