//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.
//// The checked-in SQL file is the schema source of truth.

/// The schema used both at runtime and by sqlc during generation.
pub const schema = "-- Catalogue v2: display labels do not replace immutable creation metadata.\nCREATE TABLE catalogue_session_names(\n  session_id TEXT NOT NULL PRIMARY KEY REFERENCES catalogue_sessions(session_id),\n  name TEXT NOT NULL CHECK(length(CAST(name AS BLOB)) BETWEEN 1 AND 256)\n);\n"
