//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.
//// The checked-in SQL file is the schema source of truth.

/// The schema used both at runtime and by sqlc during generation.
pub const schema = "-- Catalogue v4: a session's tool roster is creation metadata, not a label.\n-- The empty word means the session inherits the daemon's configured default,\n-- which is what every registration written before this column said.\nALTER TABLE catalogue_sessions\n  ADD COLUMN roster TEXT NOT NULL DEFAULT '' CHECK(roster IN ('', 'minimal', 'full'));\n"
