//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.
//// The checked-in SQL file is the schema source of truth.

/// The schema used both at runtime and by sqlc during generation.
pub const schema =
  "-- Catalogue v9: the model profile a session was created with, empty for none.\nALTER TABLE catalogue_sessions ADD COLUMN profile TEXT NOT NULL DEFAULT ''\n  CHECK(length(CAST(profile AS BLOB)) <= 64);\n"
