//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.
//// The checked-in SQL file is the schema source of truth.

/// The schema used both at runtime and by sqlc during generation.
pub const schema =
  "-- Catalogue v5: a session's subtitle is written once and never replaced.\nCREATE TABLE catalogue_session_subtitles(\n  session_id TEXT NOT NULL PRIMARY KEY REFERENCES catalogue_sessions(session_id),\n  subtitle TEXT NOT NULL CHECK(length(subtitle) BETWEEN 1 AND 60)\n);\n"
