//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.
//// The checked-in SQL file is the schema source of truth.

/// The schema used both at runtime and by sqlc during generation.
pub const schema =
  "-- Catalogue v8: the folders the owner recently started a session in, newest last.\nCREATE TABLE catalogue_recent_folders(\n  seq INTEGER PRIMARY KEY AUTOINCREMENT,\n  workspace TEXT NOT NULL UNIQUE\n    CHECK(length(CAST(workspace AS BLOB)) BETWEEN 1 AND 4096)\n);\n"
