//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.
//// The checked-in SQL file is the schema source of truth.

/// The schema used both at runtime and by sqlc during generation.
pub const schema =
  "-- Catalogue v13: a remote session whose deletion has begun on a daemon that\n-- is a member of the session directory (protocol-change/079). The row is\n-- written in the registry turn that checks no slot is open, before the\n-- directory record is deleted, and admission refuses a session that has one.\n-- It is removed with the registration once the record is gone, or on its own\n-- when the record turns out to belong to someone else. Its presence is what\n-- lets a restarted daemon finish a deletion: an absent record alone never\n-- deletes anything.\nCREATE TABLE catalogue_session_deletions(\n  session_id TEXT NOT NULL PRIMARY KEY REFERENCES catalogue_sessions(session_id)\n);\n"
