//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.
//// The checked-in SQL file is the schema source of truth.

/// The schema used both at runtime and by sqlc during generation.
pub const schema =
  "-- The executor ledger's second schema version (protocol-change/078, addendum:\n-- the review of the remote core). A scope that closed with unknown cleanup, or\n-- stopped in `closing` because the executor's VM ended mid-close, has no\n-- automatic successor. An operator releases it with `loomd executor release`,\n-- and this table is the record that they did.\n--\n-- One row per release, in the order they happened. `was` is the state the scope\n-- had before: `closing`, or `unknown:<count>` for the cleanup that could not be\n-- proven. `released_at_ms` is the executor's wall clock in Unix milliseconds.\nCREATE TABLE scope_release(\n  id INTEGER PRIMARY KEY,\n  session TEXT NOT NULL,\n  workspace TEXT NOT NULL,\n  incarnation INTEGER NOT NULL CHECK(incarnation >= 0),\n  was TEXT NOT NULL,\n  released_at_ms INTEGER NOT NULL\n);\n"
