//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.
//// The checked-in SQL file is the schema source of truth.

/// The schema used both at runtime and by sqlc during generation.
pub const schema =
  "-- Offers retain complete immutable service proposals, never partial native requests.\nCREATE TABLE owner_custody_command_offers (\n  address TEXT PRIMARY KEY NOT NULL,\n  parent TEXT NOT NULL,\n  service_origin TEXT NOT NULL,\n  service_id TEXT NOT NULL,\n  identity BLOB NOT NULL,\n  native_origin TEXT NOT NULL UNIQUE,\n  offer_digest TEXT NOT NULL,\n  offer BLOB NOT NULL,\n  state TEXT NOT NULL CHECK(state IN ('retained', 'cancelled', 'frozen')),\n  reserved_bytes INTEGER NOT NULL CHECK(reserved_bytes >= 0)\n);\nCREATE INDEX owner_command_offer_parent ON owner_custody_command_offers(parent, address);\nCREATE INDEX owner_command_offer_service ON owner_custody_command_offers(service_origin, address);\n"
