//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import gleam/option.{type Option}
import parrot/dev

pub type AccessOwner {
  AccessOwner(principal_id: String, display_name: String, kind: String)
}

pub fn access_owner() {
  let sql =
    "
SELECT principal_id, display_name, kind FROM access_principals WHERE kind = 'owner' LIMIT 2"
  #(sql, [], access_owner_decoder())
}

pub fn access_owner_decoder() -> decode.Decoder(AccessOwner) {
  use principal_id <- decode.field(0, decode.string)
  use display_name <- decode.field(1, decode.string)
  use kind <- decode.field(2, decode.string)
  decode.success(AccessOwner(principal_id:, display_name:, kind:))
}

pub type AccessPrincipal {
  AccessPrincipal(principal_id: String, display_name: String, kind: String)
}

pub fn access_principal(principal_id principal_id: String) {
  let sql =
    "SELECT principal_id, display_name, kind FROM access_principals WHERE principal_id = ?"
  #(sql, [dev.ParamString(principal_id)], access_principal_decoder())
}

pub fn access_principal_decoder() -> decode.Decoder(AccessPrincipal) {
  use principal_id <- decode.field(0, decode.string)
  use display_name <- decode.field(1, decode.string)
  use kind <- decode.field(2, decode.string)
  decode.success(AccessPrincipal(principal_id:, display_name:, kind:))
}

pub fn insert_access_principal(
  principal_id principal_id: String,
  display_name display_name: String,
  kind kind: String,
) {
  let sql =
    "INSERT INTO access_principals(principal_id, display_name, kind) VALUES (?, ?, ?)"
  #(sql, [
    dev.ParamString(principal_id),
    dev.ParamString(display_name),
    dev.ParamString(kind),
  ])
}

pub fn rename_access_principal(
  display_name display_name: String,
  principal_id principal_id: String,
) {
  let sql =
    "UPDATE access_principals SET display_name = ? WHERE principal_id = ?"
  #(sql, [dev.ParamString(display_name), dev.ParamString(principal_id)])
}

pub type AccessCredential {
  AccessCredential(digest: String, principal_id: String, state: String)
}

pub fn access_credential(digest digest: String) {
  let sql =
    "SELECT digest, principal_id, state FROM access_credentials WHERE digest = ?"
  #(sql, [dev.ParamString(digest)], access_credential_decoder())
}

pub fn access_credential_decoder() -> decode.Decoder(AccessCredential) {
  use digest <- decode.field(0, decode.string)
  use principal_id <- decode.field(1, decode.string)
  use state <- decode.field(2, decode.string)
  decode.success(AccessCredential(digest:, principal_id:, state:))
}

pub fn insert_access_credential(
  digest digest: String,
  principal_id principal_id: String,
) {
  let sql =
    "INSERT INTO access_credentials(digest, principal_id, state) VALUES (?, ?, 'active')"
  #(sql, [dev.ParamString(digest), dev.ParamString(principal_id)])
}

pub fn revoke_access_credential(digest digest: String) {
  let sql = "UPDATE access_credentials SET state = 'revoked' WHERE digest = ?"
  #(sql, [dev.ParamString(digest)])
}

pub fn revoke_member_credentials(principal_id principal_id: String) {
  let sql =
    "UPDATE access_credentials SET state = 'revoked' WHERE principal_id = ? AND state = 'active'"
  #(sql, [dev.ParamString(principal_id)])
}

pub type AccessMembership {
  AccessMembership(role: String)
}

pub fn access_membership(
  principal_id principal_id: String,
  session_id session_id: String,
) {
  let sql =
    "SELECT role FROM access_memberships WHERE principal_id = ? AND session_id = ?"
  #(
    sql,
    [dev.ParamString(principal_id), dev.ParamString(session_id)],
    access_membership_decoder(),
  )
}

pub fn access_membership_decoder() -> decode.Decoder(AccessMembership) {
  use role <- decode.field(0, decode.string)
  decode.success(AccessMembership(role:))
}

pub fn grant_access_membership(
  principal_id principal_id: String,
  session_id session_id: String,
  role role: String,
) {
  let sql =
    "INSERT INTO access_memberships(principal_id, session_id, role) VALUES (?, ?, ?)
ON CONFLICT(principal_id, session_id) DO UPDATE SET role = excluded.role"
  #(sql, [
    dev.ParamString(principal_id),
    dev.ParamString(session_id),
    dev.ParamString(role),
  ])
}

pub fn revoke_access_membership(
  principal_id principal_id: String,
  session_id session_id: String,
) {
  let sql =
    "DELETE FROM access_memberships WHERE principal_id = ? AND session_id = ?"
  #(sql, [dev.ParamString(principal_id), dev.ParamString(session_id)])
}

pub fn initialize_catalogue_revision() {
  let sql =
    "
INSERT INTO catalogue_meta (singleton, revision) VALUES (1, 0)"
  #(sql, [])
}

pub type FindRegistrations {
  FindRegistrations(
    session_id: String,
    path: String,
    workspace: String,
    name: String,
    configuration: String,
    created_at: Int,
    request_key: String,
    state: String,
  )
}

pub fn find_registrations(
  session_id session_id: String,
  request_key request_key: String,
  path path: String,
) {
  let sql =
    "SELECT session_id, path, workspace, name, configuration, created_at, request_key, state
FROM catalogue_sessions
WHERE session_id = ? OR request_key = ? OR path = ?"
  #(
    sql,
    [
      dev.ParamString(session_id),
      dev.ParamString(request_key),
      dev.ParamString(path),
    ],
    find_registrations_decoder(),
  )
}

pub fn find_registrations_decoder() -> decode.Decoder(FindRegistrations) {
  use session_id <- decode.field(0, decode.string)
  use path <- decode.field(1, decode.string)
  use workspace <- decode.field(2, decode.string)
  use name <- decode.field(3, decode.string)
  use configuration <- decode.field(4, decode.string)
  use created_at <- decode.field(5, decode.int)
  use request_key <- decode.field(6, decode.string)
  use state <- decode.field(7, decode.string)
  decode.success(FindRegistrations(
    session_id:,
    path:,
    workspace:,
    name:,
    configuration:,
    created_at:,
    request_key:,
    state:,
  ))
}

pub fn insert_registration(
  session_id session_id: String,
  path path: String,
  workspace workspace: String,
  name name: String,
  configuration configuration: String,
  created_at created_at: Int,
  request_key request_key: String,
) {
  let sql =
    "INSERT INTO catalogue_sessions
  (session_id, path, workspace, name, configuration, created_at, request_key, state)
VALUES (?, ?, ?, ?, ?, ?, ?, 'reserved')"
  #(sql, [
    dev.ParamString(session_id),
    dev.ParamString(path),
    dev.ParamString(workspace),
    dev.ParamString(name),
    dev.ParamString(configuration),
    dev.ParamInt(created_at),
    dev.ParamString(request_key),
  ])
}

pub fn confirm_registration(session_id session_id: String) {
  let sql = "UPDATE catalogue_sessions SET state = 'saved' WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)])
}

pub type RegistrationPage {
  RegistrationPage(
    session_id: String,
    path: String,
    workspace: String,
    name: String,
    configuration: String,
    created_at: Int,
    request_key: String,
    state: String,
  )
}

pub fn registration_page(session_id session_id: String) {
  let sql =
    "SELECT session_id, path, workspace, name, configuration, created_at, request_key, state
FROM catalogue_sessions
WHERE session_id > ?
ORDER BY session_id
LIMIT 100"
  #(sql, [dev.ParamString(session_id)], registration_page_decoder())
}

pub fn registration_page_decoder() -> decode.Decoder(RegistrationPage) {
  use session_id <- decode.field(0, decode.string)
  use path <- decode.field(1, decode.string)
  use workspace <- decode.field(2, decode.string)
  use name <- decode.field(3, decode.string)
  use configuration <- decode.field(4, decode.string)
  use created_at <- decode.field(5, decode.int)
  use request_key <- decode.field(6, decode.string)
  use state <- decode.field(7, decode.string)
  decode.success(RegistrationPage(
    session_id:,
    path:,
    workspace:,
    name:,
    configuration:,
    created_at:,
    request_key:,
    state:,
  ))
}

pub type CatalogueRevision {
  CatalogueRevision(revision: Int)
}

pub fn catalogue_revision() {
  let sql = "SELECT revision FROM catalogue_meta WHERE singleton = 1"
  #(sql, [], catalogue_revision_decoder())
}

pub fn catalogue_revision_decoder() -> decode.Decoder(CatalogueRevision) {
  use revision <- decode.field(0, decode.int)
  decode.success(CatalogueRevision(revision:))
}

pub type MemberRegistrationPage {
  MemberRegistrationPage(
    session_id: String,
    path: String,
    workspace: String,
    name: String,
    configuration: String,
    created_at: Int,
    request_key: String,
    state: String,
  )
}

pub fn member_registration_page(
  principal_id principal_id: String,
  session_id session_id: String,
) {
  let sql =
    "SELECT s.session_id, s.path, s.workspace, s.name, s.configuration,
       s.created_at, s.request_key, s.state
FROM access_memberships AS m
JOIN catalogue_sessions AS s ON s.session_id = m.session_id
WHERE m.principal_id = ? AND s.session_id > ?
  AND m.role IN ('operator', 'observer')
ORDER BY s.session_id
LIMIT 100"
  #(
    sql,
    [dev.ParamString(principal_id), dev.ParamString(session_id)],
    member_registration_page_decoder(),
  )
}

pub fn member_registration_page_decoder() -> decode.Decoder(
  MemberRegistrationPage,
) {
  use session_id <- decode.field(0, decode.string)
  use path <- decode.field(1, decode.string)
  use workspace <- decode.field(2, decode.string)
  use name <- decode.field(3, decode.string)
  use configuration <- decode.field(4, decode.string)
  use created_at <- decode.field(5, decode.int)
  use request_key <- decode.field(6, decode.string)
  use state <- decode.field(7, decode.string)
  decode.success(MemberRegistrationPage(
    session_id:,
    path:,
    workspace:,
    name:,
    configuration:,
    created_at:,
    request_key:,
    state:,
  ))
}

pub fn increment_catalogue_revision() {
  let sql =
    "UPDATE catalogue_meta SET revision = revision + 1 WHERE singleton = 1"
  #(sql, [])
}

pub type WorkspaceDefault {
  WorkspaceDefault(session_id: String)
}

pub fn workspace_default(workspace workspace: String) {
  let sql = "SELECT session_id FROM catalogue_defaults WHERE workspace = ?"
  #(sql, [dev.ParamString(workspace)], workspace_default_decoder())
}

pub fn workspace_default_decoder() -> decode.Decoder(WorkspaceDefault) {
  use session_id <- decode.field(0, decode.string)
  decode.success(WorkspaceDefault(session_id:))
}

pub fn set_workspace_default(
  workspace workspace: String,
  session_id session_id: String,
) {
  let sql =
    "INSERT INTO catalogue_defaults (workspace, session_id) VALUES (?, ?)
ON CONFLICT(workspace) DO UPDATE SET session_id = excluded.session_id"
  #(sql, [dev.ParamString(workspace), dev.ParamString(session_id)])
}

pub type DomainById {
  DomainById(
    domain_id: String,
    scope: String,
    scope_key: String,
    workspace: String,
    configuration: String,
    memory_path: String,
    index_path: String,
    digest_path: String,
  )
}

pub fn domain_by_id(domain_id domain_id: String) {
  let sql =
    "
SELECT domain_id, scope, scope_key, workspace, configuration, memory_path, index_path, digest_path
FROM catalogue_domains WHERE domain_id = ?"
  #(sql, [dev.ParamString(domain_id)], domain_by_id_decoder())
}

pub fn domain_by_id_decoder() -> decode.Decoder(DomainById) {
  use domain_id <- decode.field(0, decode.string)
  use scope <- decode.field(1, decode.string)
  use scope_key <- decode.field(2, decode.string)
  use workspace <- decode.field(3, decode.string)
  use configuration <- decode.field(4, decode.string)
  use memory_path <- decode.field(5, decode.string)
  use index_path <- decode.field(6, decode.string)
  use digest_path <- decode.field(7, decode.string)
  decode.success(DomainById(
    domain_id:,
    scope:,
    scope_key:,
    workspace:,
    configuration:,
    memory_path:,
    index_path:,
    digest_path:,
  ))
}

pub type DomainForSession {
  DomainForSession(
    domain_id: String,
    scope: String,
    scope_key: String,
    workspace: String,
    configuration: String,
    memory_path: String,
    index_path: String,
    digest_path: String,
  )
}

pub fn domain_for_session(session_id session_id: String) {
  let sql =
    "SELECT d.domain_id, d.scope, d.scope_key, d.workspace, d.configuration, d.memory_path, d.index_path, d.digest_path
FROM catalogue_domain_sessions AS s JOIN catalogue_domains AS d ON d.domain_id = s.domain_id
WHERE s.session_id = ?"
  #(sql, [dev.ParamString(session_id)], domain_for_session_decoder())
}

pub fn domain_for_session_decoder() -> decode.Decoder(DomainForSession) {
  use domain_id <- decode.field(0, decode.string)
  use scope <- decode.field(1, decode.string)
  use scope_key <- decode.field(2, decode.string)
  use workspace <- decode.field(3, decode.string)
  use configuration <- decode.field(4, decode.string)
  use memory_path <- decode.field(5, decode.string)
  use index_path <- decode.field(6, decode.string)
  use digest_path <- decode.field(7, decode.string)
  decode.success(DomainForSession(
    domain_id:,
    scope:,
    scope_key:,
    workspace:,
    configuration:,
    memory_path:,
    index_path:,
    digest_path:,
  ))
}

pub type DomainPathConflicts {
  DomainPathConflicts(domain_id: String)
}

pub fn domain_path_conflicts(
  memory memory: String,
  search search: String,
  digest digest: String,
) {
  let sql =
    "SELECT domain_id FROM catalogue_domains
WHERE memory_path IN (?1, ?2, ?3)
OR index_path IN (?1, ?2, ?3)
OR digest_path IN (?1, ?2, ?3) LIMIT 2"
  #(
    sql,
    [dev.ParamString(memory), dev.ParamString(search), dev.ParamString(digest)],
    domain_path_conflicts_decoder(),
  )
}

pub fn domain_path_conflicts_decoder() -> decode.Decoder(DomainPathConflicts) {
  use domain_id <- decode.field(0, decode.string)
  decode.success(DomainPathConflicts(domain_id:))
}

pub fn insert_domain(
  domain_id domain_id: String,
  scope scope: String,
  scope_key scope_key: String,
  workspace workspace: String,
  configuration configuration: String,
  memory_path memory_path: String,
  index_path index_path: String,
  digest_path digest_path: String,
) {
  let sql =
    "INSERT INTO catalogue_domains(domain_id, scope, scope_key, workspace, configuration, memory_path, index_path, digest_path)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamString(domain_id),
    dev.ParamString(scope),
    dev.ParamString(scope_key),
    dev.ParamString(workspace),
    dev.ParamString(configuration),
    dev.ParamString(memory_path),
    dev.ParamString(index_path),
    dev.ParamString(digest_path),
  ])
}

pub fn bind_session_domain(
  session_id session_id: String,
  domain_id domain_id: String,
) {
  let sql =
    "INSERT INTO catalogue_domain_sessions(session_id, domain_id) VALUES (?, ?)
ON CONFLICT(session_id) DO UPDATE SET domain_id = excluded.domain_id"
  #(sql, [dev.ParamString(session_id), dev.ParamString(domain_id)])
}

pub type DomainSources {
  DomainSources(session_id: String)
}

pub fn domain_sources(
  domain_id domain_id: String,
  session_id session_id: String,
) {
  let sql =
    "SELECT s.session_id FROM catalogue_domain_sessions AS s
JOIN catalogue_sessions AS r ON r.session_id = s.session_id
WHERE s.domain_id = ? AND s.session_id > ? AND r.state = 'saved'
ORDER BY s.session_id LIMIT 100"
  #(
    sql,
    [dev.ParamString(domain_id), dev.ParamString(session_id)],
    domain_sources_decoder(),
  )
}

pub fn domain_sources_decoder() -> decode.Decoder(DomainSources) {
  use session_id <- decode.field(0, decode.string)
  decode.success(DomainSources(session_id:))
}

pub type DomainPage {
  DomainPage(
    domain_id: String,
    scope: String,
    scope_key: String,
    workspace: String,
    configuration: String,
    memory_path: String,
    index_path: String,
    digest_path: String,
  )
}

pub fn domain_page(domain_id domain_id: String) {
  let sql =
    "SELECT domain_id, scope, scope_key, workspace, configuration, memory_path, index_path, digest_path
FROM catalogue_domains WHERE domain_id > ? ORDER BY domain_id LIMIT 100"
  #(sql, [dev.ParamString(domain_id)], domain_page_decoder())
}

pub fn domain_page_decoder() -> decode.Decoder(DomainPage) {
  use domain_id <- decode.field(0, decode.string)
  use scope <- decode.field(1, decode.string)
  use scope_key <- decode.field(2, decode.string)
  use workspace <- decode.field(3, decode.string)
  use configuration <- decode.field(4, decode.string)
  use memory_path <- decode.field(5, decode.string)
  use index_path <- decode.field(6, decode.string)
  use digest_path <- decode.field(7, decode.string)
  decode.success(DomainPage(
    domain_id:,
    scope:,
    scope_key:,
    workspace:,
    configuration:,
    memory_path:,
    index_path:,
    digest_path:,
  ))
}

pub type HistorySourceHeader {
  HistorySourceHeader(metadata_bytes: Int, next_seq: Option(Int))
}

pub fn history_source_header() {
  let sql =
    "
SELECT CAST(COALESCE(length(metadata), 0) AS INTEGER) AS metadata_bytes,
  next_seq FROM session LIMIT 2"
  #(sql, [], history_source_header_decoder())
}

pub fn history_source_header_decoder() -> decode.Decoder(HistorySourceHeader) {
  use metadata_bytes <- decode.field(0, decode.int)
  use next_seq <- decode.field(1, decode.optional(decode.int))
  decode.success(HistorySourceHeader(metadata_bytes:, next_seq:))
}

pub type HistorySourceMetadata {
  HistorySourceMetadata(metadata: Option(BitArray))
}

pub fn history_source_metadata() {
  let sql = "SELECT metadata FROM session LIMIT 2"
  #(sql, [], history_source_metadata_decoder())
}

pub fn history_source_metadata_decoder() -> decode.Decoder(
  HistorySourceMetadata,
) {
  use metadata <- decode.field(0, decode.optional(decode.bit_array))
  decode.success(HistorySourceMetadata(metadata:))
}

pub type HistorySourceEntry {
  HistorySourceEntry(seq: Option(Int), payload_bytes: Option(Int))
}

pub fn history_source_entry(
  entry_id entry_id: String,
  before_seq before_seq: Option(Int),
) {
  let sql =
    "SELECT seq, length(payload) AS payload_bytes FROM entries
WHERE id = ?1 AND seq < ?2 LIMIT 2"
  #(
    sql,
    [
      dev.ParamString(entry_id),
      dev.ParamNullable(option.map(before_seq, fn(v) { dev.ParamInt(v) })),
    ],
    history_source_entry_decoder(),
  )
}

pub fn history_source_entry_decoder() -> decode.Decoder(HistorySourceEntry) {
  use seq <- decode.field(0, decode.optional(decode.int))
  use payload_bytes <- decode.field(1, decode.optional(decode.int))
  decode.success(HistorySourceEntry(seq:, payload_bytes:))
}

pub type SnapshotSession {
  SnapshotSession(
    next_seq: Option(Int),
    message_count: Option(Int),
    usage_bytes: Option(Int),
  )
}

pub fn snapshot_session() {
  let sql =
    "SELECT next_seq, message_count, length(usage_payload) AS usage_bytes
FROM session LIMIT 2"
  #(sql, [], snapshot_session_decoder())
}

pub fn snapshot_session_decoder() -> decode.Decoder(SnapshotSession) {
  use next_seq <- decode.field(0, decode.optional(decode.int))
  use message_count <- decode.field(1, decode.optional(decode.int))
  use usage_bytes <- decode.field(2, decode.optional(decode.int))
  decode.success(SnapshotSession(next_seq:, message_count:, usage_bytes:))
}

pub type SnapshotUsageValue {
  SnapshotUsageValue(usage_payload: Option(BitArray))
}

pub fn snapshot_usage_value() {
  let sql = "SELECT usage_payload FROM session LIMIT 2"
  #(sql, [], snapshot_usage_value_decoder())
}

pub fn snapshot_usage_value_decoder() -> decode.Decoder(SnapshotUsageValue) {
  use usage_payload <- decode.field(0, decode.optional(decode.bit_array))
  decode.success(SnapshotUsageValue(usage_payload:))
}

pub type SnapshotRegisterHeaders {
  SnapshotRegisterHeaders(key: String, seq: Int, value_bytes: Option(Int))
}

pub fn snapshot_register_headers(
  namespace namespace: String,
  prefix prefix: String,
  prefix_upper prefix_upper: String,
  field field: String,
  expected expected: String,
) {
  let sql =
    "SELECT key, seq, length(value) AS value_bytes
FROM registers
WHERE ns = ?1 AND key >= ?2 AND key <
  CASE WHEN CAST(?3 AS TEXT) = '' THEN CAST('' AS BLOB)
  ELSE CAST(?3 AS TEXT) END
AND CASE
  WHEN CAST(?4 AS TEXT) = '' THEN 1
  WHEN length(value) > 1048576 THEN 1
  WHEN NOT json_valid(CAST(value AS TEXT)) THEN 1
  WHEN json_type(CAST(value AS TEXT), '$.' || ?4) IS NOT 'text' THEN 1
  ELSE json_extract(CAST(value AS TEXT), '$.' || ?4) = CAST(?5 AS TEXT)
END
ORDER BY key LIMIT 1025"
  #(
    sql,
    [
      dev.ParamString(namespace),
      dev.ParamString(prefix),
      dev.ParamString(prefix_upper),
      dev.ParamString(field),
      dev.ParamString(expected),
    ],
    snapshot_register_headers_decoder(),
  )
}

pub fn snapshot_register_headers_decoder() -> decode.Decoder(
  SnapshotRegisterHeaders,
) {
  use key <- decode.field(0, decode.string)
  use seq <- decode.field(1, decode.int)
  use value_bytes <- decode.field(2, decode.optional(decode.int))
  decode.success(SnapshotRegisterHeaders(key:, seq:, value_bytes:))
}

pub type SnapshotRegisterBudget {
  SnapshotRegisterBudget(cell_count: Int, total_bytes: Int)
}

pub fn snapshot_register_budget(
  namespace namespace: String,
  prefix prefix: String,
  prefix_upper prefix_upper: String,
  field field: String,
  expected expected: String,
) {
  let sql =
    "SELECT COUNT(*) AS cell_count,
  CAST(COALESCE(SUM(length(value) + length(CAST(key AS BLOB)) + length(CAST(ns AS BLOB)) + 65), 0) AS INTEGER) AS total_bytes
FROM registers
WHERE ns = ?1 AND key >= ?2 AND key <
  CASE WHEN CAST(?3 AS TEXT) = '' THEN CAST('' AS BLOB)
  ELSE CAST(?3 AS TEXT) END
AND CASE
  WHEN CAST(?4 AS TEXT) = '' THEN 1
  WHEN length(value) > 1048576 THEN 1
  WHEN NOT json_valid(CAST(value AS TEXT)) THEN 1
  WHEN json_type(CAST(value AS TEXT), '$.' || ?4) IS NOT 'text' THEN 1
  ELSE json_extract(CAST(value AS TEXT), '$.' || ?4) = CAST(?5 AS TEXT)
END"
  #(
    sql,
    [
      dev.ParamString(namespace),
      dev.ParamString(prefix),
      dev.ParamString(prefix_upper),
      dev.ParamString(field),
      dev.ParamString(expected),
    ],
    snapshot_register_budget_decoder(),
  )
}

pub fn snapshot_register_budget_decoder() -> decode.Decoder(
  SnapshotRegisterBudget,
) {
  use cell_count <- decode.field(0, decode.int)
  use total_bytes <- decode.field(1, decode.int)
  decode.success(SnapshotRegisterBudget(cell_count:, total_bytes:))
}

pub type SnapshotRegisterValue {
  SnapshotRegisterValue(value: BitArray)
}

pub fn snapshot_register_value(
  namespace namespace: String,
  key key: String,
  seq seq: Int,
) {
  let sql =
    "SELECT value FROM registers
WHERE ns = ?1 AND key = ?2 AND seq = ?3"
  #(
    sql,
    [dev.ParamString(namespace), dev.ParamString(key), dev.ParamInt(seq)],
    snapshot_register_value_decoder(),
  )
}

pub fn snapshot_register_value_decoder() -> decode.Decoder(
  SnapshotRegisterValue,
) {
  use value <- decode.field(0, decode.bit_array)
  decode.success(SnapshotRegisterValue(value:))
}

pub type SnapshotRegisterHeader {
  SnapshotRegisterHeader(seq: Int, value_bytes: Option(Int))
}

pub fn snapshot_register_header(namespace namespace: String, key key: String) {
  let sql =
    "SELECT seq, length(value) AS value_bytes FROM registers
WHERE ns = ?1 AND key = ?2"
  #(
    sql,
    [dev.ParamString(namespace), dev.ParamString(key)],
    snapshot_register_header_decoder(),
  )
}

pub fn snapshot_register_header_decoder() -> decode.Decoder(
  SnapshotRegisterHeader,
) {
  use seq <- decode.field(0, decode.int)
  use value_bytes <- decode.field(1, decode.optional(decode.int))
  decode.success(SnapshotRegisterHeader(seq:, value_bytes:))
}

pub type SnapshotEntryPage {
  SnapshotEntryPage(id: String, seq: Option(Int), payload_bytes: Option(Int))
}

pub fn snapshot_entry_page(
  after_seq after_seq: Option(Int),
  before_seq before_seq: Option(Int),
  page_size page_size: Int,
) {
  let sql =
    "SELECT CAST(CASE WHEN length(CAST(id AS BLOB)) = 36 THEN id ELSE '' END AS TEXT) AS id,
  seq, length(payload) AS payload_bytes FROM entries
WHERE seq > ?1 AND seq < ?2
ORDER BY seq ASC LIMIT ?3"
  #(
    sql,
    [
      dev.ParamNullable(option.map(after_seq, fn(v) { dev.ParamInt(v) })),
      dev.ParamNullable(option.map(before_seq, fn(v) { dev.ParamInt(v) })),
      dev.ParamInt(page_size),
    ],
    snapshot_entry_page_decoder(),
  )
}

pub fn snapshot_entry_page_decoder() -> decode.Decoder(SnapshotEntryPage) {
  use id <- decode.field(0, decode.string)
  use seq <- decode.field(1, decode.optional(decode.int))
  use payload_bytes <- decode.field(2, decode.optional(decode.int))
  decode.success(SnapshotEntryPage(id:, seq:, payload_bytes:))
}

pub type SnapshotRecentEntries {
  SnapshotRecentEntries(
    id: String,
    seq: Option(Int),
    payload_bytes: Option(Int),
  )
}

pub fn snapshot_recent_entries(
  before_seq before_seq: Option(Int),
  page_size page_size: Int,
) {
  let sql =
    "SELECT CAST(CASE WHEN length(CAST(id AS BLOB)) = 36 THEN id ELSE '' END AS TEXT) AS id,
  seq, length(payload) AS payload_bytes FROM entries
WHERE seq < ?1 ORDER BY seq DESC LIMIT ?2"
  #(
    sql,
    [
      dev.ParamNullable(option.map(before_seq, fn(v) { dev.ParamInt(v) })),
      dev.ParamInt(page_size),
    ],
    snapshot_recent_entries_decoder(),
  )
}

pub fn snapshot_recent_entries_decoder() -> decode.Decoder(
  SnapshotRecentEntries,
) {
  use id <- decode.field(0, decode.string)
  use seq <- decode.field(1, decode.optional(decode.int))
  use payload_bytes <- decode.field(2, decode.optional(decode.int))
  decode.success(SnapshotRecentEntries(id:, seq:, payload_bytes:))
}

pub type SnapshotEntryFragment {
  SnapshotEntryFragment(fragment: BitArray)
}

pub fn snapshot_entry_fragment(
  offset offset: Int,
  fragment_size fragment_size: Int,
  id id: String,
  seq seq: Option(Int),
  payload_bytes payload_bytes: Int,
) {
  let sql =
    "SELECT CAST(substr(payload, CAST(?1 AS INTEGER) + 1, ?2) AS BLOB) AS fragment FROM entries
WHERE id = ?3 AND seq = ?4 AND length(payload) = CAST(?5 AS INTEGER)"
  #(
    sql,
    [
      dev.ParamInt(offset),
      dev.ParamInt(fragment_size),
      dev.ParamString(id),
      dev.ParamNullable(option.map(seq, fn(v) { dev.ParamInt(v) })),
      dev.ParamInt(payload_bytes),
    ],
    snapshot_entry_fragment_decoder(),
  )
}

pub fn snapshot_entry_fragment_decoder() -> decode.Decoder(
  SnapshotEntryFragment,
) {
  use fragment <- decode.field(0, decode.bit_array)
  decode.success(SnapshotEntryFragment(fragment:))
}
