//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import gleam/option.{type Option}
import parrot/dev

pub type AccessOwner {
  AccessOwner(principal_id: String, display_name: String, kind: String)
}

pub fn access_owner() {
  let sql =
    "
SELECT principal_id, display_name, kind FROM access_principals WHERE kind = 'owner' LIMIT 2"
  #(sql, [], access_owner_decoder())
}

pub fn access_owner_decoder() -> decode.Decoder(AccessOwner) {
  use principal_id <- decode.field(0, decode.string)
  use display_name <- decode.field(1, decode.string)
  use kind <- decode.field(2, decode.string)
  decode.success(AccessOwner(principal_id:, display_name:, kind:))
}

pub type AccessPrincipal {
  AccessPrincipal(principal_id: String, display_name: String, kind: String)
}

pub fn access_principal(principal_id principal_id: String) {
  let sql =
    "SELECT principal_id, display_name, kind FROM access_principals WHERE principal_id = ?"
  #(sql, [dev.ParamString(principal_id)], access_principal_decoder())
}

pub fn access_principal_decoder() -> decode.Decoder(AccessPrincipal) {
  use principal_id <- decode.field(0, decode.string)
  use display_name <- decode.field(1, decode.string)
  use kind <- decode.field(2, decode.string)
  decode.success(AccessPrincipal(principal_id:, display_name:, kind:))
}

pub fn insert_access_principal(
  principal_id principal_id: String,
  display_name display_name: String,
  kind kind: String,
) {
  let sql =
    "INSERT INTO access_principals(principal_id, display_name, kind) VALUES (?, ?, ?)"
  #(sql, [
    dev.ParamString(principal_id),
    dev.ParamString(display_name),
    dev.ParamString(kind),
  ])
}

pub fn rename_access_principal(
  display_name display_name: String,
  principal_id principal_id: String,
) {
  let sql =
    "UPDATE access_principals SET display_name = ? WHERE principal_id = ?"
  #(sql, [dev.ParamString(display_name), dev.ParamString(principal_id)])
}

pub type AccessCredential {
  AccessCredential(digest: String, principal_id: String, state: String)
}

pub fn access_credential(digest digest: String, kind kind: String) {
  let sql =
    "SELECT digest, principal_id, state FROM access_credentials WHERE digest = ? AND kind = ?"
  #(
    sql,
    [dev.ParamString(digest), dev.ParamString(kind)],
    access_credential_decoder(),
  )
}

pub fn access_credential_decoder() -> decode.Decoder(AccessCredential) {
  use digest <- decode.field(0, decode.string)
  use principal_id <- decode.field(1, decode.string)
  use state <- decode.field(2, decode.string)
  decode.success(AccessCredential(digest:, principal_id:, state:))
}

pub type AccessCredentialAnyKind {
  AccessCredentialAnyKind(digest: String, principal_id: String, state: String)
}

pub fn access_credential_any_kind(digest digest: String) {
  let sql =
    "SELECT digest, principal_id, state FROM access_credentials WHERE digest = ?"
  #(sql, [dev.ParamString(digest)], access_credential_any_kind_decoder())
}

pub fn access_credential_any_kind_decoder() -> decode.Decoder(
  AccessCredentialAnyKind,
) {
  use digest <- decode.field(0, decode.string)
  use principal_id <- decode.field(1, decode.string)
  use state <- decode.field(2, decode.string)
  decode.success(AccessCredentialAnyKind(digest:, principal_id:, state:))
}

pub fn insert_access_credential(
  digest digest: String,
  principal_id principal_id: String,
  kind kind: String,
) {
  let sql =
    "INSERT INTO access_credentials(digest, principal_id, state, kind) VALUES (?, ?, 'active', ?)"
  #(sql, [
    dev.ParamString(digest),
    dev.ParamString(principal_id),
    dev.ParamString(kind),
  ])
}

pub fn revoke_access_credential(digest digest: String) {
  let sql = "UPDATE access_credentials SET state = 'revoked' WHERE digest = ?"
  #(sql, [dev.ParamString(digest)])
}

pub fn revoke_member_credentials(principal_id principal_id: String) {
  let sql =
    "UPDATE access_credentials SET state = 'revoked' WHERE principal_id = ? AND state = 'active'"
  #(sql, [dev.ParamString(principal_id)])
}

pub type AccessMembership {
  AccessMembership(role: String)
}

pub fn access_membership(
  principal_id principal_id: String,
  session_id session_id: String,
) {
  let sql =
    "SELECT role FROM access_memberships WHERE principal_id = ? AND session_id = ?"
  #(
    sql,
    [dev.ParamString(principal_id), dev.ParamString(session_id)],
    access_membership_decoder(),
  )
}

pub fn access_membership_decoder() -> decode.Decoder(AccessMembership) {
  use role <- decode.field(0, decode.string)
  decode.success(AccessMembership(role:))
}

pub fn grant_access_membership(
  principal_id principal_id: String,
  session_id session_id: String,
  role role: String,
) {
  let sql =
    "INSERT INTO access_memberships(principal_id, session_id, role) VALUES (?, ?, ?)
ON CONFLICT(principal_id, session_id) DO UPDATE SET role = excluded.role"
  #(sql, [
    dev.ParamString(principal_id),
    dev.ParamString(session_id),
    dev.ParamString(role),
  ])
}

pub fn revoke_access_membership(
  principal_id principal_id: String,
  session_id session_id: String,
) {
  let sql =
    "DELETE FROM access_memberships WHERE principal_id = ? AND session_id = ?"
  #(sql, [dev.ParamString(principal_id), dev.ParamString(session_id)])
}

pub type AccessClaim {
  AccessClaim(
    digest: String,
    principal_id: String,
    expires_at_ms: Int,
    state: String,
    credential_digest: Option(String),
    claimed_at_ms: Option(Int),
  )
}

pub fn access_claim(digest digest: String) {
  let sql =
    "SELECT digest, principal_id, expires_at_ms, state, credential_digest, claimed_at_ms FROM access_claims WHERE digest = ?"
  #(sql, [dev.ParamString(digest)], access_claim_decoder())
}

pub fn access_claim_decoder() -> decode.Decoder(AccessClaim) {
  use digest <- decode.field(0, decode.string)
  use principal_id <- decode.field(1, decode.string)
  use expires_at_ms <- decode.field(2, decode.int)
  use state <- decode.field(3, decode.string)
  use credential_digest <- decode.field(4, decode.optional(decode.string))
  use claimed_at_ms <- decode.field(5, decode.optional(decode.int))
  decode.success(AccessClaim(
    digest:,
    principal_id:,
    expires_at_ms:,
    state:,
    credential_digest:,
    claimed_at_ms:,
  ))
}

pub fn insert_access_claim(
  digest digest: String,
  principal_id principal_id: String,
  expires_at_ms expires_at_ms: Int,
) {
  let sql =
    "INSERT INTO access_claims(digest, principal_id, expires_at_ms, state) VALUES (?, ?, ?, 'open')"
  #(sql, [
    dev.ParamString(digest),
    dev.ParamString(principal_id),
    dev.ParamInt(expires_at_ms),
  ])
}

pub fn bind_access_claim(
  credential_digest credential_digest: Option(String),
  claimed_at_ms claimed_at_ms: Option(Int),
  digest digest: String,
) {
  let sql =
    "UPDATE access_claims SET state = 'claimed', credential_digest = ?, claimed_at_ms = ? WHERE digest = ? AND state = 'open'"
  #(sql, [
    dev.ParamNullable(
      option.map(credential_digest, fn(v) { dev.ParamString(v) }),
    ),
    dev.ParamNullable(option.map(claimed_at_ms, fn(v) { dev.ParamInt(v) })),
    dev.ParamString(digest),
  ])
}

pub fn void_member_claims(principal_id principal_id: String) {
  let sql =
    "UPDATE access_claims SET state = 'void' WHERE principal_id = ? AND state = 'open'"
  #(sql, [dev.ParamString(principal_id)])
}

pub type ActiveMemberCredentials {
  ActiveMemberCredentials(digest: String)
}

pub fn active_member_credentials(principal_id principal_id: String) {
  let sql =
    "SELECT digest FROM access_credentials WHERE principal_id = ? AND state = 'active' LIMIT 1"
  #(sql, [dev.ParamString(principal_id)], active_member_credentials_decoder())
}

pub fn active_member_credentials_decoder() -> decode.Decoder(
  ActiveMemberCredentials,
) {
  use digest <- decode.field(0, decode.string)
  decode.success(ActiveMemberCredentials(digest:))
}

pub type ClaimMemberships {
  ClaimMemberships(session_id: String, role: String)
}

pub fn claim_memberships(principal_id principal_id: String) {
  let sql =
    "SELECT session_id, role FROM access_memberships WHERE principal_id = ? ORDER BY session_id LIMIT 16"
  #(sql, [dev.ParamString(principal_id)], claim_memberships_decoder())
}

pub fn claim_memberships_decoder() -> decode.Decoder(ClaimMemberships) {
  use session_id <- decode.field(0, decode.string)
  use role <- decode.field(1, decode.string)
  decode.success(ClaimMemberships(session_id:, role:))
}

pub type PrincipalListing {
  PrincipalListing(principal_id: String, display_name: String, kind: String)
}

pub fn principal_listing(principal_id principal_id: String) {
  let sql =
    "SELECT principal_id, display_name, kind FROM access_principals WHERE principal_id > ? ORDER BY principal_id LIMIT 101"
  #(sql, [dev.ParamString(principal_id)], principal_listing_decoder())
}

pub fn principal_listing_decoder() -> decode.Decoder(PrincipalListing) {
  use principal_id <- decode.field(0, decode.string)
  use display_name <- decode.field(1, decode.string)
  use kind <- decode.field(2, decode.string)
  decode.success(PrincipalListing(principal_id:, display_name:, kind:))
}

pub type PrincipalActiveCredential {
  PrincipalActiveCredential(digest: String, claimed_at_ms: Option(Int))
}

pub fn principal_active_credential(
  principal_id principal_id: String,
  expires_at_ms expires_at_ms: Option(Int),
) {
  let sql =
    "SELECT c.digest, k.claimed_at_ms FROM access_credentials AS c
LEFT JOIN access_claims AS k ON k.credential_digest = c.digest
WHERE c.principal_id = ? AND c.state = 'active'
  AND (c.kind = 'bearer' OR k.claimed_at_ms IS NOT NULL)
  AND (c.expires_at_ms IS NULL OR c.expires_at_ms > ?)
ORDER BY c.digest LIMIT 1"
  #(
    sql,
    [
      dev.ParamString(principal_id),
      dev.ParamNullable(option.map(expires_at_ms, fn(v) { dev.ParamInt(v) })),
    ],
    principal_active_credential_decoder(),
  )
}

pub fn principal_active_credential_decoder() -> decode.Decoder(
  PrincipalActiveCredential,
) {
  use digest <- decode.field(0, decode.string)
  use claimed_at_ms <- decode.field(1, decode.optional(decode.int))
  decode.success(PrincipalActiveCredential(digest:, claimed_at_ms:))
}

pub type PrincipalOpenClaim {
  PrincipalOpenClaim(expires_at_ms: Int)
}

pub fn principal_open_claim(principal_id principal_id: String) {
  let sql =
    "SELECT expires_at_ms FROM access_claims WHERE principal_id = ? AND state = 'open' LIMIT 1"
  #(sql, [dev.ParamString(principal_id)], principal_open_claim_decoder())
}

pub fn principal_open_claim_decoder() -> decode.Decoder(PrincipalOpenClaim) {
  use expires_at_ms <- decode.field(0, decode.int)
  decode.success(PrincipalOpenClaim(expires_at_ms:))
}

pub type PrincipalMemberships {
  PrincipalMemberships(session_id: String, name: String, role: String)
}

pub fn principal_memberships(
  principal_id principal_id: String,
  session_id session_id: String,
) {
  let sql =
    "SELECT m.session_id, CAST(COALESCE(n.name, s.name) AS TEXT) AS name, m.role
FROM access_memberships AS m
JOIN catalogue_sessions AS s ON s.session_id = m.session_id
LEFT JOIN catalogue_session_names AS n ON n.session_id = s.session_id
WHERE m.principal_id = ? AND m.session_id > ?
ORDER BY m.session_id LIMIT 101"
  #(
    sql,
    [dev.ParamString(principal_id), dev.ParamString(session_id)],
    principal_memberships_decoder(),
  )
}

pub fn principal_memberships_decoder() -> decode.Decoder(PrincipalMemberships) {
  use session_id <- decode.field(0, decode.string)
  use name <- decode.field(1, decode.string)
  use role <- decode.field(2, decode.string)
  decode.success(PrincipalMemberships(session_id:, name:, role:))
}

pub fn insert_access_login(
  digest digest: String,
  principal_id principal_id: String,
  issued_at_ms issued_at_ms: Option(Int),
  expires_at_ms expires_at_ms: Option(Int),
) {
  let sql =
    "
INSERT INTO access_credentials(digest, principal_id, state, kind, issued_at_ms, expires_at_ms)
VALUES (?, ?, 'active', 'browser', ?, ?)"
  #(sql, [
    dev.ParamString(digest),
    dev.ParamString(principal_id),
    dev.ParamNullable(option.map(issued_at_ms, fn(v) { dev.ParamInt(v) })),
    dev.ParamNullable(option.map(expires_at_ms, fn(v) { dev.ParamInt(v) })),
  ])
}

pub fn insert_access_login_from(
  digest digest: String,
  principal_id principal_id: String,
  issued_at_ms issued_at_ms: Option(Int),
  expires_at_ms expires_at_ms: Option(Int),
  issued_by issued_by: Option(String),
) {
  let sql =
    "INSERT INTO access_credentials(digest, principal_id, state, kind, issued_at_ms, expires_at_ms, issued_by)
VALUES (?, ?, 'active', 'browser', ?, ?, ?)"
  #(sql, [
    dev.ParamString(digest),
    dev.ParamString(principal_id),
    dev.ParamNullable(option.map(issued_at_ms, fn(v) { dev.ParamInt(v) })),
    dev.ParamNullable(option.map(expires_at_ms, fn(v) { dev.ParamInt(v) })),
    dev.ParamNullable(option.map(issued_by, fn(v) { dev.ParamString(v) })),
  ])
}

pub type PrincipalLogins {
  PrincipalLogins(
    digest: String,
    issued_at_ms: Option(Int),
    last_resumed_ms: Option(Int),
    expires_at_ms: Option(Int),
    issued_by: Option(String),
  )
}

pub fn principal_logins(
  principal_id principal_id: String,
  expires_at_ms expires_at_ms: Option(Int),
  digest digest: String,
) {
  let sql =
    "SELECT digest, issued_at_ms, last_resumed_ms, expires_at_ms, issued_by FROM access_credentials
WHERE principal_id = ? AND kind = 'browser' AND state = 'active'
  AND (expires_at_ms IS NULL OR expires_at_ms > ?)
  AND substr(digest, 1, 16) > ?
ORDER BY digest LIMIT 101"
  #(
    sql,
    [
      dev.ParamString(principal_id),
      dev.ParamNullable(option.map(expires_at_ms, fn(v) { dev.ParamInt(v) })),
      dev.ParamString(digest),
    ],
    principal_logins_decoder(),
  )
}

pub fn principal_logins_decoder() -> decode.Decoder(PrincipalLogins) {
  use digest <- decode.field(0, decode.string)
  use issued_at_ms <- decode.field(1, decode.optional(decode.int))
  use last_resumed_ms <- decode.field(2, decode.optional(decode.int))
  use expires_at_ms <- decode.field(3, decode.optional(decode.int))
  use issued_by <- decode.field(4, decode.optional(decode.string))
  decode.success(PrincipalLogins(
    digest:,
    issued_at_ms:,
    last_resumed_ms:,
    expires_at_ms:,
    issued_by:,
  ))
}

pub type PrincipalLoginCount {
  PrincipalLoginCount(count: Int)
}

pub fn principal_login_count(
  principal_id principal_id: String,
  expires_at_ms expires_at_ms: Option(Int),
) {
  let sql =
    "SELECT COUNT(*) FROM access_credentials
WHERE principal_id = ? AND kind = 'browser' AND state = 'active'
  AND (expires_at_ms IS NULL OR expires_at_ms > ?)"
  #(
    sql,
    [
      dev.ParamString(principal_id),
      dev.ParamNullable(option.map(expires_at_ms, fn(v) { dev.ParamInt(v) })),
    ],
    principal_login_count_decoder(),
  )
}

pub fn principal_login_count_decoder() -> decode.Decoder(PrincipalLoginCount) {
  use count <- decode.field(0, decode.int)
  decode.success(PrincipalLoginCount(count:))
}

pub type PrincipalLoginByFingerprint {
  PrincipalLoginByFingerprint(digest: String, state: String)
}

pub fn principal_login_by_fingerprint(
  principal_id principal_id: String,
  digest digest: String,
) {
  let sql =
    "SELECT digest, state FROM access_credentials
WHERE principal_id = ? AND kind = 'browser' AND substr(digest, 1, 16) = ?
LIMIT 2"
  #(
    sql,
    [dev.ParamString(principal_id), dev.ParamString(digest)],
    principal_login_by_fingerprint_decoder(),
  )
}

pub fn principal_login_by_fingerprint_decoder() -> decode.Decoder(
  PrincipalLoginByFingerprint,
) {
  use digest <- decode.field(0, decode.string)
  use state <- decode.field(1, decode.string)
  decode.success(PrincipalLoginByFingerprint(digest:, state:))
}

pub fn revoke_principal_logins(principal_id principal_id: String) {
  let sql =
    "UPDATE access_credentials SET state = 'revoked'
WHERE principal_id = ? AND kind = 'browser' AND state = 'active'"
  #(sql, [dev.ParamString(principal_id)])
}

pub type ActiveLoginCount {
  ActiveLoginCount(count: Int)
}

pub fn active_login_count() {
  let sql =
    "SELECT COUNT(*) FROM access_credentials WHERE kind = 'browser' AND state = 'active'"
  #(sql, [], active_login_count_decoder())
}

pub fn active_login_count_decoder() -> decode.Decoder(ActiveLoginCount) {
  use count <- decode.field(0, decode.int)
  decode.success(ActiveLoginCount(count:))
}

pub fn revoke_all_logins() {
  let sql =
    "UPDATE access_credentials SET state = 'revoked' WHERE kind = 'browser' AND state = 'active'"
  #(sql, [])
}

pub type LoginResumedAt {
  LoginResumedAt(last_resumed_ms: Option(Int))
}

pub fn login_resumed_at(digest digest: String) {
  let sql =
    "SELECT last_resumed_ms FROM access_credentials WHERE digest = ? AND kind = 'browser'"
  #(sql, [dev.ParamString(digest)], login_resumed_at_decoder())
}

pub fn login_resumed_at_decoder() -> decode.Decoder(LoginResumedAt) {
  use last_resumed_ms <- decode.field(0, decode.optional(decode.int))
  decode.success(LoginResumedAt(last_resumed_ms:))
}

pub fn stamp_login_resumed(
  last_resumed_ms last_resumed_ms: Option(Int),
  digest digest: String,
) {
  let sql =
    "UPDATE access_credentials SET last_resumed_ms = ? WHERE digest = ? AND kind = 'browser'"
  #(sql, [
    dev.ParamNullable(option.map(last_resumed_ms, fn(v) { dev.ParamInt(v) })),
    dev.ParamString(digest),
  ])
}

pub type SessionMembers {
  SessionMembers(principal_id: String, display_name: String, role: String)
}

pub fn session_members(
  session_id session_id: String,
  principal_id principal_id: String,
) {
  let sql =
    "SELECT m.principal_id, p.display_name, m.role
FROM access_memberships AS m
JOIN access_principals AS p ON p.principal_id = m.principal_id
WHERE m.session_id = ? AND m.principal_id > ?
ORDER BY m.principal_id LIMIT 101"
  #(
    sql,
    [dev.ParamString(session_id), dev.ParamString(principal_id)],
    session_members_decoder(),
  )
}

pub fn session_members_decoder() -> decode.Decoder(SessionMembers) {
  use principal_id <- decode.field(0, decode.string)
  use display_name <- decode.field(1, decode.string)
  use role <- decode.field(2, decode.string)
  decode.success(SessionMembers(principal_id:, display_name:, role:))
}

pub fn initialize_catalogue_revision() {
  let sql =
    "
INSERT INTO catalogue_meta (singleton, revision) VALUES (1, 0)"
  #(sql, [])
}

pub type FindRegistrations {
  FindRegistrations(
    session_id: String,
    path: String,
    workspace: String,
    name: String,
    configuration: String,
    created_at: Int,
    request_key: String,
    state: String,
    profile: String,
  )
}

pub fn find_registrations(
  session_id session_id: String,
  request_key request_key: String,
  path path: String,
) {
  let sql =
    "SELECT session_id, path, workspace, name, configuration, created_at, request_key, state, profile
FROM catalogue_sessions
WHERE session_id = ? OR request_key = ? OR path = ?"
  #(
    sql,
    [
      dev.ParamString(session_id),
      dev.ParamString(request_key),
      dev.ParamString(path),
    ],
    find_registrations_decoder(),
  )
}

pub fn find_registrations_decoder() -> decode.Decoder(FindRegistrations) {
  use session_id <- decode.field(0, decode.string)
  use path <- decode.field(1, decode.string)
  use workspace <- decode.field(2, decode.string)
  use name <- decode.field(3, decode.string)
  use configuration <- decode.field(4, decode.string)
  use created_at <- decode.field(5, decode.int)
  use request_key <- decode.field(6, decode.string)
  use state <- decode.field(7, decode.string)
  use profile <- decode.field(8, decode.string)
  decode.success(FindRegistrations(
    session_id:,
    path:,
    workspace:,
    name:,
    configuration:,
    created_at:,
    request_key:,
    state:,
    profile:,
  ))
}

pub fn insert_registration(
  session_id session_id: String,
  path path: String,
  workspace workspace: String,
  name name: String,
  configuration configuration: String,
  created_at created_at: Int,
  request_key request_key: String,
  profile profile: String,
) {
  let sql =
    "INSERT INTO catalogue_sessions
  (session_id, path, workspace, name, configuration, created_at, request_key, state, profile)
VALUES (?, ?, ?, ?, ?, ?, ?, 'reserved', ?)"
  #(sql, [
    dev.ParamString(session_id),
    dev.ParamString(path),
    dev.ParamString(workspace),
    dev.ParamString(name),
    dev.ParamString(configuration),
    dev.ParamInt(created_at),
    dev.ParamString(request_key),
    dev.ParamString(profile),
  ])
}

pub fn confirm_registration(session_id session_id: String) {
  let sql = "UPDATE catalogue_sessions SET state = 'saved' WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)])
}

pub type RegistrationDisplayName {
  RegistrationDisplayName(name: String)
}

pub fn registration_display_name(session_id session_id: String) {
  let sql = "SELECT name FROM catalogue_session_names WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)], registration_display_name_decoder())
}

pub fn registration_display_name_decoder() -> decode.Decoder(
  RegistrationDisplayName,
) {
  use name <- decode.field(0, decode.string)
  decode.success(RegistrationDisplayName(name:))
}

pub type RegistrationSubtitle {
  RegistrationSubtitle(subtitle: String)
}

pub fn registration_subtitle(session_id session_id: String) {
  let sql =
    "SELECT subtitle FROM catalogue_session_subtitles WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)], registration_subtitle_decoder())
}

pub fn registration_subtitle_decoder() -> decode.Decoder(RegistrationSubtitle) {
  use subtitle <- decode.field(0, decode.string)
  decode.success(RegistrationSubtitle(subtitle:))
}

pub fn insert_registration_subtitle(
  session_id session_id: String,
  subtitle subtitle: String,
) {
  let sql =
    "INSERT INTO catalogue_session_subtitles (session_id, subtitle) VALUES (?, ?)
ON CONFLICT(session_id) DO NOTHING"
  #(sql, [dev.ParamString(session_id), dev.ParamString(subtitle)])
}

pub fn delete_session_subtitle(session_id session_id: String) {
  let sql = "DELETE FROM catalogue_session_subtitles WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)])
}

pub fn set_registration_display_name(
  session_id session_id: String,
  name name: String,
) {
  let sql =
    "INSERT INTO catalogue_session_names (session_id, name) VALUES (?, ?)
ON CONFLICT(session_id) DO UPDATE SET name = excluded.name"
  #(sql, [dev.ParamString(session_id), dev.ParamString(name)])
}

pub type RegistrationPage {
  RegistrationPage(
    session_id: String,
    path: String,
    workspace: String,
    name: String,
    configuration: String,
    created_at: Int,
    request_key: String,
    state: String,
    profile: String,
    subtitle: Option(String),
  )
}

pub fn registration_page(after after: String, archived archived: Int) {
  let sql =
    "SELECT s.session_id, s.path, s.workspace, CAST(COALESCE(n.name, s.name) AS TEXT) AS name,
       s.configuration, s.created_at, s.request_key, s.state, s.profile, t.subtitle
FROM catalogue_sessions AS s
LEFT JOIN catalogue_session_names AS n ON n.session_id = s.session_id
LEFT JOIN catalogue_session_subtitles AS t ON t.session_id = s.session_id
WHERE s.session_id > ?1
  AND EXISTS (SELECT 1 FROM catalogue_session_archives AS a
              WHERE a.session_id = s.session_id) = CAST(?2 AS INTEGER)
ORDER BY s.session_id
LIMIT 100"
  #(
    sql,
    [dev.ParamString(after), dev.ParamInt(archived)],
    registration_page_decoder(),
  )
}

pub fn registration_page_decoder() -> decode.Decoder(RegistrationPage) {
  use session_id <- decode.field(0, decode.string)
  use path <- decode.field(1, decode.string)
  use workspace <- decode.field(2, decode.string)
  use name <- decode.field(3, decode.string)
  use configuration <- decode.field(4, decode.string)
  use created_at <- decode.field(5, decode.int)
  use request_key <- decode.field(6, decode.string)
  use state <- decode.field(7, decode.string)
  use profile <- decode.field(8, decode.string)
  use subtitle <- decode.field(9, decode.optional(decode.string))
  decode.success(RegistrationPage(
    session_id:,
    path:,
    workspace:,
    name:,
    configuration:,
    created_at:,
    request_key:,
    state:,
    profile:,
    subtitle:,
  ))
}

pub type CatalogueRevision {
  CatalogueRevision(revision: Int)
}

pub fn catalogue_revision() {
  let sql = "SELECT revision FROM catalogue_meta WHERE singleton = 1"
  #(sql, [], catalogue_revision_decoder())
}

pub fn catalogue_revision_decoder() -> decode.Decoder(CatalogueRevision) {
  use revision <- decode.field(0, decode.int)
  decode.success(CatalogueRevision(revision:))
}

pub type MemberRegistrationPage {
  MemberRegistrationPage(
    session_id: String,
    path: String,
    workspace: String,
    name: String,
    configuration: String,
    created_at: Int,
    request_key: String,
    state: String,
    profile: String,
    subtitle: Option(String),
  )
}

pub fn member_registration_page(
  principal_id principal_id: String,
  session_id session_id: String,
) {
  let sql =
    "SELECT s.session_id, s.path, s.workspace, CAST(COALESCE(n.name, s.name) AS TEXT) AS name, s.configuration,
       s.created_at, s.request_key, s.state, s.profile, t.subtitle
FROM access_memberships AS m
JOIN catalogue_sessions AS s ON s.session_id = m.session_id
LEFT JOIN catalogue_session_names AS n ON n.session_id = s.session_id
LEFT JOIN catalogue_session_subtitles AS t ON t.session_id = s.session_id
WHERE m.principal_id = ? AND s.session_id > ?
  AND m.role IN ('operator', 'observer')
  AND NOT EXISTS (SELECT 1 FROM catalogue_session_archives AS a
                  WHERE a.session_id = s.session_id)
ORDER BY s.session_id
LIMIT 100"
  #(
    sql,
    [dev.ParamString(principal_id), dev.ParamString(session_id)],
    member_registration_page_decoder(),
  )
}

pub fn member_registration_page_decoder() -> decode.Decoder(
  MemberRegistrationPage,
) {
  use session_id <- decode.field(0, decode.string)
  use path <- decode.field(1, decode.string)
  use workspace <- decode.field(2, decode.string)
  use name <- decode.field(3, decode.string)
  use configuration <- decode.field(4, decode.string)
  use created_at <- decode.field(5, decode.int)
  use request_key <- decode.field(6, decode.string)
  use state <- decode.field(7, decode.string)
  use profile <- decode.field(8, decode.string)
  use subtitle <- decode.field(9, decode.optional(decode.string))
  decode.success(MemberRegistrationPage(
    session_id:,
    path:,
    workspace:,
    name:,
    configuration:,
    created_at:,
    request_key:,
    state:,
    profile:,
    subtitle:,
  ))
}

pub fn increment_catalogue_revision() {
  let sql =
    "UPDATE catalogue_meta SET revision = revision + 1 WHERE singleton = 1"
  #(sql, [])
}

pub type WorkspaceDefault {
  WorkspaceDefault(session_id: String)
}

pub fn workspace_default(workspace workspace: String) {
  let sql = "SELECT session_id FROM catalogue_defaults WHERE workspace = ?"
  #(sql, [dev.ParamString(workspace)], workspace_default_decoder())
}

pub fn workspace_default_decoder() -> decode.Decoder(WorkspaceDefault) {
  use session_id <- decode.field(0, decode.string)
  decode.success(WorkspaceDefault(session_id:))
}

pub fn set_workspace_default(
  workspace workspace: String,
  session_id session_id: String,
) {
  let sql =
    "INSERT INTO catalogue_defaults (workspace, session_id) VALUES (?, ?)
ON CONFLICT(workspace) DO UPDATE SET session_id = excluded.session_id"
  #(sql, [dev.ParamString(workspace), dev.ParamString(session_id)])
}

pub fn delete_session_default(session_id session_id: String) {
  let sql = "DELETE FROM catalogue_defaults WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)])
}

pub fn delete_session_memberships(session_id session_id: String) {
  let sql = "DELETE FROM access_memberships WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)])
}

pub fn delete_session_domain(session_id session_id: String) {
  let sql = "DELETE FROM catalogue_domain_sessions WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)])
}

pub fn delete_session_display_name(session_id session_id: String) {
  let sql = "DELETE FROM catalogue_session_names WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)])
}

pub fn delete_registration(session_id session_id: String) {
  let sql = "DELETE FROM catalogue_sessions WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)])
}

pub type SessionArchive {
  SessionArchive(session_id: String)
}

pub fn session_archive(session_id session_id: String) {
  let sql =
    "SELECT session_id FROM catalogue_session_archives WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)], session_archive_decoder())
}

pub fn session_archive_decoder() -> decode.Decoder(SessionArchive) {
  use session_id <- decode.field(0, decode.string)
  decode.success(SessionArchive(session_id:))
}

pub fn archive_session(session_id session_id: String) {
  let sql = "INSERT INTO catalogue_session_archives (session_id) VALUES (?)"
  #(sql, [dev.ParamString(session_id)])
}

pub fn restore_session(session_id session_id: String) {
  let sql = "DELETE FROM catalogue_session_archives WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)])
}

pub type RecentFolders {
  RecentFolders(seq: Int, workspace: String)
}

pub fn recent_folders() {
  let sql =
    "SELECT seq, workspace FROM catalogue_recent_folders ORDER BY seq DESC"
  #(sql, [], recent_folders_decoder())
}

pub fn recent_folders_decoder() -> decode.Decoder(RecentFolders) {
  use seq <- decode.field(0, decode.int)
  use workspace <- decode.field(1, decode.string)
  decode.success(RecentFolders(seq:, workspace:))
}

pub fn insert_recent_folder(workspace workspace: String) {
  let sql = "INSERT INTO catalogue_recent_folders (workspace) VALUES (?)"
  #(sql, [dev.ParamString(workspace)])
}

pub fn delete_recent_folder(workspace workspace: String) {
  let sql = "DELETE FROM catalogue_recent_folders WHERE workspace = ?"
  #(sql, [dev.ParamString(workspace)])
}

pub fn forget_recent_folder(seq seq: Int) {
  let sql = "DELETE FROM catalogue_recent_folders WHERE seq = ?"
  #(sql, [dev.ParamInt(seq)])
}

pub fn trim_recent_folders(limit limit: Int) {
  let sql =
    "DELETE FROM catalogue_recent_folders
WHERE seq NOT IN (SELECT seq FROM catalogue_recent_folders ORDER BY seq DESC LIMIT ?)"
  #(sql, [dev.ParamInt(limit)])
}

pub type DomainById {
  DomainById(
    domain_id: String,
    scope: String,
    scope_key: String,
    workspace: String,
    configuration: String,
    memory_path: String,
    index_path: String,
    digest_path: String,
  )
}

pub fn domain_by_id(domain_id domain_id: String) {
  let sql =
    "
SELECT domain_id, scope, scope_key, workspace, configuration, memory_path, index_path, digest_path
FROM catalogue_domains WHERE domain_id = ?"
  #(sql, [dev.ParamString(domain_id)], domain_by_id_decoder())
}

pub fn domain_by_id_decoder() -> decode.Decoder(DomainById) {
  use domain_id <- decode.field(0, decode.string)
  use scope <- decode.field(1, decode.string)
  use scope_key <- decode.field(2, decode.string)
  use workspace <- decode.field(3, decode.string)
  use configuration <- decode.field(4, decode.string)
  use memory_path <- decode.field(5, decode.string)
  use index_path <- decode.field(6, decode.string)
  use digest_path <- decode.field(7, decode.string)
  decode.success(DomainById(
    domain_id:,
    scope:,
    scope_key:,
    workspace:,
    configuration:,
    memory_path:,
    index_path:,
    digest_path:,
  ))
}

pub type DomainForSession {
  DomainForSession(
    domain_id: String,
    scope: String,
    scope_key: String,
    workspace: String,
    configuration: String,
    memory_path: String,
    index_path: String,
    digest_path: String,
  )
}

pub fn domain_for_session(session_id session_id: String) {
  let sql =
    "SELECT d.domain_id, d.scope, d.scope_key, d.workspace, d.configuration, d.memory_path, d.index_path, d.digest_path
FROM catalogue_domain_sessions AS s JOIN catalogue_domains AS d ON d.domain_id = s.domain_id
WHERE s.session_id = ?"
  #(sql, [dev.ParamString(session_id)], domain_for_session_decoder())
}

pub fn domain_for_session_decoder() -> decode.Decoder(DomainForSession) {
  use domain_id <- decode.field(0, decode.string)
  use scope <- decode.field(1, decode.string)
  use scope_key <- decode.field(2, decode.string)
  use workspace <- decode.field(3, decode.string)
  use configuration <- decode.field(4, decode.string)
  use memory_path <- decode.field(5, decode.string)
  use index_path <- decode.field(6, decode.string)
  use digest_path <- decode.field(7, decode.string)
  decode.success(DomainForSession(
    domain_id:,
    scope:,
    scope_key:,
    workspace:,
    configuration:,
    memory_path:,
    index_path:,
    digest_path:,
  ))
}

pub type DomainPathConflicts {
  DomainPathConflicts(domain_id: String)
}

pub fn domain_path_conflicts(
  memory memory: String,
  search search: String,
  digest digest: String,
) {
  let sql =
    "SELECT domain_id FROM catalogue_domains
WHERE memory_path IN (?1, ?2, ?3)
OR index_path IN (?1, ?2, ?3)
OR digest_path IN (?1, ?2, ?3) LIMIT 2"
  #(
    sql,
    [dev.ParamString(memory), dev.ParamString(search), dev.ParamString(digest)],
    domain_path_conflicts_decoder(),
  )
}

pub fn domain_path_conflicts_decoder() -> decode.Decoder(DomainPathConflicts) {
  use domain_id <- decode.field(0, decode.string)
  decode.success(DomainPathConflicts(domain_id:))
}

pub fn insert_domain(
  domain_id domain_id: String,
  scope scope: String,
  scope_key scope_key: String,
  workspace workspace: String,
  configuration configuration: String,
  memory_path memory_path: String,
  index_path index_path: String,
  digest_path digest_path: String,
) {
  let sql =
    "INSERT INTO catalogue_domains(domain_id, scope, scope_key, workspace, configuration, memory_path, index_path, digest_path)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)"
  #(sql, [
    dev.ParamString(domain_id),
    dev.ParamString(scope),
    dev.ParamString(scope_key),
    dev.ParamString(workspace),
    dev.ParamString(configuration),
    dev.ParamString(memory_path),
    dev.ParamString(index_path),
    dev.ParamString(digest_path),
  ])
}

pub fn bind_session_domain(
  session_id session_id: String,
  domain_id domain_id: String,
) {
  let sql =
    "INSERT INTO catalogue_domain_sessions(session_id, domain_id) VALUES (?, ?)
ON CONFLICT(session_id) DO UPDATE SET domain_id = excluded.domain_id"
  #(sql, [dev.ParamString(session_id), dev.ParamString(domain_id)])
}

pub type DomainSources {
  DomainSources(session_id: String)
}

pub fn domain_sources(
  domain_id domain_id: String,
  session_id session_id: String,
) {
  let sql =
    "SELECT s.session_id FROM catalogue_domain_sessions AS s
JOIN catalogue_sessions AS r ON r.session_id = s.session_id
WHERE s.domain_id = ? AND s.session_id > ? AND r.state = 'saved'
ORDER BY s.session_id LIMIT 100"
  #(
    sql,
    [dev.ParamString(domain_id), dev.ParamString(session_id)],
    domain_sources_decoder(),
  )
}

pub fn domain_sources_decoder() -> decode.Decoder(DomainSources) {
  use session_id <- decode.field(0, decode.string)
  decode.success(DomainSources(session_id:))
}

pub type DomainPage {
  DomainPage(
    domain_id: String,
    scope: String,
    scope_key: String,
    workspace: String,
    configuration: String,
    memory_path: String,
    index_path: String,
    digest_path: String,
  )
}

pub fn domain_page(domain_id domain_id: String) {
  let sql =
    "SELECT domain_id, scope, scope_key, workspace, configuration, memory_path, index_path, digest_path
FROM catalogue_domains WHERE domain_id > ? ORDER BY domain_id LIMIT 100"
  #(sql, [dev.ParamString(domain_id)], domain_page_decoder())
}

pub fn domain_page_decoder() -> decode.Decoder(DomainPage) {
  use domain_id <- decode.field(0, decode.string)
  use scope <- decode.field(1, decode.string)
  use scope_key <- decode.field(2, decode.string)
  use workspace <- decode.field(3, decode.string)
  use configuration <- decode.field(4, decode.string)
  use memory_path <- decode.field(5, decode.string)
  use index_path <- decode.field(6, decode.string)
  use digest_path <- decode.field(7, decode.string)
  decode.success(DomainPage(
    domain_id:,
    scope:,
    scope_key:,
    workspace:,
    configuration:,
    memory_path:,
    index_path:,
    digest_path:,
  ))
}

pub type HistorySourceHeader {
  HistorySourceHeader(metadata_bytes: Int, next_seq: Option(Int))
}

pub fn history_source_header() {
  let sql =
    "
SELECT CAST(COALESCE(length(metadata), 0) AS INTEGER) AS metadata_bytes,
  next_seq FROM session LIMIT 2"
  #(sql, [], history_source_header_decoder())
}

pub fn history_source_header_decoder() -> decode.Decoder(HistorySourceHeader) {
  use metadata_bytes <- decode.field(0, decode.int)
  use next_seq <- decode.field(1, decode.optional(decode.int))
  decode.success(HistorySourceHeader(metadata_bytes:, next_seq:))
}

pub type HistorySourceMetadata {
  HistorySourceMetadata(metadata: Option(BitArray))
}

pub fn history_source_metadata() {
  let sql = "SELECT metadata FROM session LIMIT 2"
  #(sql, [], history_source_metadata_decoder())
}

pub fn history_source_metadata_decoder() -> decode.Decoder(
  HistorySourceMetadata,
) {
  use metadata <- decode.field(0, decode.optional(decode.bit_array))
  decode.success(HistorySourceMetadata(metadata:))
}

pub type HistorySourceEntry {
  HistorySourceEntry(seq: Option(Int), payload_bytes: Option(Int))
}

pub fn history_source_entry(
  entry_id entry_id: String,
  before_seq before_seq: Option(Int),
) {
  let sql =
    "SELECT seq, length(payload) AS payload_bytes FROM entries
WHERE id = ?1 AND seq < ?2 LIMIT 2"
  #(
    sql,
    [
      dev.ParamString(entry_id),
      dev.ParamNullable(option.map(before_seq, fn(v) { dev.ParamInt(v) })),
    ],
    history_source_entry_decoder(),
  )
}

pub fn history_source_entry_decoder() -> decode.Decoder(HistorySourceEntry) {
  use seq <- decode.field(0, decode.optional(decode.int))
  use payload_bytes <- decode.field(1, decode.optional(decode.int))
  decode.success(HistorySourceEntry(seq:, payload_bytes:))
}

pub type SnapshotSession {
  SnapshotSession(
    next_seq: Option(Int),
    message_count: Option(Int),
    usage_bytes: Option(Int),
  )
}

pub fn snapshot_session() {
  let sql =
    "SELECT next_seq, message_count, length(usage_payload) AS usage_bytes
FROM session LIMIT 2"
  #(sql, [], snapshot_session_decoder())
}

pub fn snapshot_session_decoder() -> decode.Decoder(SnapshotSession) {
  use next_seq <- decode.field(0, decode.optional(decode.int))
  use message_count <- decode.field(1, decode.optional(decode.int))
  use usage_bytes <- decode.field(2, decode.optional(decode.int))
  decode.success(SnapshotSession(next_seq:, message_count:, usage_bytes:))
}

pub type SnapshotUsageValue {
  SnapshotUsageValue(usage_payload: Option(BitArray))
}

pub fn snapshot_usage_value() {
  let sql = "SELECT usage_payload FROM session LIMIT 2"
  #(sql, [], snapshot_usage_value_decoder())
}

pub fn snapshot_usage_value_decoder() -> decode.Decoder(SnapshotUsageValue) {
  use usage_payload <- decode.field(0, decode.optional(decode.bit_array))
  decode.success(SnapshotUsageValue(usage_payload:))
}

pub type SnapshotRegisterHeaders {
  SnapshotRegisterHeaders(key: String, seq: Int, value_bytes: Option(Int))
}

pub fn snapshot_register_headers(
  namespace namespace: String,
  prefix prefix: String,
  prefix_upper prefix_upper: String,
  field field: String,
  expected expected: String,
) {
  let sql =
    "SELECT key, seq, length(value) AS value_bytes
FROM registers
WHERE ns = ?1 AND key >= ?2 AND key <
  CASE WHEN CAST(?3 AS TEXT) = '' THEN CAST('' AS BLOB)
  ELSE CAST(?3 AS TEXT) END
AND CASE
  WHEN CAST(?4 AS TEXT) = '' THEN 1
  WHEN length(value) > 1048576 THEN 1
  WHEN NOT json_valid(CAST(value AS TEXT)) THEN 1
  WHEN json_type(CAST(value AS TEXT), '$.' || ?4) IS NOT 'text' THEN 1
  ELSE json_extract(CAST(value AS TEXT), '$.' || ?4) = CAST(?5 AS TEXT)
END
ORDER BY key LIMIT 1025"
  #(
    sql,
    [
      dev.ParamString(namespace),
      dev.ParamString(prefix),
      dev.ParamString(prefix_upper),
      dev.ParamString(field),
      dev.ParamString(expected),
    ],
    snapshot_register_headers_decoder(),
  )
}

pub fn snapshot_register_headers_decoder() -> decode.Decoder(
  SnapshotRegisterHeaders,
) {
  use key <- decode.field(0, decode.string)
  use seq <- decode.field(1, decode.int)
  use value_bytes <- decode.field(2, decode.optional(decode.int))
  decode.success(SnapshotRegisterHeaders(key:, seq:, value_bytes:))
}

pub type SnapshotRegisterBudget {
  SnapshotRegisterBudget(cell_count: Int, total_bytes: Int)
}

pub fn snapshot_register_budget(
  namespace namespace: String,
  prefix prefix: String,
  prefix_upper prefix_upper: String,
  field field: String,
  expected expected: String,
) {
  let sql =
    "SELECT COUNT(*) AS cell_count,
  CAST(COALESCE(SUM(length(value) + length(CAST(key AS BLOB)) + length(CAST(ns AS BLOB)) + 65), 0) AS INTEGER) AS total_bytes
FROM registers
WHERE ns = ?1 AND key >= ?2 AND key <
  CASE WHEN CAST(?3 AS TEXT) = '' THEN CAST('' AS BLOB)
  ELSE CAST(?3 AS TEXT) END
AND CASE
  WHEN CAST(?4 AS TEXT) = '' THEN 1
  WHEN length(value) > 1048576 THEN 1
  WHEN NOT json_valid(CAST(value AS TEXT)) THEN 1
  WHEN json_type(CAST(value AS TEXT), '$.' || ?4) IS NOT 'text' THEN 1
  ELSE json_extract(CAST(value AS TEXT), '$.' || ?4) = CAST(?5 AS TEXT)
END"
  #(
    sql,
    [
      dev.ParamString(namespace),
      dev.ParamString(prefix),
      dev.ParamString(prefix_upper),
      dev.ParamString(field),
      dev.ParamString(expected),
    ],
    snapshot_register_budget_decoder(),
  )
}

pub fn snapshot_register_budget_decoder() -> decode.Decoder(
  SnapshotRegisterBudget,
) {
  use cell_count <- decode.field(0, decode.int)
  use total_bytes <- decode.field(1, decode.int)
  decode.success(SnapshotRegisterBudget(cell_count:, total_bytes:))
}

pub type SnapshotRegisterValue {
  SnapshotRegisterValue(value: BitArray)
}

pub fn snapshot_register_value(
  namespace namespace: String,
  key key: String,
  seq seq: Int,
) {
  let sql =
    "SELECT value FROM registers
WHERE ns = ?1 AND key = ?2 AND seq = ?3"
  #(
    sql,
    [dev.ParamString(namespace), dev.ParamString(key), dev.ParamInt(seq)],
    snapshot_register_value_decoder(),
  )
}

pub fn snapshot_register_value_decoder() -> decode.Decoder(
  SnapshotRegisterValue,
) {
  use value <- decode.field(0, decode.bit_array)
  decode.success(SnapshotRegisterValue(value:))
}

pub type SnapshotRegisterPageBudget {
  SnapshotRegisterPageBudget(cell_count: Int, total_bytes: Int)
}

pub fn snapshot_register_page_budget(
  namespace namespace: String,
  prefix prefix: String,
  after_key after_key: String,
  prefix_upper prefix_upper: String,
  page_size page_size: Int,
) {
  let sql =
    "SELECT COUNT(*) AS cell_count,
  CAST(COALESCE(SUM(value_bytes + key_bytes + ns_bytes + 65), 0) AS INTEGER) AS total_bytes
FROM (
  SELECT length(value) AS value_bytes, length(CAST(key AS BLOB)) AS key_bytes,
    length(CAST(ns AS BLOB)) AS ns_bytes
  FROM registers
  WHERE ns = ?1
  AND key >= MAX(CAST(?2 AS TEXT), CAST(?3 AS TEXT))
  AND key <> ?3 AND key <
    CASE WHEN CAST(?4 AS TEXT) = '' THEN CAST('' AS BLOB)
    ELSE CAST(?4 AS TEXT) END
  ORDER BY key LIMIT ?5
)"
  #(
    sql,
    [
      dev.ParamString(namespace),
      dev.ParamString(prefix),
      dev.ParamString(after_key),
      dev.ParamString(prefix_upper),
      dev.ParamInt(page_size),
    ],
    snapshot_register_page_budget_decoder(),
  )
}

pub fn snapshot_register_page_budget_decoder() -> decode.Decoder(
  SnapshotRegisterPageBudget,
) {
  use cell_count <- decode.field(0, decode.int)
  use total_bytes <- decode.field(1, decode.int)
  decode.success(SnapshotRegisterPageBudget(cell_count:, total_bytes:))
}

pub type SnapshotRegisterPageHeaders {
  SnapshotRegisterPageHeaders(key: String, seq: Int, value_bytes: Option(Int))
}

pub fn snapshot_register_page_headers(
  namespace namespace: String,
  prefix prefix: String,
  after_key after_key: String,
  prefix_upper prefix_upper: String,
  page_size page_size: Int,
) {
  let sql =
    "SELECT key, seq, length(value) AS value_bytes
FROM registers
WHERE ns = ?1
AND key >= MAX(CAST(?2 AS TEXT), CAST(?3 AS TEXT))
AND key <> ?3 AND key <
  CASE WHEN CAST(?4 AS TEXT) = '' THEN CAST('' AS BLOB)
  ELSE CAST(?4 AS TEXT) END
ORDER BY key LIMIT ?5"
  #(
    sql,
    [
      dev.ParamString(namespace),
      dev.ParamString(prefix),
      dev.ParamString(after_key),
      dev.ParamString(prefix_upper),
      dev.ParamInt(page_size),
    ],
    snapshot_register_page_headers_decoder(),
  )
}

pub fn snapshot_register_page_headers_decoder() -> decode.Decoder(
  SnapshotRegisterPageHeaders,
) {
  use key <- decode.field(0, decode.string)
  use seq <- decode.field(1, decode.int)
  use value_bytes <- decode.field(2, decode.optional(decode.int))
  decode.success(SnapshotRegisterPageHeaders(key:, seq:, value_bytes:))
}

pub type SnapshotRegisterHeader {
  SnapshotRegisterHeader(seq: Int, value_bytes: Option(Int))
}

pub fn snapshot_register_header(namespace namespace: String, key key: String) {
  let sql =
    "SELECT seq, length(value) AS value_bytes FROM registers
WHERE ns = ?1 AND key = ?2"
  #(
    sql,
    [dev.ParamString(namespace), dev.ParamString(key)],
    snapshot_register_header_decoder(),
  )
}

pub fn snapshot_register_header_decoder() -> decode.Decoder(
  SnapshotRegisterHeader,
) {
  use seq <- decode.field(0, decode.int)
  use value_bytes <- decode.field(1, decode.optional(decode.int))
  decode.success(SnapshotRegisterHeader(seq:, value_bytes:))
}

pub type SnapshotEntryPage {
  SnapshotEntryPage(id: String, seq: Option(Int), payload_bytes: Option(Int))
}

pub fn snapshot_entry_page(
  after_seq after_seq: Option(Int),
  before_seq before_seq: Option(Int),
  page_size page_size: Int,
) {
  let sql =
    "SELECT CAST(CASE WHEN length(CAST(id AS BLOB)) = 36 THEN id ELSE '' END AS TEXT) AS id,
  seq, length(payload) AS payload_bytes FROM entries
WHERE seq > ?1 AND seq < ?2
ORDER BY seq ASC LIMIT ?3"
  #(
    sql,
    [
      dev.ParamNullable(option.map(after_seq, fn(v) { dev.ParamInt(v) })),
      dev.ParamNullable(option.map(before_seq, fn(v) { dev.ParamInt(v) })),
      dev.ParamInt(page_size),
    ],
    snapshot_entry_page_decoder(),
  )
}

pub fn snapshot_entry_page_decoder() -> decode.Decoder(SnapshotEntryPage) {
  use id <- decode.field(0, decode.string)
  use seq <- decode.field(1, decode.optional(decode.int))
  use payload_bytes <- decode.field(2, decode.optional(decode.int))
  decode.success(SnapshotEntryPage(id:, seq:, payload_bytes:))
}

pub type SnapshotRecentEntries {
  SnapshotRecentEntries(
    id: String,
    seq: Option(Int),
    payload_bytes: Option(Int),
  )
}

pub fn snapshot_recent_entries(
  before_seq before_seq: Option(Int),
  page_size page_size: Int,
) {
  let sql =
    "SELECT CAST(CASE WHEN length(CAST(id AS BLOB)) = 36 THEN id ELSE '' END AS TEXT) AS id,
  seq, length(payload) AS payload_bytes FROM entries
WHERE seq < ?1 ORDER BY seq DESC LIMIT ?2"
  #(
    sql,
    [
      dev.ParamNullable(option.map(before_seq, fn(v) { dev.ParamInt(v) })),
      dev.ParamInt(page_size),
    ],
    snapshot_recent_entries_decoder(),
  )
}

pub fn snapshot_recent_entries_decoder() -> decode.Decoder(
  SnapshotRecentEntries,
) {
  use id <- decode.field(0, decode.string)
  use seq <- decode.field(1, decode.optional(decode.int))
  use payload_bytes <- decode.field(2, decode.optional(decode.int))
  decode.success(SnapshotRecentEntries(id:, seq:, payload_bytes:))
}

pub type SnapshotEntryFragment {
  SnapshotEntryFragment(fragment: BitArray)
}

pub fn snapshot_entry_fragment(
  offset offset: Int,
  fragment_size fragment_size: Int,
  id id: String,
  seq seq: Option(Int),
  payload_bytes payload_bytes: Int,
) {
  let sql =
    "SELECT CAST(substr(payload, CAST(?1 AS INTEGER) + 1, ?2) AS BLOB) AS fragment FROM entries
WHERE id = ?3 AND seq = ?4 AND length(payload) = CAST(?5 AS INTEGER)"
  #(
    sql,
    [
      dev.ParamInt(offset),
      dev.ParamInt(fragment_size),
      dev.ParamString(id),
      dev.ParamNullable(option.map(seq, fn(v) { dev.ParamInt(v) })),
      dev.ParamInt(payload_bytes),
    ],
    snapshot_entry_fragment_decoder(),
  )
}

pub fn snapshot_entry_fragment_decoder() -> decode.Decoder(
  SnapshotEntryFragment,
) {
  use fragment <- decode.field(0, decode.bit_array)
  decode.success(SnapshotEntryFragment(fragment:))
}

pub type SnapshotEntryHead {
  SnapshotEntryHead(
    id: String,
    parent_id: Option(String),
    seq: Option(Int),
    payload_bytes: Option(Int),
  )
}

pub fn snapshot_entry_head(
  entry_id entry_id: String,
  before_seq before_seq: Option(Int),
) {
  let sql =
    "SELECT CAST(CASE WHEN length(CAST(id AS BLOB)) = 36 THEN id ELSE '' END AS TEXT) AS id,
  parent_id, seq, length(payload) AS payload_bytes FROM entries
WHERE id = ?1 AND seq < ?2 LIMIT 2"
  #(
    sql,
    [
      dev.ParamString(entry_id),
      dev.ParamNullable(option.map(before_seq, fn(v) { dev.ParamInt(v) })),
    ],
    snapshot_entry_head_decoder(),
  )
}

pub fn snapshot_entry_head_decoder() -> decode.Decoder(SnapshotEntryHead) {
  use id <- decode.field(0, decode.string)
  use parent_id <- decode.field(1, decode.optional(decode.string))
  use seq <- decode.field(2, decode.optional(decode.int))
  use payload_bytes <- decode.field(3, decode.optional(decode.int))
  decode.success(SnapshotEntryHead(id:, parent_id:, seq:, payload_bytes:))
}
