//// Code generated by parrot. DO NOT EDIT.
////

import gleam/dynamic/decode
import parrot/dev

pub fn insert_entry_text(
  session_id session_id: String,
  entry_id entry_id: String,
  text text: String,
) {
  let sql =
    "
INSERT INTO entry_fts (session_id, entry_id, text)
VALUES (?, ?, ?)"
  #(sql, [
    dev.ParamString(session_id),
    dev.ParamString(entry_id),
    dev.ParamString(text),
  ])
}

pub fn delete_session_index(session_id session_id: String) {
  let sql = "DELETE FROM entry_fts WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)])
}

pub type SearchEntries {
  SearchEntries(session_id: String, entry_id: String, snippet: String)
}

pub fn search_entries(text text: String, limit limit: Int) {
  let sql =
    "SELECT
  session_id,
  entry_id,
  snippet(entry_fts, 2, '[', ']', '...', 12) AS snippet
FROM entry_fts
WHERE entry_fts.text MATCH ?
ORDER BY rank
LIMIT ?"
  #(sql, [dev.ParamString(text), dev.ParamInt(limit)], search_entries_decoder())
}

pub fn search_entries_decoder() -> decode.Decoder(SearchEntries) {
  use session_id <- decode.field(0, decode.string)
  use entry_id <- decode.field(1, decode.string)
  use snippet <- decode.field(2, decode.string)
  decode.success(SearchEntries(session_id:, entry_id:, snippet:))
}

pub type SearchEntriesInSession {
  SearchEntriesInSession(session_id: String, entry_id: String, snippet: String)
}

pub fn search_entries_in_session(
  text text: String,
  session_id session_id: String,
  limit limit: Int,
) {
  let sql =
    "SELECT
  session_id,
  entry_id,
  snippet(entry_fts, 2, '[', ']', '...', 12) AS snippet
FROM entry_fts
WHERE entry_fts.text MATCH ?
  AND session_id = ?
ORDER BY rank
LIMIT ?"
  #(
    sql,
    [dev.ParamString(text), dev.ParamString(session_id), dev.ParamInt(limit)],
    search_entries_in_session_decoder(),
  )
}

pub fn search_entries_in_session_decoder() -> decode.Decoder(
  SearchEntriesInSession,
) {
  use session_id <- decode.field(0, decode.string)
  use entry_id <- decode.field(1, decode.string)
  use snippet <- decode.field(2, decode.string)
  decode.success(SearchEntriesInSession(session_id:, entry_id:, snippet:))
}

pub type GetCursor {
  GetCursor(generation: Int, high_water: Int)
}

pub fn get_cursor(session_id session_id: String) {
  let sql =
    "SELECT generation, high_water
FROM search_cursor
WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)], get_cursor_decoder())
}

pub fn get_cursor_decoder() -> decode.Decoder(GetCursor) {
  use generation <- decode.field(0, decode.int)
  use high_water <- decode.field(1, decode.int)
  decode.success(GetCursor(generation:, high_water:))
}

pub fn set_cursor(
  session_id session_id: String,
  generation generation: Int,
  high_water high_water: Int,
) {
  let sql =
    "INSERT INTO search_cursor (session_id, generation, high_water)
VALUES (?, ?, ?)
ON CONFLICT (session_id) DO UPDATE SET
  generation = excluded.generation,
  high_water = excluded.high_water"
  #(sql, [
    dev.ParamString(session_id),
    dev.ParamInt(generation),
    dev.ParamInt(high_water),
  ])
}

pub fn delete_cursor(session_id session_id: String) {
  let sql = "DELETE FROM search_cursor WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)])
}

pub fn register_source(session_id session_id: String, path path: String) {
  let sql =
    "INSERT INTO search_source (session_id, path) VALUES (?, ?)
ON CONFLICT (session_id) DO UPDATE SET path = excluded.path"
  #(sql, [dev.ParamString(session_id), dev.ParamString(path)])
}

pub type GetSource {
  GetSource(path: String)
}

pub fn get_source(session_id session_id: String) {
  let sql = "SELECT path FROM search_source WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)], get_source_decoder())
}

pub fn get_source_decoder() -> decode.Decoder(GetSource) {
  use path <- decode.field(0, decode.string)
  decode.success(GetSource(path:))
}

pub fn delete_source(session_id session_id: String) {
  let sql = "DELETE FROM search_source WHERE session_id = ?"
  #(sql, [dev.ParamString(session_id)])
}
