//// The enforcement tag vocabulary shared with the Go helper.
////
//// GENERATED by scripts/gen-tags.py from protocol/enforcement-tags.toml;
//// DO NOT EDIT. Change a spelling in the source and run `make gen-tags`;
//// `make tags-check` fails when this file and the source disagree.
//// source sha256: 94ee6475acc42ee37e29a0a263fba85fad2101d672d8e3a01ba728e748b19c30
////
//// These are the strings `packages/sandbox` writes into `hello.features`
//// and `exec_exit.enforcement`. `broker/exec` reads them back to decide
//// whether an execution's report satisfies an enforcement demand, so a
//// spelling that moved on one side only would refuse (or silently stop
//// requiring) a layer. The Go side gets the same constants from
//// `internal/jail/tags_gen.go`.

/// The layer tag `rlimits`.
///
/// Per-process resource ceilings; needs no kernel opt-in, so always
/// advertised. Emitted as: feature; on: linux, darwin, other.
pub const tag_rlimits: String = "rlimits"

/// The layer tag `pgroup`.
///
/// Each execution gets its own session and process group, signalled as a
/// unit. Emitted as: feature; on: linux, darwin, other.
pub const tag_pgroup: String = "pgroup"

/// The layer tag `degraded`.
///
/// The strongest platform jail (bwrap or Seatbelt) is unavailable on this
/// host. Emitted as: feature; on: linux, darwin, other.
pub const tag_degraded: String = "degraded"

/// The layer tag `platform-unsupported`.
///
/// The build has no jail for its operating system at all; worse than
/// degraded. Emitted as: feature; on: other.
pub const tag_platform_unsupported: String = "platform-unsupported"

/// The layer tag `bwrap`.
///
/// Bubblewrap namespaces and mount plan; applied only once stage 2 has
/// reported from inside. Emitted as: feature, applied, skip; on: linux.
pub const tag_bwrap: String = "bwrap"

/// The layer tag `landlock`.
///
/// Landlock filesystem rules, the second filesystem layer and the first in
/// degraded mode. Emitted as: feature, applied, skip; on: linux.
pub const tag_landlock: String = "landlock"

/// The layer tag `seccomp`.
///
/// Seccomp-filter support; the applied form is seccomp-net. Emitted as:
/// feature, skip; on: linux.
pub const tag_seccomp: String = "seccomp"

/// The layer tag `cgroup-v2`.
///
/// A per-execution cgroup v2 group holding the memory and process ceilings.
/// Emitted as: feature, applied, skip; on: linux.
pub const tag_cgroup_v2: String = "cgroup-v2"

/// The layer tag `seatbelt`.
///
/// The macOS Seatbelt profile (sandbox-exec) entered around the execution.
/// Emitted as: feature, applied, skip; on: darwin.
pub const tag_seatbelt: String = "seatbelt"

/// The layer tag `mounts`.
///
/// The audited mount plan: applied carries counts and a plan digest,
/// skipped names a widened path. Emitted as: applied, skip; on: linux.
pub const tag_mounts: String = "mounts"

/// The layer tag `no-new-privs`.
///
/// PR_SET_NO_NEW_PRIVS: no privilege gain through setuid binaries or file
/// capabilities. Emitted as: applied, skip; on: linux.
pub const tag_no_new_privs: String = "no-new-privs"

/// The layer tag `seccomp-net`.
///
/// A seccomp filter denying direct sockets under network off and proxy
/// policies. Emitted as: applied; on: linux.
pub const tag_seccomp_net: String = "seccomp-net"

/// The layer tag `seatbelt-fs`.
///
/// The Seatbelt filesystem plan, with root counts and a plan digest.
/// Emitted as: applied; on: darwin.
pub const tag_seatbelt_fs: String = "seatbelt-fs"

/// The layer tag `seatbelt-net`.
///
/// Seatbelt denial of direct network access under network off and proxy
/// policies. Emitted as: applied; on: darwin.
pub const tag_seatbelt_net: String = "seatbelt-net"

/// The layer tag `rlimit-fsize`.
///
/// RLIMIT_FSIZE ceiling on the size of any file the execution writes.
/// Emitted as: applied; on: linux, darwin.
pub const tag_rlimit_fsize: String = "rlimit-fsize"

/// The layer tag `rlimit-cpu`.
///
/// RLIMIT_CPU ceiling on CPU seconds. Emitted as: applied; on: linux,
/// darwin.
pub const tag_rlimit_cpu: String = "rlimit-cpu"

/// The layer tag `rlimit-address-space`.
///
/// RLIMIT_AS ceiling standing in for the memory limit, where the kernel
/// accepts one. Emitted as: applied, skip; on: darwin.
pub const tag_rlimit_address_space: String = "rlimit-address-space"

/// The layer tag `rlimit-processes`.
///
/// RLIMIT_NPROC ceiling standing in for the process limit; per-user, not
/// per-execution. Emitted as: applied, skip; on: darwin.
pub const tag_rlimit_processes: String = "rlimit-processes"

/// The layer tag `darwin-process-lifecycle`.
///
/// The one containment property Seatbelt cannot give: no PID namespace or
/// subreaper. Emitted as: skip; on: darwin.
pub const tag_darwin_process_lifecycle: String = "darwin-process-lifecycle"

/// The layer tag `stage2`.
///
/// Stage 2 sent no enforcement report, so its in-process layers cannot be
/// confirmed. Emitted as: skip; on: linux, darwin.
pub const tag_stage2: String = "stage2"

/// The layer tag `network-proxy`.
///
/// Proxy-mode network policy: direct network was disabled but the allowlist
/// was not enforced. Emitted as: skip; on: linux, darwin, other.
pub const tag_network_proxy: String = "network-proxy"

/// The layer tag `platform-restrictions`.
///
/// Stage 2 has no in-process driver for this operating system. Emitted as:
/// skip; on: other.
pub const tag_platform_restrictions: String = "platform-restrictions"

/// The layer tag `jail`.
///
/// Opens the platform-unsupported reason: this build has no sandbox for its
/// OS. Emitted as: skip; on: other.
pub const tag_jail: String = "jail"

/// The separator `skip:`.
///
/// Marks an enforcement entry as a layer that was NOT applied; the rest is
/// the layer tag and a reason.
pub const prefix_skip: String = "skip:"

/// The separator `landlock:abi=`.
///
/// Landlock applied entry; the number that follows is the kernel ABI
/// version.
pub const prefix_landlock_abi: String = "landlock:abi="

/// The separator `mounts:`.
///
/// Mount-audit applied entry; comma-separated counts and a plan digest
/// follow.
pub const prefix_mounts_report: String = "mounts:"

/// The separator `seatbelt-fs:`.
///
/// Seatbelt filesystem applied entry; comma-separated counts and a plan
/// digest follow.
pub const prefix_seatbelt_fs_report: String = "seatbelt-fs:"
