name = "ext"
version = "0.2.0"
gleam = ">= 1.18.0"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
cap = { path = "../cap" }
weft = { git = "https://github.com/Roasbeef/weft.git", ref = "f076c0661518ce9432cc6ff874b1ece71edbd9b7" }
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
core = { path = "../core" }
gleeunit = ">= 1.0.0 and < 2.0.0"
