name = "host"
version = "0.1.0"
target = "erlang"
gleam = ">= 1.18.0"

[dependencies]
core = { path = "../core" }
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
stratus = ">= 3.0.0 and < 4.0.0"
weft = "== 0.4.4"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 1.0.0 and < 2.0.0"
