#!/usr/bin/env python3
"""Embed an ASCII schema for releases without a runtime source-file dependency."""

import json
import pathlib
import sys


def main():
    source, destination = map(pathlib.Path, sys.argv[1:])
    schema = source.read_text(encoding="ascii")
    destination.write_text(
        "//// Generated by scripts/embed-sql-schema.py. DO NOT EDIT.\n"
        "//// The checked-in SQL file is the schema source of truth.\n\n"
        "/// The schema used both at runtime and by sqlc during generation.\n"
        "pub const schema = " + json.dumps(schema) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
