#!/usr/bin/env python3
"""gen-tags.py: render and gate the enforcement tag vocabulary.

    scripts/gen-tags.py              regenerate both outputs (needs python3)
    scripts/gen-tags.py --check      fail if either output or the source drifted
    scripts/gen-tags.py --self-test  prove --check catches each kind of drift

The source is protocol/enforcement-tags.toml. The outputs are

    packages/sandbox/internal/jail/tags_gen.go
    packages/broker/src/broker/tags.gleam

## Why a generated pair rather than one shared file

The Go helper writes these strings and the Gleam broker reads them, and
until now nothing but a test run tied the two spellings together. A tag
renamed on one side failed open in the worst direction: the broker stops
finding a layer the helper still reports, and a full-enforcement demand
is refused (or, for a layer added on one side only, never asked for).
Rendering both from one file makes the spelling a compile-time fact on
each side and makes drift a build failure here.

## Why --check needs only python3

It runs inside `make check` on every push, so like gen-prelude.sh it may
not add a toolchain to the merge gate. It regenerates in memory and
compares bytes. Each output records the sha256 of the source it was
rendered from, which lets the failure say which fix applies: a stale
digest means the source moved (run `make gen-tags`), a current digest
with different bytes means somebody edited a generated file (edit the
source instead).
"""

import hashlib
import re
import sys
import textwrap
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "protocol" / "enforcement-tags.toml"
GO_OUT = ROOT / "packages" / "sandbox" / "internal" / "jail" / "tags_gen.go"
GLEAM_OUT = ROOT / "packages" / "broker" / "src" / "broker" / "tags.gleam"

KINDS = ("feature", "applied", "skip")
PLATFORMS = ("linux", "darwin", "other")
DIGEST_RE = re.compile(r"source sha256: ([0-9a-f]{64})")


class SourceError(Exception):
    """The TOML source is malformed; the message names the entry."""


def digest(text):
    return hashlib.sha256(text.encode()).hexdigest()


def parse(text):
    """Validate the source and return (tags, prefixes)."""
    doc = tomllib.loads(text)
    tags, prefixes = doc.get("tag", []), doc.get("prefix", [])
    seen = set()
    for t in tags:
        tid = t.get("id", "")
        if not re.fullmatch(r"[a-z][a-z0-9]*(-[a-z0-9]+)*", tid):
            raise SourceError(f"tag id {tid!r} is not kebab-case")
        if tid in seen:
            raise SourceError(f"duplicate id {tid!r}")
        seen.add(tid)
        if not t.get("kinds") or not set(t["kinds"]) <= set(KINDS):
            raise SourceError(f"{tid}: kinds must be a non-empty subset of {KINDS}")
        if not t.get("platforms") or not set(t["platforms"]) <= set(PLATFORMS):
            raise SourceError(f"{tid}: platforms must be a non-empty subset of {PLATFORMS}")
        if not t.get("meaning"):
            raise SourceError(f"{tid}: meaning is required")
    for p in prefixes:
        pid = p.get("id", "")
        if not re.fullmatch(r"[a-z][a-z0-9]*(-[a-z0-9]+)*", pid):
            raise SourceError(f"prefix id {pid!r} is not kebab-case")
        if pid in seen:
            raise SourceError(f"duplicate id {pid!r}")
        seen.add(pid)
        if not p.get("value", "").endswith((":", "=")):
            raise SourceError(f"prefix {pid}: value must end in ':' or '='")
        if not p.get("meaning"):
            raise SourceError(f"prefix {pid}: meaning is required")
    return tags, prefixes


def camel(ident):
    return "".join(part.capitalize() for part in ident.split("-"))


def snake(ident):
    return ident.replace("-", "_")


def describe(entry):
    """The doc sentence set for one entry, as wrapped plain text lines."""
    if "value" in entry:
        facts = ""
    else:
        facts = " Emitted as: %s; on: %s." % (
            ", ".join(entry["kinds"]), ", ".join(entry["platforms"]))
    return textwrap.wrap(entry["meaning"] + facts, width=72)


def go_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_go(tags, prefixes, src_digest):
    out = [
        "// Code generated by scripts/gen-tags.py from protocol/enforcement-tags.toml; DO NOT EDIT.",
        "// source sha256: " + src_digest,
        "",
        "package jail",
        "",
        "// The enforcement tag vocabulary: the strings this helper writes into",
        "// hello.features and exec_exit.enforcement, and that the broker's",
        "// exec.gleam reads back through the generated broker/tags module. Edit",
        "// protocol/enforcement-tags.toml and run `make gen-tags`; never this file.",
    ]
    for t in tags:
        out += ["", "// Tag%s is the layer tag %s." % (camel(t["id"]), go_string(t["id"]))]
        out += ["// " + line for line in describe(t)]
        out.append("const Tag%s = %s" % (camel(t["id"]), go_string(t["id"])))
    for p in prefixes:
        out += ["", "// Prefix%s is the separator %s." % (camel(p["id"]), go_string(p["value"]))]
        out += ["// " + line for line in describe(p)]
        out.append("const Prefix%s = %s" % (camel(p["id"]), go_string(p["value"])))
    return "\n".join(out) + "\n"


def render_gleam(tags, prefixes, src_digest):
    out = [
        "//// The enforcement tag vocabulary shared with the Go helper.",
        "////",
        "//// GENERATED by scripts/gen-tags.py from protocol/enforcement-tags.toml;",
        "//// DO NOT EDIT. Change a spelling in the source and run `make gen-tags`;",
        "//// `make tags-check` fails when this file and the source disagree.",
        "//// source sha256: " + src_digest,
        "////",
        "//// These are the strings `packages/sandbox` writes into `hello.features`",
        "//// and `exec_exit.enforcement`. `broker/exec` reads them back to decide",
        "//// whether an execution's report satisfies an enforcement demand, so a",
        "//// spelling that moved on one side only would refuse (or silently stop",
        "//// requiring) a layer. The Go side gets the same constants from",
        "//// `internal/jail/tags_gen.go`.",
    ]
    for t in tags:
        out += ["", "/// The layer tag `%s`." % t["id"], "///"]
        out += ["/// " + line for line in describe(t)]
        out.append('pub const tag_%s: String = "%s"' % (snake(t["id"]), t["id"]))
    for p in prefixes:
        out += ["", "/// The separator `%s`." % p["value"], "///"]
        out += ["/// " + line for line in describe(p)]
        out.append('pub const prefix_%s: String = "%s"' % (snake(p["id"]), p["value"]))
    return "\n".join(out) + "\n"


def render_all(text):
    tags, prefixes = parse(text)
    d = digest(text)
    return {GO_OUT: render_go(tags, prefixes, d), GLEAM_OUT: render_gleam(tags, prefixes, d)}


def verdicts(source_text, files):
    """Problems between a source text and the on-disk outputs, as strings."""
    problems = []
    try:
        want = render_all(source_text)
    except (SourceError, tomllib.TOMLDecodeError) as e:
        return [f"{SOURCE.relative_to(ROOT)}: {e}"]
    current = digest(source_text)
    for path, body in want.items():
        rel = path.relative_to(ROOT)
        have = files.get(path)
        if have is None:
            problems.append(f"{rel}: missing; run `make gen-tags`")
            continue
        m = DIGEST_RE.search(have)
        if not m or m.group(1) != current:
            problems.append(
                f"{rel}: rendered from an older enforcement-tags.toml; run `make gen-tags`")
        elif have != body:
            problems.append(
                f"{rel}: edited by hand; change protocol/enforcement-tags.toml "
                "and run `make gen-tags`")
    return problems


def read_outputs():
    return {p: p.read_text() for p in (GO_OUT, GLEAM_OUT) if p.exists()}


def generate():
    for path, body in render_all(SOURCE.read_text()).items():
        path.write_text(body)
        print(f"wrote {path.relative_to(ROOT)}")


def check():
    problems = verdicts(SOURCE.read_text(), read_outputs())
    for p in problems:
        print(f"tags-check: {p}", file=sys.stderr)
    if problems:
        return 1
    print("tags-check: enforcement tag vocabulary is in sync")
    return 0


def self_test():
    """Each kind of drift must be reported; the clean state must not be."""
    src = SOURCE.read_text()
    clean = render_all(src)
    assert verdicts(src, clean) == [], "clean state reported as drift"
    renamed = src.replace('id = "seccomp-net"', 'id = "seccomp-netx"', 1)
    assert any("older" in p for p in verdicts(renamed, clean)), "source edit not caught"
    hand = dict(clean)
    hand[GLEAM_OUT] = hand[GLEAM_OUT].replace('"bwrap"', '"bwrapx"', 1)
    assert any("by hand" in p for p in verdicts(src, hand)), "gleam hand-edit not caught"
    hand = dict(clean)
    hand[GO_OUT] = hand[GO_OUT].replace('"bwrap"', '"bwrapx"', 1)
    assert any("by hand" in p for p in verdicts(src, hand)), "go hand-edit not caught"
    missing = {GO_OUT: clean[GO_OUT]}
    assert any("missing" in p for p in verdicts(src, missing)), "missing output not caught"
    assert verdicts("[[tag]]\nid = 'A'\n", clean), "malformed source accepted"
    print("tags-check self-test: ok")
    return 0


def main(argv):
    if argv == ["--check"]:
        return check()
    if argv == ["--self-test"]:
        return self_test()
    if argv:
        print(__doc__, file=sys.stderr)
        return 2
    generate()
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
