#!/usr/bin/env bash
# Build a self-contained OTP release of the Loom terminal client into
# build/release/loom-client — the BEAM runtime system included, so the
# machine that runs `loom` needs no Erlang installed.
#
#   scripts/release-client.sh          # build the release tree
#   scripts/release-client.sh --smoke  # boot it with no erl on PATH
#
# This is the server's scripts/release.sh applied to the client, and it
# is the same argument: a shipment (`make tui-shipment`) is compiled BEAM
# files that need an OTP installation on the host, and `include_erts`
# copies the runtime in beside them. The shipment is not retired by this
# — it is what a package manager that already provides Erlang wants, and
# `INSTALL_CLIENT=slim make install` still installs it. What differs from
# the server release is everything the client does not have: no helper,
# no compiler, no seed, no NIF, so a client release is the runtime and
# the client and nothing else.
#
# The copied ERTS is this machine's, so the release is per-platform by
# construction; see docs/distribution.md.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd)"

STRIP_ERTS="${DIST_STRIP_ERTS:-1}"
REL_ROOT="$ROOT/build/release"
REL="$REL_ROOT/loom-client"
WORK="$REL_ROOT/work-client"
SMOKE=0
[ "${1-}" = "--smoke" ] && SMOKE=1

# ------------------------------------------------------------ smoke only
# The claim under test is that the built client runs with no Erlang on
# the host, so the smoke asks nothing of PATH beyond the system shell
# tools. It boots the bundled emulator exactly as the launcher does — the
# same boot file, the same code path — and asks it to load the client's
# entry module, then halt. The client itself is not run: it is a terminal
# program and, given no terminal, it waits for one rather than exiting,
# which is correct for a client and useless for a smoke. Loading the
# module is the whole claim anyway: the runtime is there, it boots, and
# the client's code is on its path.
if [ "$SMOKE" = 1 ]; then
  [ -x "$REL/bin/loom" ] || {
    echo "release-client.sh: no release at $REL — run \`make release-client\` first" >&2
    exit 1; }
  erts_bin="$(ls -d "$REL"/erts-*/bin | head -1)"
  out="$(env -i PATH=/usr/bin:/bin HOME="${HOME:-/tmp}" \
    "$erts_bin/erl" -boot "$REL/bin/no_dot_erlang" -pa "$REL"/lib/*/ebin -noshell \
    -eval '{module, M} = code:ensure_loaded(tui@@main), io:format("~s~n", [M]), halt().' \
    2>&1 || true)"
  case "$out" in
    "tui@@main") echo "release-client smoke: the bundled runtime boots and loads the client without erl on PATH" ;;
    *) echo "release-client smoke: the bundled runtime did not load the client:" >&2
       printf '%s\n' "$out" | sed 's/^/  /' >&2
       exit 1 ;;
  esac
  exit 0
fi

# ------------------------------------------------------------ preflight
missing=""
need() { command -v "$1" >/dev/null 2>&1 || missing="$missing  $1 — $2\n"; }
need gleam  "exports the tui package as an erlang shipment (>= 1.18)"
need rebar3 "assembles the OTP release and copies ERTS into it"
need erl    "the runtime system that gets copied in (OTP >= 29)"
if [ "$STRIP_ERTS" = 1 ]; then
  need strip "strips the copied ERTS binaries (DIST_STRIP_ERTS=0 to skip)"
fi
if [ -n "$missing" ]; then
  printf 'release-client.sh: cannot build a release, these are not on PATH:\n' >&2
  printf '%b' "$missing" >&2
  exit 1
fi
VERSION="$(sed -n 's/^version *= *"\(.*\)"/\1/p' packages/tui/gleam.toml | head -1)"
[ -n "$VERSION" ] || { echo "release-client.sh: no version in packages/tui/gleam.toml" >&2; exit 1; }
ERTS_VSN="$(erl -noshell -eval 'io:format("~s",[erlang:system_info(version)]),halt().')"

# ------------------------------------------------------------ the build
echo "==> exporting the client shipment"
( cd packages/tui && gleam export erlang-shipment >/dev/null )
rm -rf "$REL" "$WORK"
mkdir -p "$WORK/libs"
cp -R packages/tui/build/erlang-shipment/. "$WORK/libs/"
rm -f "$WORK/libs/entrypoint.sh" "$WORK/libs/entrypoint.ps1"

# The release is named for the product's client so its directory reads
# right in a tarball listing; relx works out the OTP application closure
# (crypto, ssl, inets for the websocket) from lib_dirs by itself.
cat > "$WORK/rebar.config" <<EOF
%% Generated by scripts/release-client.sh. Edit the script, not this file.
{erl_opts, []}.
{deps, []}.
{project_app_dirs, []}.
{relx, [
  {release, {loom_client, "$VERSION"}, [tui]},
  {lib_dirs, ["libs"]},
  {include_erts, true},
  {include_src, false},
  {dev_mode, false},
  {debug_info, strip}
]}.
EOF

echo "==> assembling the release (rebar3 relx)"
( cd "$WORK" && rebar3 release >/dev/null )
mkdir -p "$REL_ROOT"
mv "$WORK/_build/default/rel/loom_client" "$REL"
rm -rf "$WORK"

# The same trimming the server release gets, for the same reasons: relx's
# launcher is a distributed-node supervisor Loom has no use for and a
# guessable cookie is not a default the two-channel doctrine permits;
# vm.args and sys.config are read only by that launcher; the *.boot files
# stay because the bundled emulator boots from bin/.
find "$REL/bin" -maxdepth 1 -type f ! -name '*.boot' -delete
rm -f "$REL/releases/$VERSION/vm.args" \
      "$REL/releases/$VERSION/sys.config"
[ -f "$REL/bin/no_dot_erlang.boot" ] || {
  echo "release-client.sh: relx left no bin/no_dot_erlang.boot" >&2; exit 1; }

if [ "$STRIP_ERTS" = 1 ]; then
  echo "==> stripping the copied ERTS"
  find "$REL/erts-$ERTS_VSN/bin" -type f -exec sh -c '
    file -b "$1" | grep -q "ELF.*not stripped" && strip -s "$1"' _ {} \; || true
fi

# The launcher: the shipment entrypoint's invocation over the bundled
# `erl`, booting `no_dot_erlang` so nobody's ~/.erlang runs inside the
# client, with `+Bd` so ctrl+c reaches the client rather than the BEAM
# break handler. LOOM_EXECUTABLE is how the client learns where it is,
# and so where a sibling `loomd` would be; an installer that puts a
# wrapper on PATH sets it first, so it is only defaulted here.
cat > "$REL/bin/loom" <<EOF
#!/bin/sh
# Generated by scripts/release-client.sh. The Loom terminal client.
set -eu
here=\$(CDPATH= cd -- "\$(dirname -- "\$0")" && pwd -P)
root=\$(dirname "\$here")
: "\${LOOM_EXECUTABLE:=\$here/loom}"
export LOOM_EXECUTABLE

exec "\$root/erts-$ERTS_VSN/bin/erl" +Bd \\
  -boot "\$root/bin/no_dot_erlang" \\
  -pa "\$root"/lib/*/ebin \\
  -noshell \\
  -eval 'tui@@main:run(tui)' \\
  -extra "\$@"
EOF
chmod +x "$REL/bin/loom"

SHA256=sha256sum
command -v sha256sum >/dev/null 2>&1 || SHA256="shasum -a 256"
( cd "$REL" && find . -type f -perm -u+x | LC_ALL=C sort -u \
    | tr '\n' '\0' | xargs -0 $SHA256 > SHA256SUMS )

echo
echo "client release: $REL"
for p in "$REL" "$REL/erts-$ERTS_VSN" "$REL/lib"; do
  du -sh "$p" | sed 's/^/  /'
done
