name = "broker"
version = "0.2.0"
gleam = ">= 1.18.0"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
core = { path = "../core" }
telemetry = { path = "../telemetry" }
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
envoy = ">= 1.0.0 and < 2.0.0"
weft = { git = "https://github.com/Roasbeef/weft.git", ref = "f076c0661518ce9432cc6ff874b1ece71edbd9b7" }

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
