name = "mcp"
version = "0.2.0"
gleam = ">= 1.18.0"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
core = { path = "../core" }
gleam_mcp = { git = "https://github.com/Roasbeef/gleam-mcp.git", ref = "d829a35f90be380ab1c659016aec752ebff67a95" }

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
